import type {
  IAttackInvalidPayload,
  IToHitModifier,
} from './GameSessionAttackEvents';
import type { IHexCoordinate, RangeBracket } from './HexGridInterfaces';
import type { IndirectFireBasis } from './IndirectFireInterfaces';
import type { CoverLevel, TerrainType } from './TerrainTypes';

export type CombatLOSState = 'clear' | 'partial' | 'blocked';

export type CombatFiringArc =
  | 'front'
  | 'left-side'
  | 'right-side'
  | 'rear'
  | 'out-of-arc';

export type CombatTargetVisibilityState =
  | 'none'
  | 'visible'
  | 'hidden'
  | 'lastKnown'
  | 'mixed';

export type CombatLineOfSightBlockerKind =
  | 'terrain'
  | 'elevation'
  | 'cover'
  | 'unknown';

export interface ICombatLineOfSightBlocker {
  /** Intervening hex responsible for blocked or partial LOS. */
  readonly hex: IHexCoordinate;
  /** Player-facing blocker category for compact map badges. */
  readonly kind: CombatLineOfSightBlockerKind;
  /** Blocking or modifying terrain type when the classifier identified one. */
  readonly terrain?: TerrainType;
  /** Player-facing explanation from the shared LOS classifier. */
  readonly reason: string;
}

export interface ICombatWeaponImpact {
  /** Weapon status id included in the projected available volley. */
  readonly weaponId: string;
  /** Player-facing weapon name included in the projected available volley. */
  readonly weaponName: string;
  /** Heat generated by this weapon if it is fired. */
  readonly heat: number;
  /** Listed damage contributed by this weapon in the projected volley. */
  readonly damage: number;
  /** Ammo shots consumed by this weapon; 0 for energy or unlimited weapons. */
  readonly ammoConsumed: number;
  /** Ammo remaining before fire, when the weapon consumes represented ammo. */
  readonly ammoRemaining?: number;
}

export interface ICombatWeaponRangeOption extends ICombatWeaponImpact {
  /** Weapon range bracket at this hex distance. */
  readonly rangeBracket: RangeBracket;
  /** This weapon's range profile covers this hex. */
  readonly inRange: boolean;
  /** This weapon's mounting arc covers this hex. */
  readonly inArc: boolean;
  /** Represented environment rules allow this weapon against this hex. */
  readonly environmentLegal: boolean;
  /** This weapon satisfies range, arc, and represented environment rules. */
  readonly available: boolean;
  /** Minimum-range to-hit penalty for this weapon at this hex, when any. */
  readonly minimumRangePenalty?: number;
  /** Engine-style target number for this weapon when committed alone. */
  readonly toHitNumber?: number;
  /** Engine-style modifier stack for this weapon's target number. */
  readonly toHitModifiers?: readonly IToHitModifier[];
  /** Player-facing to-hit summary for this weapon. */
  readonly toHitReason?: string;
  /** Hit-probability-weighted damage for this weapon when available. */
  readonly expectedDamage?: number;
  /** Player-facing reason this weapon is unavailable, when blocked. */
  readonly blockedReason?: string;
}

/**
 * Rules-backed tactical attack projection for one map hex. The map uses this
 * as an explanation layer: range, arc, LOS, target presence, and blocked reason
 * are all derived before the player commits an attack.
 */
export interface ICombatRangeHex {
  /** Hex position */
  readonly hex: IHexCoordinate;
  /** Distance from attacker to this hex */
  readonly distance: number;
  /** Best weapon range bracket covering this hex */
  readonly rangeBracket: RangeBracket;
  /** At least one operational weapon can reach this hex */
  readonly inRange: boolean;
  /** At least one operational weapon can cover this target arc */
  readonly inArc: boolean;
  /** Line-of-sight classifier result */
  readonly losState: CombatLOSState;
  /** Player-facing direct-LOS blocker explanation, even when indirect fire is legal */
  readonly lineOfSightBlockerReason?: string;
  /** Intervening LOS blocker or partial-cover hex from the shared classifier */
  readonly lineOfSightBlocker?: ICombatLineOfSightBlocker;
  /** Cover level provided by the target hex terrain */
  readonly targetCoverLevel: CoverLevel;
  /** Target hex grants partial cover to an occupant */
  readonly targetPartialCover: boolean;
  /** To-hit modifier contributed by target hex cover */
  readonly targetCoverModifier: number;
  /** Player-facing explanation for target hex cover, when any */
  readonly targetCoverReason?: string;
  /** Target unit is represented as hull-down. */
  readonly targetHullDown?: boolean;
  /** To-hit modifier contributed by represented hull-down state. */
  readonly targetHullDownModifier?: number;
  /** Player-facing explanation for represented hull-down state. */
  readonly targetHullDownReason?: string;
  /** Highest selected-weapon minimum-range to-hit penalty at this distance */
  readonly minimumRangePenalty?: number;
  /** Weapons contributing the displayed minimum-range penalty */
  readonly minimumRangeWeaponIds?: readonly string[];
  /** Player-facing minimum-range explanation */
  readonly minimumRangeReason?: string;
  /** Engine-style target number preview for an attack committed against this hex */
  readonly toHitNumber?: number;
  /** Engine-style to-hit modifier stack used to build toHitNumber */
  readonly toHitModifiers?: readonly IToHitModifier[];
  /** Player-facing to-hit summary */
  readonly toHitReason?: string;
  /** C3 network improved the range bracket used by this preview */
  readonly c3BenefitApplied?: boolean;
  /** C3 unit whose target range supplied the improved bracket */
  readonly c3SpotterId?: string | null;
  /** Range from the C3 spotter to the projected target */
  readonly c3SpotterRange?: number | null;
  /** Firing arc classifier result */
  readonly firingArc: CombatFiringArc;
  /** Hex has at least one enemy target token */
  readonly hasTarget: boolean;
  /** Best player-facing visibility state for enemy contacts on this hex */
  readonly targetVisibilityState: CombatTargetVisibilityState;
  /** Enemy unit ids on this hex that are currently visible to the viewer */
  readonly visibleTargetUnitIds: readonly string[];
  /** Enemy contact ids represented only by hidden / last-known fog markers */
  readonly obscuredTargetUnitIds: readonly string[];
  /** Player-facing reason a fog contact cannot be committed as an attack */
  readonly visibilityBlockedReason?: string;
  /** A player-facing attack can be committed against a target in this hex */
  readonly attackable: boolean;
  /** Operational weapon ids whose range profile covers this hex */
  readonly weaponIdsInRange: readonly string[];
  /** Operational weapon ids whose mounting arc covers this hex */
  readonly weaponIdsInArc: readonly string[];
  /** Operational weapon ids satisfying both range and mounting arc */
  readonly weaponIdsAvailable: readonly string[];
  /** Per-weapon range, arc, environment, and availability details */
  readonly weaponRangeOptions: readonly ICombatWeaponRangeOption[];
  /** Per-weapon heat and ammo impact for weapons satisfying range, arc, and environment rules */
  readonly availableWeaponImpacts: readonly ICombatWeaponImpact[];
  /** Total heat generated by available weapons if fired together */
  readonly availableWeaponHeat: number;
  /** Aggregate listed damage for available weapons if fired together */
  readonly availableWeaponDamage: number;
  /** Sum of per-weapon hit-probability-weighted damage for the projected attack, when known */
  readonly expectedDamage?: number;
  /** Enemy unit ids occupying this hex */
  readonly targetUnitIds: readonly string[];
  /** Enemy unit ids occupying this hex and satisfying range/arc/LOS */
  readonly validTargetUnitIds: readonly string[];
  /** Engine-aligned attack rejection reason for enemy targets on this hex */
  readonly attackInvalidReason?: IAttackInvalidPayload['reason'];
  /** Engine-style detail string paired with attackInvalidReason */
  readonly attackInvalidDetails?: string;
  /** Player-facing reason a target here is blocked or tactically unavailable */
  readonly blockedReason?: string;
  /** LOS-blocked attack can still be committed through indirect fire */
  readonly indirectFireAvailable?: boolean;
  /** Spotter unit selected for LOS-based indirect fire, when any */
  readonly indirectFireSpotterId?: string | null;
  /** Why indirect fire is legal: LOS spotter, beacon, or semi-guided TAG */
  readonly indirectFireBasis?: IndirectFireBasis;
  /** To-hit penalty contributed by indirect fire */
  readonly indirectFireToHitPenalty?: number;
  /** Gunnery skill of the elected LOS spotter, when represented */
  readonly indirectFireSpotterGunnery?: number;
  /** Spotter-skill modifier folded into the indirect-fire penalty */
  readonly indirectFireSpotterSkillModifier?: number;
  /** Forward Observer SPA cancelled the walked-spotter indirect-fire add */
  readonly indirectFireForwardObserver?: boolean;
  /** Indirect-fire penalty points cancelled by Forward Observer */
  readonly indirectFirePenaltyCancelled?: number;
  /** Player-facing indirect-fire explanation */
  readonly indirectFireReason?: string;
  /** Player-facing reason an indirect-fire fallback is unavailable */
  readonly indirectFireUnavailableReason?: string;
}
