/**
 * Game session attack, heat, and PSR event payloads
 * Extracted from GameSessionInterfaces.ts to keep focused type modules under the lint line cap.
 */

import type {
  AttackVisualCategory,
  HeatVisualThreshold,
} from './GameSessionCoreTypes';
import type { IINarcPodState } from './GameSessionStateTypes';

import { Facing, FiringArc, IHexCoordinate } from './HexGridInterfaces';
import { PSRTrigger } from './PSRTriggerCodes';

/**
 * Attack declared event payload.
 */
export interface IAttackDeclaredPayload {
  /** Attacking unit */
  readonly attackerId: string;
  /** Target unit */
  readonly targetId: string;
  /** Weapon ID(s) used (backward-compatible) */
  readonly weapons: readonly string[];
  /** Selected firing mode by weapon id for multi-mode weapons. */
  readonly weaponModes?: Readonly<Record<string, string>>;
  /**
   * Defender-selected AMS mount id by incoming attacker weapon id. Optional
   * because automatic AMS assignment remains the legacy/default behavior.
   */
  readonly selectedAMSWeaponIds?: Readonly<Record<string, string>>;
  /**
   * Replayable defender mount snapshots for selected AMS ids, keyed by the
   * incoming attacker weapon id. Populated by interactive/runtime declaration
   * paths that still have access to defender weapon caches; replay resolvers
   * must not reach back into those caches.
   */
  readonly selectedAMSWeaponMounts?: Readonly<
    Record<string, ISelectedAMSWeaponMountData>
  >;
  /** Full weapon attack data (damage, heat, ranges per weapon) */
  readonly weaponAttacks?: readonly IWeaponAttackData[];
  /** Calculated to-hit number */
  readonly toHitNumber: number;
  /** All to-hit modifiers */
  readonly modifiers: readonly IToHitModifier[];
  /**
   * Per `add-combat-fidelity-suite` Phase 2 (`combat-resolution` delta):
   * range bracket the to-hit calculation used. Values match the
   * `RangeBracket` enum string values (`'short' | 'medium' | 'long' |
   * 'extreme'`); `'out_of_range'` is filtered upstream and emits
   * `AttackInvalid` instead. Optional for backward compatibility with
   * pre-P2 callers (legacy InteractiveSession multi-weapon emission
   * path doesn't yet populate it).
   */
  readonly range?: 'short' | 'medium' | 'long' | 'extreme';
  /**
   * Per `add-combat-fidelity-suite` Phase 2: firing arc relative to the
   * target's facing the to-hit calculation used. Symmetric with
   * `IAttackResolvedPayload.attackerArc`. Optional for backward
   * compatibility.
   */
  readonly firingArc?: 'front' | 'left' | 'right' | 'rear';
}

export interface ISelectedAMSWeaponMountData {
  /** Selected defender AMS runtime mount id. */
  readonly weaponId: string;
  /** Selected defender AMS display/catalog name. */
  readonly weaponName: string;
  /** Heat generated by firing the AMS mount. */
  readonly heat: number;
  /** Ammo type consumed by this mount when it is not an energy AMS. */
  readonly ammoWeaponType?: string;
  /** Mounted firing arc, when known. Missing preserves legacy permissive arc. */
  readonly mountingArc?: FiringArc;
  /** Multi-arc mount coverage, when known. */
  readonly mountingArcs?: readonly FiringArc[];
  /** Explicit multi-use AMS mount state, when already authored. */
  readonly amsMultiUse?: boolean;
}

/**
 * All attack declarations for the weapon phase are locked and may now be
 * exposed to every participant. The individual `AttackDeclared` events remain
 * the source of weapon/target detail; this payload captures the reveal boundary.
 */
export interface IAttacksRevealedPayload {
  /** Active units whose weapon-phase declarations are now revealed. */
  readonly unitIds: readonly string[];
  /** Number of AttackDeclared events revealed for this turn. */
  readonly attackCount: number;
}

/**
 * Weapon attack data stored in attack events.
 * Carries the real weapon stats so resolveAttack can use actual damage/heat values.
 */
export interface IWeaponAttackData {
  /** Weapon ID */
  readonly weaponId: string;
  /** Weapon name */
  readonly weaponName: string;
  /** Damage per hit */
  readonly damage: number;
  /** Heat generated */
  readonly heat: number;
}

/**
 * Attack resolved event payload.
 */
export interface IAttackResolvedPayload {
  /** Attacking unit */
  readonly attackerId: string;
  /** Target unit */
  readonly targetId: string;
  /** Weapon used */
  readonly weaponId: string;
  /** Dice roll result */
  readonly roll: number;
  /** To-hit number */
  readonly toHitNumber: number;
  /** Hit or miss */
  readonly hit: boolean;
  /** Hit location (if hit) */
  readonly location?: string;
  /** Damage dealt (if hit) */
  readonly damage?: number;
  /**
   * Heat generated by firing this weapon. Set to the weapon's catalog heat
   * value (per `wire-real-weapon-data`). UI consumers and `gameSessionHeat`
   * read this to accumulate firing heat on the attacker during the heat
   * phase instead of approximating `weapons.length * N`.
   */
  readonly heat?: number;
  /**
   * Firing arc used to select the hit-location table (per
   * `wire-firing-arc-resolution`). Exposed on the event so UI + replay
   * consumers can show "AC/20 hit rear CT" rather than assuming Front.
   * Values match the `FiringArc` enum ('front' | 'left' | 'right' |
   * 'rear'). Absent on misses (no arc needed) and on same-hex
   * invalidations.
   */
  readonly attackerArc?: 'front' | 'left' | 'right' | 'rear';
  /**
   * Per `wire-ammo-consumption`: `null` for energy weapons; set to the
   * bin id that was drawn from for ammo-consuming weapons. Enables UI
   * + replay consumers to trace which bin fed each shot.
   */
  readonly ammoBinId?: string | null;
  /**
   * Phase 7 tactical visual hint. Optional so existing event streams and
   * combat resolvers remain replay-compatible; UI layers may derive a
   * category from weapon metadata when this is absent.
   */
  readonly visualCategory?: AttackVisualCategory;
  /**
   * Stable subtype key for visual color/stagger maps, such as
   * `medium-laser`, `lrm-20`, or `kick`. Optional for legacy streams.
   */
  readonly visualSubtype?: string;
  /**
   * Projectile/tracer count for cluster and multi-shot weapons. Optional
   * because non-cluster weapons can render a single primitive by default.
   */
  readonly projectileCount?: number;
  /**
   * Per `add-authoritative-roll-arbitration` (Wave 3a): every individual
   * d6 the server consumed for this event, in consumption order
   * (typically the to-hit 2d6 + the location 2d6 on hit). OPTIONAL so
   * single-player / hot-seat resolvers compile without populating it.
   */
  readonly rolls?: readonly number[];
  /** True when a legal Edge trigger replaced the original hit-location roll. */
  readonly edgeReroll?: boolean;
  /** True when the original hit-location roll was superseded by Edge. */
  readonly edgeSuperseded?: boolean;
  /** Trigger-specific Edge ability spent for the hit-location reroll. */
  readonly edgeTrigger?: string;
  /** Remaining Edge points after the hit-location reroll. */
  readonly edgePointsRemaining?: number;
  /** Original hit location replaced by Edge. */
  readonly edgeSupersededLocation?: string;
  /** Original hit-location roll total replaced by Edge. */
  readonly edgeSupersededRoll?: number;
}

/**
 * Fog-of-war redacted attack resolution. Sent to the target owner when the
 * attacker is hidden; weapon and attacker identifiers are intentionally absent.
 */
export interface IRedactedAttackResolvedPayload {
  readonly targetId: string;
  readonly roll: number;
  readonly toHitNumber: number;
  readonly hit: boolean;
  readonly location?: string;
  readonly damage?: number;
  readonly rolls?: readonly number[];
}

/**
 * Attack-invalid event payload — emitted when an attack attempt is
 * rejected BEFORE any damage, heat, or `AttackResolved` event fires.
 * Reasons are future-extensible; initial users are `wire-ammo-consumption`
 * (OutOfAmmo) and `wire-firing-arc-resolution` (SameHex, retrofitted).
 */
export interface IAttackInvalidPayload {
  readonly attackerId: string;
  readonly targetId: string;
  readonly weaponId?: string;
  readonly reason:
    | 'OutOfAmmo'
    | 'SameHex'
    | 'OutOfRange'
    | 'OutOfArc'
    | 'NoLineOfSight'
    | 'TargetNotVisible'
    | 'InvalidTarget'
    | 'UnknownWeapon'
    | 'WeaponDestroyed'
    | 'WeaponJammed'
    | 'AttackerEvading'
    | 'AttackerSprinted';
  readonly details?: string;
}

/**
 * Damage applied event payload.
 */
export interface IDamageAppliedPayload {
  /** Unit that took damage */
  readonly unitId: string;
  /** Location hit */
  readonly location: string;
  /** Damage amount */
  readonly damage: number;
  /** Armor remaining after damage */
  readonly armorRemaining: number;
  /** Structure remaining after damage */
  readonly structureRemaining: number;
  /** Was location destroyed? */
  readonly locationDestroyed: boolean;
  /** Critical hits triggered */
  readonly criticals?: readonly string[];
  /** Unit that dealt the damage (undefined for self-damage: ammo explosions, falling, heat, etc.) */
  readonly sourceUnitId?: string;
  /** Attack ID that caused this damage (links to AttackResolved event) */
  readonly attackId?: string;
}

/**
 * Heat event payload.
 *
 * Per `wire-heat-generation-and-effects` task 0.5.4: the `source`
 * union breaks heat generation down by cause so UI + AI consumers can
 * distinguish firing heat from engine-hit heat without parsing
 * adjacent events. `'weapons'` is kept as a legacy alias for
 * `'firing'`; `'external'` is kept for fall / crash / jump-jet
 * backfires that pre-date this change.
 */
export interface IHeatPayload {
  /** Unit */
  readonly unitId: string;
  /** Heat amount (positive for generated, negative for dissipated) */
  readonly amount: number;
  /** Heat source */
  readonly source:
    | 'movement'
    | 'firing'
    | 'weapons'
    | 'engine_hit'
    | 'environment'
    | 'dissipation'
    | 'external';
  /** New total heat */
  readonly newTotal: number;
  /**
   * Previous total heat when known. Optional because legacy event creators
   * only carried the post-event total.
   */
  readonly previousTotal?: number;
  /**
   * UI threshold transition metadata for Phase 7 heat indicators. Optional
   * so renderers can derive it from `previousTotal`/`newTotal` or fall back
   * to `newTotal` alone for old replays.
   */
  readonly previousThreshold?: HeatVisualThreshold;
  readonly currentThreshold?: HeatVisualThreshold;
  /** Whether the new heat total is in the ammo-explosion warning band. */
  readonly ammoExplosionRisk?: boolean;
  /**
   * Per `wire-heat-generation-and-effects` task 13.2: optional
   * dissipation breakdown. Populated only on `HeatDissipated` events
   * so UI / replay consumers can show "10 base + 4 water" without
   * re-reading terrain state. `baseDissipation` is the heat-sink
   * contribution (count × rating − destroyed × rating), `waterBonus`
   * is the water-cooling add per `getWaterCoolingBonus(depth)`.
   * `environmentalModifier` is the net atmosphere/temperature adjustment.
   * `heatGenerationReduction` is the per-turn generated-heat reduction
   * from abilities such as Cool Under Fire, capped by generated heat.
   */
  readonly breakdown?: {
    readonly baseDissipation: number;
    readonly waterBonus: number;
    readonly environmentalModifier?: number;
    readonly heatGenerationReduction?: number;
  };
}

/**
 * Pilot hit event payload.
 */
export interface IPilotHitPayload {
  /** Unit */
  readonly unitId: string;
  /** Wounds inflicted */
  readonly wounds: number;
  /** Total wounds */
  readonly totalWounds: number;
  /**
   * Source of the hit.
   *
   * Per `wire-heat-generation-and-effects` task 12.3: `'heat'` is
   * emitted when the heat phase applies pilot damage (heat ≥ 15 with
   * life-support damage); distinct from `'head_hit'` (head-location
   * critical) so UI / replay consumers can show the right cause.
   */
  readonly source:
    | 'head_hit'
    | 'ammo_explosion'
    | 'mech_destruction'
    | 'fall'
    | 'heat'
    | 'neural_feedback';
  /** Consciousness check required? */
  readonly consciousnessCheckRequired: boolean;
  /** Consciousness check result (if required) */
  readonly consciousnessCheckPassed?: boolean;
  /**
   * Optional trigger-specific Edge metadata. `edgeSuperseded` marks an
   * original failed roll that was replaced by a legal Edge reroll, while
   * `edgeReroll` marks the final replacement roll.
   */
  readonly edgeReroll?: boolean;
  readonly edgeSuperseded?: boolean;
  readonly edgeTrigger?: string;
  readonly edgePointsRemaining?: number;
  /**
   * Per `add-authoritative-roll-arbitration` (Wave 3a): consumed d6s for
   * the consciousness check (when required). OPTIONAL.
   */
  readonly rolls?: readonly number[];
}

/**
 * Ammo explosion event payload.
 *
 * Per `wire-heat-generation-and-effects` task 11.4: emitted when an
 * explosive ammo bin detonates. `source` distinguishes heat-induced
 * explosions (rolled during the heat phase at heat ≥ 19) from
 * crit-induced explosions (explosive component destroyed by through-
 * armor crit or damage-transfer). `damage` is the total point value
 * delivered to the bin's location (`remainingRounds × damagePerRound`
 * for heat, or the crit-caller's damage for `CritInduced`).
 */
export interface IAmmoExplosionPayload {
  /** Unit whose ammo exploded */
  readonly unitId: string;
  /** Location of the bin that exploded */
  readonly location: string;
  /** Bin id that exploded (when known) */
  readonly binId?: string;
  /** Equipment name when a non-ammo mounted component exploded. */
  readonly equipmentName?: string;
  /** Weapon type the bin fed (when known) */
  readonly weaponType?: string;
  /** Rounds destroyed in the blast */
  readonly roundsDestroyed?: number;
  /** Total explosion damage before CASE caps or local containment */
  readonly damage: number;
  /** CASE protection that modified downstream damage transfer, when known. */
  readonly caseProtection?: 'none' | 'case' | 'case_ii';
  /** Why the bin exploded */
  readonly source: 'HeatInduced' | 'CritInduced';
}

/**
 * Unit destroyed event payload.
 */
export interface IUnitDestroyedPayload {
  /** Unit that was destroyed */
  readonly unitId: string;
  /**
   * Cause of destruction.
   *
   * Closed snake_case enum unified across the three type files
   * (`GameSessionInterfaces.ts`, `CombatInterfaces.ts`, and
   * `utils/gameplay/damage/types.ts`) per the
   * `add-combat-fidelity-suite` Phase 0.5 reconciliation.
   *
   * Mutually exclusive — exactly one value per `UnitDestroyed`
   * event. Priority order when multiple conditions apply in the same
   * turn (per `damage-system` spec):
   *   `pilot_death` > `head_destroyed` > `ct_destroyed` >
   *   `engine_destroyed` > `ammo_explosion` >
   *   `impossible_displacement` > `damage`.
   *
   * Heat shutdown is a lifecycle/action-eligibility state, not a
   * destruction cause. It is reported by `ShutdownCheck`/heat lifecycle
   * events and should not be encoded as `UnitDestroyed`.
   */
  readonly cause:
    | 'damage'
    | 'ammo_explosion'
    | 'pilot_death'
    | 'engine_destroyed'
    | 'impossible_displacement'
    | 'ct_destroyed'
    | 'head_destroyed';
  /** Unit that killed this unit (undefined for self-destruction: ammo explosions, pilot death, etc.) */
  readonly killerUnitId?: string;
}

/**
 * Fog-of-war redacted destruction notice. Sent when a hidden enemy is destroyed
 * without leaking cause, damage, crit, pilot, or killer detail.
 */
export interface IRedactedUnitDestroyedPayload {
  readonly unitId: string;
}

/**
 * To-hit modifier for tracking.
 */
export interface IToHitModifier {
  /** Modifier name */
  readonly name: string;
  /** Modifier value */
  readonly value: number;
  /** Modifier source */
  readonly source: string;
  /** Optional player-facing rule detail behind the modifier */
  readonly description?: string;
}

// =============================================================================
// Phase 4: Extended Combat Event Payloads
// =============================================================================

export interface ICriticalHitResolvedPayload {
  readonly unitId: string;
  readonly location: string;
  readonly slotIndex: number;
  readonly componentType: string;
  readonly componentName: string;
  readonly weaponId?: string;
  readonly ammoBinId?: string;
  /** True when a represented weapon/equipment critical came from hot-loaded state. */
  readonly hotLoaded?: boolean;
  /** Explicit weapon id hit by a represented linked-equipment critical. */
  readonly linkedCriticalWeaponId?: string;
  /** Player-facing linked weapon name for represented linked-equipment criticals. */
  readonly linkedCriticalWeaponName?: string;
  /**
   * Total damage from a represented explosive equipment critical. Ammo-bin
   * criticals derive damage from ammo state instead.
   */
  readonly explosionDamage?: number;
  readonly effect: string;
  readonly destroyed: boolean;
  readonly missing?: boolean;
  readonly breached?: boolean;
  /** Remaining Edge points after a critical-slot Edge replacement. */
  readonly edgePointsRemaining?: number;
  /**
   * Per `add-authoritative-roll-arbitration` (Wave 3a): the server's
   * consumed d6 sequence for this crit (determination roll + slot
   * roll). OPTIONAL — see the field-level docs on
   * `IInitiativeRolledPayload`.
   */
  readonly rolls?: readonly number[];
}

export interface IPSRTriggeredPayload {
  readonly unitId: string;
  readonly reason: string;
  readonly additionalModifier: number;
  readonly triggerSource: string;
  /**
   * The unit's pilot piloting skill BEFORE per-trigger and cumulative
   * modifiers (i.e. the raw value from `IGameUnit.piloting`). Consumers
   * use this to render the full PSR target-number arithmetic
   * (`basePilotingSkill + additionalModifier + cumulative-mods = TN`)
   * without separately joining to the unit record. Optional for
   * back-compat with NDJSON event streams written before this field
   * landed.
   */
  readonly basePilotingSkill?: number;
  /**
   * Fixed system target number for PSRs that do not derive from the
   * pilot's piloting skill. Optional for back-compat with older event
   * streams and omitted for normal piloting-skill rolls.
   */
  readonly fixedTargetNumber?: number;
  /**
   * Per `structure-psr-reason-as-discriminated-code` (PR E): canonical
   * `PSRTrigger` enum value paired with the human-readable `reason`
   * string. Display consumers (`EventLogDisplay`, `format-event-log.py`)
   * keep reading `reason`; filter / aggregate consumers
   * (`EventLogQuery`, `MetricsCollector`) read `reasonCode` for
   * machine-readable filtering. OPTIONAL for back-compat with NDJSON
   * streams written before this field landed.
   */
  readonly reasonCode?: PSRTrigger;
}

export interface IPSRResolvedPayload {
  readonly unitId: string;
  readonly targetNumber: number;
  readonly roll: number;
  readonly modifiers: number;
  readonly passed: boolean;
  readonly reason: string;
  /**
   * Optional trigger-specific Edge metadata. `edgeSuperseded` marks an
   * original failed roll that was replaced by a legal Edge reroll, while
   * `edgeReroll` marks the replacement roll.
   */
  readonly edgeReroll?: boolean;
  readonly edgeSuperseded?: boolean;
  readonly edgeTrigger?: string;
  readonly edgePointsRemaining?: number;
  /**
   * Per `add-authoritative-roll-arbitration` (Wave 3a): the two d6 that
   * compose `roll`. OPTIONAL — see `IInitiativeRolledPayload.rolls`.
   */
  readonly rolls?: readonly number[];
  /**
   * Per `structure-psr-reason-as-discriminated-code` (PR E): canonical
   * `PSRTrigger` enum value paired with the human-readable `reason`
   * string. Same back-compat semantics as `IPSRTriggeredPayload.reasonCode`.
   * OPTIONAL.
   */
  readonly reasonCode?: PSRTrigger;
}

export interface IUnitFellPayload {
  readonly unitId: string;
  readonly fallDamage: number;
  readonly newFacing: Facing;
  readonly pilotDamage: number;
  /**
   * Per `add-authoritative-roll-arbitration` (Wave 3a): consumed d6s for
   * the fall direction + per-cluster hit-location rolls. OPTIONAL.
   */
  readonly rolls?: readonly number[];
  /**
   * Location at which the fall happened (e.g. `'left_leg'`, `'center_torso'`,
   * or a hex-coordinate string when the trigger was terrain). Sourced from
   * the PSR resolution context that caused the fall. Optional for
   * back-compat with NDJSON event streams written before this field
   * landed.
   */
  readonly location?: string;
  /**
   * Free-string reason describing the fall cause (e.g. `'gyro-hit'`,
   * `'took-20-damage'`). PR E (`structure-psr-reason-as-discriminated-code`)
   * keeps this string-typed for display continuity and adds the sibling
   * `reasonCode` below for machine-readable filtering. Optional for
   * back-compat.
   */
  readonly reason?: string;
  /**
   * Per `structure-psr-reason-as-discriminated-code` (PR E): canonical
   * `PSRTrigger` enum value paired with the human-readable `reason`
   * string. Same back-compat semantics as `IPSRTriggeredPayload.reasonCode`.
   * OPTIONAL.
   */
  readonly reasonCode?: PSRTrigger;
}

/**
 * Emitted when a failed source-backed movement PSR makes a unit stuck
 * instead of fallen, such as MegaMek swamp bog-down.
 */
export interface IUnitStuckPayload {
  readonly unitId: string;
  readonly reason?: string;
  readonly reasonCode?: PSRTrigger;
}

/**
 * Per `wire-piloting-skill-rolls` task 0.5.4: emitted when a prone
 * unit passes an `AttemptStand` PSR and returns to upright state.
 */
export interface IUnitStoodPayload {
  readonly unitId: string;
  readonly turn: number;
  readonly roll: number;
  readonly targetNumber: number;
  /** Reason this stand-up succeeded without rolling, when no PSR was required. */
  readonly automaticSuccessReason?: string;
  /**
   * Per `add-authoritative-roll-arbitration` (Wave 3a): the two d6 that
   * compose `roll`. OPTIONAL.
   */
  readonly rolls?: readonly number[];
}

/**
 * Per `implement-physical-attack-phase` task 2.2: physical attack event
 * types include core physical attacks plus the melee-weapon variants
 * (hatchet, sword, mace, lance, retractable blade, flail, wrecking ball).
 * The resolved payload uses the same union so club swings and charges emit
 * the same event shape.
 */
export type PhysicalAttackEventType =
  | 'punch'
  | 'kick'
  | 'charge'
  | 'dfa'
  | 'push'
  | 'trip'
  | 'thrash'
  | 'jump-jet-attack'
  | 'brush-off'
  | 'grapple'
  | 'break-grapple'
  | 'hatchet'
  | 'sword'
  | 'mace'
  | 'lance'
  | 'retractable-blade'
  | 'flail'
  | 'wrecking-ball';

export type PhysicalAttackINarcPodSelection = Pick<
  IINarcPodState,
  'teamId' | 'podType'
> &
  Partial<Pick<IINarcPodState, 'location'>>;

export interface IPhysicalDominoStepOutOptionPayload {
  readonly kind: 'forward' | 'backward';
  readonly to: IHexCoordinate;
}

export interface IPhysicalDominoStepOutContextPayload {
  readonly sideEntered: boolean;
  readonly blockerJumped: boolean;
  readonly legalStepOptions: readonly IPhysicalDominoStepOutOptionPayload[];
}

export interface IPhysicalDominoStepOutDecisionPayload {
  readonly blockerUnitId: string;
  readonly from: IHexCoordinate;
  readonly response: 'move' | 'declined' | 'failed' | 'no-response';
  readonly psrPassed: boolean;
  readonly context: IPhysicalDominoStepOutContextPayload;
  readonly path: readonly IHexCoordinate[];
}

export interface IPhysicalAttackDeclaredPayload {
  readonly attackerId: string;
  readonly targetId: string;
  readonly attackType: PhysicalAttackEventType;
  readonly toHitNumber: number;
  /**
   * Per `implement-physical-attack-phase` task 2.3: limb targeted by the
   * declaration. Required for `punch` and `kick`; may be supplied for
   * club attacks. OPTIONAL.
   */
  readonly limb?: 'leftArm' | 'rightArm' | 'leftLeg' | 'rightLeg';
  /**
   * Hit-location table selected at declaration time so replay resolves the
   * same hull-down/elevation-specific table that the command preview showed.
   */
  readonly hitTable?: 'punch' | 'kick';
  /**
   * Explicit two-handed Zweihander declaration state. The canonical
   * `zweihander` pilot ability is only consumed when this flag is true.
   */
  readonly twoHandedZweihander?: boolean;
  /**
   * Optional Brush-Off iNARC pod object selection. When present, runtime
   * removal targets the first attached pod with matching team and pod type;
   * absence preserves the legacy first-attached-pod behavior.
   */
  readonly selectedINarcPod?: PhysicalAttackINarcPodSelection;
  /**
   * Pre-resolved voluntary domino step-out/CFR branch. When omitted, declined,
   * failed, or invalid, the resolver keeps the existing forced domino fallback.
   */
  readonly blockerStepOutDecision?: IPhysicalDominoStepOutDecisionPayload;
}

export interface IPhysicalDisplacement {
  readonly unitId: string;
  readonly from: IHexCoordinate;
  readonly to: IHexCoordinate;
  readonly reason:
    | 'push'
    | 'charge'
    | 'charge_miss'
    | 'dfa'
    | 'dfa_miss'
    | 'break-grapple'
    | 'domino_step_out'
    | 'domino';
}

export interface IPhysicalAttackResolvedPayload {
  readonly attackerId: string;
  readonly targetId: string;
  readonly attackType: PhysicalAttackEventType;
  readonly roll: number;
  readonly toHitNumber: number;
  readonly hit: boolean;
  readonly damage?: number;
  readonly location?: string;
  /**
   * Per `implement-physical-attack-phase` tasks 6.4 / 7.4: per-cluster
   * (damage, location) pairs for charge and DFA, where the total damage
   * is split into 5-point clusters and each cluster rolls a fresh
   * hit-location. OPTIONAL — omitted for single-cluster attacks.
   */
  readonly clusters?: readonly {
    readonly damage: number;
    readonly location: string;
  }[];
  /**
   * Source-backed physical displacement results. Push, charge, and DFA move
   * the target and then the attacker follows into the target's original hex
   * when the destination is legal.
   */
  readonly displacements?: readonly IPhysicalDisplacement[];
  readonly automaticHit?: boolean;
  readonly automaticHitReason?: string;
  readonly selectedINarcPod?: PhysicalAttackINarcPodSelection;
  /**
   * Per `add-authoritative-roll-arbitration` (Wave 3a): consumed d6s for
   * the to-hit + hit-location rolls (location omitted on miss). OPTIONAL.
   */
  readonly rolls?: readonly number[];
}
