/**
 * Tactical Movement Intent Interfaces
 *
 * Type surface for the intent-first movement flow (change
 * `tactical-movement-intent-composer`, design D5). The player composes a
 * movement turn as Intent Items — zero or more Posture Actions plus at most
 * one waypointed Locomotion Path — a Cost Ledger totals it live, Live
 * Intersection blocks unaffordable intent at the source, and the movement
 * mode is chosen last via an explicit Lock-In.
 *
 * Naming note: design D5 names the mode field's type `MovementMode`. No such
 * enum exists in the codebase — the canonical enum is `MovementType`
 * (walk/run/jump/…). We use `MovementType` here so budget options and the
 * committed declaration stay on the single existing movement-type authority.
 * Costs and rules come from `movement-system` code paths; there is NO
 * UI-local MP math in this module.
 *
 * @spec openspec/changes/tactical-movement-intent-composer/specs/tactical-movement-intent/spec.md
 */

import type { Facing, IHexCoordinate, MovementType } from './HexGridInterfaces';

/**
 * The Posture Actions a unit may compose before locomotion. Costs derive from
 * `movement-system` (stand-up / careful-stand / hull-down entry / go-prone),
 * never from a UI-local formula. `EVADE` is a posture with no destination and
 * no path MP (the run/evade budget is what the resolver charges) per ADR 0001 /
 * the composer design's Open Questions resolution.
 */
export type PostureActionType =
  | 'STAND_UP'
  | 'CAREFUL_STAND'
  | 'GO_PRONE'
  | 'HULL_DOWN'
  | 'EVADE';

/**
 * A player-placed anchor on the Locomotion Path. The MP charged for the
 * facing change at this waypoint (a Pivot Point) derives from `facingChange`
 * via `movement-system` turning costs.
 */
export interface IWaypoint {
  /** Axial hex the waypoint sits on. */
  readonly hex: IHexCoordinate;
  /**
   * Facing change applied at this waypoint (hexsides turned); the pivot MP
   * cost derives from it per `movement-system`.
   */
  readonly facingChange: number;
}

/**
 * One auto-routed leg between two consecutive Locomotion Path anchors. The
 * `path` is the pathfinder's cheapest hex sequence between the anchors
 * (inclusive of `to`); `mpCost` is terrain-adjusted per `movement-system`.
 */
export interface ILocomotionLeg {
  readonly from: IWaypoint;
  readonly to: IWaypoint;
  /** A*-routed hex sequence between the anchors (inclusive of `to`). */
  readonly path: readonly IHexCoordinate[];
  /** Terrain-adjusted MP for the leg, per movement-system. */
  readonly mpCost: number;
}

/**
 * A composed Intent Item. A `posture` item carries a single Posture Action
 * and its rules-derived MP cost; a `locomotion` item carries the ordered legs
 * of the Locomotion Path plus the final facing picked at the last waypoint.
 */
export type IIntentItem =
  | {
      readonly kind: 'posture';
      readonly action: PostureActionType;
      readonly mpCost: number;
    }
  | {
      readonly kind: 'locomotion';
      readonly legs: readonly ILocomotionLeg[];
      readonly finalFacing: Facing;
    };

/**
 * A candidate Movement Budget presented by Live Intersection / the Budget
 * Resolver. `budgetMp` is the damage/heat-adjusted MP for the mode (from
 * `movement-system` hooks); `affordable` is `ledgerTotal <= budgetMp`;
 * `heatGenerated` and `attackerToHitModifier` are the resolver consequence
 * lines, also sourced from `movement-system`.
 */
export interface IBudgetOption {
  /** WALK | RUN | JUMP (existing `MovementType` enum). */
  readonly mode: MovementType;
  /** Damage/heat-adjusted MP budget for the mode. */
  readonly budgetMp: number;
  /** `true` when this budget affords the composed ledger total. */
  readonly affordable: boolean;
  /** Heat generated by committing at this mode, per movement-system. */
  readonly heatGenerated: number;
  /** Attacker to-hit modifier incurred by moving at this mode. */
  readonly attackerToHitModifier: number;
}

/**
 * The stored movement-intent slice. Only `items` and `lockedMode` are stored;
 * `ledgerTotalMp` and `budgetOptions` are DERIVED via selectors from `items`
 * plus the live unit state (design D5: derived values are selectors, not
 * stored — single source of truth is `items` + unit state).
 */
export interface IMovementIntentState {
  /** The composed Intent Items in composition order. */
  readonly items: readonly IIntentItem[];
  /** The mode committed at Lock-In; `null` until the player locks in. */
  readonly lockedMode: MovementType | null;
}
