import type { AerospaceState } from '@/stores/aerospaceState';
import type { BattleArmorState } from '@/stores/battleArmorState';
import type { ProtoMechState } from '@/stores/protoMechState';
import type { VehicleState } from '@/stores/vehicleState';

import { aerospaceLocationToBlockName } from './BlkExportServiceCore.formatters';

export function tag(name: string, value: string): string {
  return `<${name}>\n${value}\n</${name}>`;
}

export function writeLicenseHeader(lines: string[]): void {
  lines.push(
    '#MegaMek Data (C) 2025 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.',
  );
  lines.push(
    '#To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/',
  );
  lines.push('#');
  lines.push('#Generated by MekStation');
  lines.push('');
}

export function writeVehicleEquipment(
  lines: string[],
  unit: VehicleState,
): void {
  const locationMap: Record<string, string[]> = {};

  for (const eq of unit.equipment) {
    const loc = eq.isTurretMounted ? 'Turret' : eq.location;
    if (!locationMap[loc]) {
      locationMap[loc] = [];
    }
    locationMap[loc].push(eq.name);
  }

  const locationOrder = ['Front', 'Left', 'Right', 'Rear', 'Turret', 'Body'];
  for (const loc of locationOrder) {
    const items = locationMap[loc];
    if (items && items.length > 0) {
      lines.push(tag(`${loc} Equipment`, items.join('\n')));
      lines.push('');
    }
  }
}

export function writeAerospaceEquipment(
  lines: string[],
  unit: AerospaceState,
): void {
  const locationMap: Record<string, string[]> = {};

  for (const eq of unit.equipment) {
    const loc = aerospaceLocationToBlockName(eq.location);
    if (!locationMap[loc]) {
      locationMap[loc] = [];
    }
    locationMap[loc].push(eq.name);
  }

  const arcOrder = ['Nose', 'Left Wing', 'Right Wing', 'Aft'];
  for (const arc of arcOrder) {
    const items = locationMap[arc];
    if (items && items.length > 0) {
      lines.push(tag(`${arc} Equipment`, items.join('\n')));
      lines.push('');
    }
  }
}

export function writeBattleArmorEquipment(
  lines: string[],
  unit: BattleArmorState,
): void {
  if (unit.equipment && unit.equipment.length > 0) {
    const items = unit.equipment.map((eq) => eq.name);
    lines.push(tag('Squad Equipment', items.join('\n')));
    lines.push('');
  }
}

export function writeProtoMechEquipment(
  lines: string[],
  unit: ProtoMechState,
): void {
  const locationMap: Record<string, string[]> = {};

  for (const eq of unit.equipment) {
    const loc = eq.location || 'Torso';
    if (!locationMap[loc]) {
      locationMap[loc] = [];
    }
    locationMap[loc].push(eq.name);
  }

  const locationOrder = [
    'Head',
    'Torso',
    'Main Gun',
    'Left Arm',
    'Right Arm',
    'Legs',
  ];
  for (const loc of locationOrder) {
    const items = locationMap[loc];
    if (items && items.length > 0) {
      lines.push(tag(`${loc} Equipment`, items.join('\n')));
      lines.push('');
    }
  }
}
