/**
 * Campaign Contract Market Page
 *
 * The Contract Market command surface (CP2b — `add-campaign-command-ui`,
 * design D5). Lists the current contract-market offers with accept /
 * decline actions. Accept routes through the existing `mission-contracts`
 * acceptance logic via `campaignCommandActions`; decline hides the offer
 * until the next market refresh.
 *
 * The market pool is generated by `contractMarketProcessor` in the day
 * pipeline; a campaign with no market this cycle has none, so this page
 * seeds one on first open using the same `generateAtBContracts` engine —
 * the page never invents contract logic, only surfaces it.
 *
 * @spec openspec/changes/add-campaign-command-ui/specs/campaign-command-ui/spec.md
 */

import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';

import type { ICampaign } from '@/types/campaign/Campaign';
import type { ICampaignWithCommand } from '@/types/campaign/CampaignCommandExtensions';

import { CampaignNavigation } from '@/components/campaign/CampaignNavigation';
import {
  CommandError,
  CommandLoading,
} from '@/components/campaign/command/CommandStates';
import { ContractMarketPanel } from '@/components/campaign/command/ContractMarketPanel';
import { CampaignCoopRouteSurface } from '@/components/campaign/coop';
import { EmptyState, PageLayout } from '@/components/ui';
import { generateAtBContracts } from '@/lib/campaign/contractMarket';
import {
  acceptContractOffer,
  declineContractOffer,
} from '@/stores/campaign/campaignCommandActions';
import { selectVisibleContractOffers } from '@/stores/campaign/campaignCommandSelectors';
import { useCampaignPersistenceStore } from '@/stores/campaign/useCampaignPersistenceStore';
import { useCampaignStore } from '@/stores/campaign/useCampaignStore';

export default function ContractMarketPage(): React.ReactElement {
  const router = useRouter();
  const { id } = router.query;
  const store = useCampaignStore();
  const campaign = store.getState().getCampaign();
  const saveState = useCampaignPersistenceStore((state) => state.saveState);
  const loadCampaign = useCampaignPersistenceStore(
    (state) => state.loadCampaign,
  );
  const [isClient, setIsClient] = useState(false);
  // Re-render tick — bumped after an action so the page re-reads the market.
  const [, setActionTick] = useState(0);
  const [busyOfferId, setBusyOfferId] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);

  useEffect(() => {
    setIsClient(true);
  }, []);

  // Seed the contract market on first open when the campaign has no
  // market state yet. Uses the existing AtB contract engine — no new
  // generation logic.
  useEffect(() => {
    if (!isClient || !campaign) return;
    const extended = campaign as ICampaignWithCommand;
    if (extended.contractMarket !== undefined) return;
    const offers = generateAtBContracts(campaign);
    store.getState().updateCampaign({
      contractMarket: { offers, declinedOfferIds: [] },
    } as Partial<ICampaign>);
    setActionTick((tick) => tick + 1);
  }, [isClient, campaign, store]);

  const breadcrumbs = [
    { label: 'Home', href: '/' },
    { label: 'Gameplay', href: '/gameplay' },
    { label: 'Campaigns', href: '/gameplay/campaigns' },
    { label: campaign?.name || 'Campaign', href: `/gameplay/campaigns/${id}` },
    { label: 'Contract Market' },
  ];

  if (!isClient) {
    return (
      <PageLayout
        title="Contract Market"
        subtitle="Loading contract market..."
        maxWidth="wide"
      >
        <CommandLoading />
      </PageLayout>
    );
  }

  if (!campaign) {
    return (
      <PageLayout
        title="Contract Market"
        subtitle="Campaign not found"
        maxWidth="wide"
        breadcrumbs={breadcrumbs}
      >
        <EmptyState
          title="Campaign not found"
          message="Return to campaigns list to select a campaign."
        />
      </PageLayout>
    );
  }

  const offers = selectVisibleContractOffers(campaign);

  /** Accept a contract through the existing mission-contracts logic. */
  const handleAccept = (offerId: string): void => {
    setActionError(null);
    setBusyOfferId(offerId);
    const result = acceptContractOffer(offerId);
    setBusyOfferId(null);
    if (!result.applied) {
      setActionError(result.reason ?? 'The contract is no longer available.');
      return;
    }
    setActionTick((tick) => tick + 1);
  };

  /** Decline a contract — hides it until the next market refresh. */
  const handleDecline = (offerId: string): void => {
    setActionError(null);
    setBusyOfferId(offerId);
    declineContractOffer(offerId);
    setBusyOfferId(null);
    setActionTick((tick) => tick + 1);
  };

  return (
    <PageLayout
      title="Contract Market"
      subtitle={`${campaign.name} — ${offers.length} contracts on offer`}
      maxWidth="wide"
      breadcrumbs={breadcrumbs}
    >
      <CampaignNavigation
        campaignId={campaign.id}
        currentPage="contract-market"
        coopSession={campaign.coopSession}
      />

      <CampaignCoopRouteSurface campaign={campaign} routeId="contract-market" />
      {actionError ? (
        <CommandError
          message={actionError}
          onRetry={() => setActionError(null)}
        />
      ) : saveState === 'error' ? (
        <CommandError
          message="The campaign command data failed to load."
          onRetry={() => {
            void loadCampaign(campaign.id);
          }}
        />
      ) : (
        <ContractMarketPanel
          offers={offers}
          onAccept={handleAccept}
          onDecline={handleDecline}
          busyOfferId={busyOfferId}
        />
      )}
    </PageLayout>
  );
}
