/**
 * Campaign Personnel & Hiring Page
 *
 * The Personnel & Hiring command surface (CP2b — `add-campaign-command-ui`,
 * design D2). Lists the current personnel-market candidate pool with a
 * per-candidate hire action routing through the existing
 * `personnel-management` hiring logic via `campaignCommandActions`.
 *
 * The market pool is generated by `personnelMarketProcessor` in the day
 * pipeline; a campaign that has never advanced a day yet has no pool, so
 * this page seeds one on first open using the same `generatePersonnelForDay`
 * engine — the page never invents hiring logic, only surfaces it.
 *
 * @spec openspec/changes/add-campaign-command-ui/specs/campaign-command-ui/spec.md
 */

import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';

import type { ICampaign } from '@/types/campaign/Campaign';
import type { ICampaignWithCommand } from '@/types/campaign/CampaignCommandExtensions';

import { CampaignNavigation } from '@/components/campaign/CampaignNavigation';
import {
  CommandError,
  CommandLoading,
} from '@/components/campaign/command/CommandStates';
import { HiringPanel } from '@/components/campaign/command/HiringPanel';
import { CampaignCoopRouteSurface } from '@/components/campaign/coop';
import { EmptyState, PageLayout } from '@/components/ui';
import { generatePersonnelForDay } from '@/lib/campaign/markets/personnelMarket';
import { hireCandidate } from '@/stores/campaign/campaignCommandActions';
import { selectPersonnelMarket } from '@/stores/campaign/campaignCommandSelectors';
import { useCampaignPersistenceStore } from '@/stores/campaign/useCampaignPersistenceStore';
import { useCampaignStore } from '@/stores/campaign/useCampaignStore';

export default function HiringPage(): React.ReactElement {
  const router = useRouter();
  const { id } = router.query;
  const store = useCampaignStore();
  const campaign = store.getState().getCampaign();
  const saveState = useCampaignPersistenceStore((state) => state.saveState);
  const loadCampaign = useCampaignPersistenceStore(
    (state) => state.loadCampaign,
  );
  const [isClient, setIsClient] = useState(false);
  // Re-render tick — bumped after a hire so the page re-reads the market.
  const [, setActionTick] = useState(0);
  // Offer id of a hire in flight, and any action error.
  const [hiringOfferId, setHiringOfferId] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);

  useEffect(() => {
    setIsClient(true);
  }, []);

  // Seed the personnel market on first open when the campaign has no
  // pool yet (a fresh campaign that has not advanced a day). Uses the
  // existing market engine — no new generation logic.
  useEffect(() => {
    if (!isClient || !campaign) return;
    const extended = campaign as ICampaignWithCommand;
    if (extended.personnelMarket !== undefined) return;
    const offers = generatePersonnelForDay(campaign, Math.random);
    store
      .getState()
      .updateCampaign({ personnelMarket: offers } as Partial<ICampaign>);
    setActionTick((tick) => tick + 1);
  }, [isClient, campaign, store]);

  const breadcrumbs = [
    { label: 'Home', href: '/' },
    { label: 'Gameplay', href: '/gameplay' },
    { label: 'Campaigns', href: '/gameplay/campaigns' },
    { label: campaign?.name || 'Campaign', href: `/gameplay/campaigns/${id}` },
    { label: 'Personnel & Hiring' },
  ];

  if (!isClient) {
    return (
      <PageLayout
        title="Personnel & Hiring"
        subtitle="Loading hiring market..."
        maxWidth="wide"
      >
        <CommandLoading />
      </PageLayout>
    );
  }

  if (!campaign) {
    return (
      <PageLayout
        title="Personnel & Hiring"
        subtitle="Campaign not found"
        maxWidth="wide"
        breadcrumbs={breadcrumbs}
      >
        <EmptyState
          title="Campaign not found"
          message="Return to campaigns list to select a campaign."
        />
      </PageLayout>
    );
  }

  const candidates = selectPersonnelMarket(campaign);

  /** Hire a candidate through the existing personnel-management logic. */
  const handleHire = (offerId: string): void => {
    setActionError(null);
    setHiringOfferId(offerId);
    const result = hireCandidate(offerId);
    setHiringOfferId(null);
    if (!result.applied) {
      setActionError(result.reason ?? 'The candidate is no longer available.');
      return;
    }
    setActionTick((tick) => tick + 1);
  };

  return (
    <PageLayout
      title="Personnel & Hiring"
      subtitle={`${campaign.name} — ${candidates.length} candidates on the market`}
      maxWidth="wide"
      breadcrumbs={breadcrumbs}
    >
      <CampaignNavigation
        campaignId={campaign.id}
        currentPage="hiring"
        coopSession={campaign.coopSession}
      />

      <CampaignCoopRouteSurface campaign={campaign} routeId="hiring" />

      {actionError ? (
        <CommandError
          message={actionError}
          onRetry={() => setActionError(null)}
        />
      ) : saveState === 'error' ? (
        <CommandError
          message="The campaign command data failed to load."
          onRetry={() => {
            void loadCampaign(campaign.id);
          }}
        />
      ) : (
        <HiringPanel
          candidates={candidates}
          onHire={handleHire}
          hiringOfferId={hiringOfferId}
        />
      )}
    </PageLayout>
  );
}
