/**
 * Campaign Personnel & Hiring Page
 *
 * The Personnel & Hiring command surface (CP2b — `add-campaign-command-ui`,
 * design D2). Lists the current personnel-market candidate pool with a
 * per-candidate hire action routing through the existing
 * `personnel-management` hiring logic via `campaignCommandActions`.
 *
 * The market pool is generated by `personnelMarketProcessor` in the day
 * pipeline; a campaign that has never advanced a day yet has no pool, so
 * this page seeds one on first open using the same `generatePersonnelForDay`
 * engine — the page never invents hiring logic, only surfaces it.
 *
 * @spec openspec/changes/add-campaign-command-ui/specs/campaign-command-ui/spec.md
 */

import React, { useEffect, useState } from 'react';

import type { ICampaign } from '@/types/campaign/Campaign';
import type { ICampaignWithCommand } from '@/types/campaign/CampaignCommandExtensions';

import { HiringPanel } from '@/components/campaign/command/HiringPanel';
import { generatePersonnelForDay } from '@/lib/campaign/markets/personnelMarket';
import {
  CampaignPageFrameFromShell,
  getLoadedCampaign,
  renderCampaignCommandFeedback,
  renderPendingCampaignPage,
  useCampaignLoadStatus,
  useCampaignPageShell,
} from '@/pages-modules/gameplay/campaigns/campaignPageShell';
import { hireCandidate } from '@/stores/campaign/campaignCommandActions';
import { selectPersonnelMarket } from '@/stores/campaign/campaignCommandSelectors';

const HIRING_LOADING = {
  title: 'Personnel & Hiring',
  subtitle: 'Loading hiring market...',
} as const;

export default function HiringPage(): React.ReactElement {
  const shell = useCampaignPageShell('Personnel & Hiring');
  const { campaign: shellCampaign, store, isClient } = shell;
  const loadStatus = useCampaignLoadStatus();
  // Re-render tick — bumped after a hire so the page re-reads the market.
  const [, setActionTick] = useState(0);
  // Offer id of a hire in flight, and any action error.
  const [hiringOfferId, setHiringOfferId] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);

  // Seed the personnel market on first open when the campaign has no
  // pool yet (a fresh campaign that has not advanced a day). Uses the
  // existing market engine — no new generation logic.
  useEffect(() => {
    if (!isClient || !shellCampaign) return;
    const extended = shellCampaign as ICampaignWithCommand;
    if (extended.personnelMarket !== undefined) return;
    const offers = generatePersonnelForDay(shellCampaign, Math.random);
    store
      .getState()
      .updateCampaign({ personnelMarket: offers } as Partial<ICampaign>);
    setActionTick((tick) => tick + 1);
  }, [isClient, shellCampaign, store]);

  const pendingPage = renderPendingCampaignPage(shell, HIRING_LOADING);
  if (pendingPage) return pendingPage;

  const campaign = getLoadedCampaign(shell);
  const candidates = selectPersonnelMarket(campaign);
  const frame = {
    title: 'Personnel & Hiring',
    subtitle: `${campaign.name} — ${candidates.length} candidates on the market`,
    currentPage: 'hiring',
    coopRouteId: 'hiring',
  } as const;

  /** Hire a candidate through the existing personnel-management logic. */
  const handleHire = (offerId: string): void => {
    setActionError(null);
    setHiringOfferId(offerId);
    const result = hireCandidate(offerId);
    setHiringOfferId(null);
    if (!result.applied) {
      setActionError(result.reason ?? 'The candidate is no longer available.');
      return;
    }
    setActionTick((tick) => tick + 1);
  };

  const feedback = renderCampaignCommandFeedback({
    actionError,
    campaignId: campaign.id,
    loadStatus,
    onClearActionError: () => setActionError(null),
  });

  return (
    <CampaignPageFrameFromShell shell={shell} frame={frame}>
      {feedback ?? (
        <HiringPanel
          candidates={candidates}
          onHire={handleHire}
          hiringOfferId={hiringOfferId}
        />
      )}
    </CampaignPageFrameFromShell>
  );
}
