/**
 * BV Catalog Prewarmer
 *
 * The on-disk BattleMech catalog (`public/data/units/battlemechs/index.json`
 * and the unit JSONs it points at) does NOT store a precomputed Battle Value
 * field — BV is computed at runtime. The Phase 4 `randomForceGenerator`
 * reads `entry.bv ?? 0` while filtering / picking units, so without
 * prewarming every entry shows up as BV=0 and the force generator throws
 * `BudgetUnsatisfiableError`.
 *
 * Two-tier BV source strategy
 * ---------------------------
 * Tier 1 — `validation-output/bv-validation-report.json` (preferred):
 *   The repo ships an authoritative BV report generated by
 *   `scripts/validate-bv.ts`. It covers 4196/4225 catalog units at >99.8%
 *   parity with MUL data. We read this once and key BV by `unitId`.
 *
 * Tier 2 — `calculateUnitBV()` from `src/utils/construction/bvAdapter`:
 *   Used only as a fallback for units the report does not cover. The
 *   construction-side adapter is a reduced-scope calculator and returns
 *   0 for many unit shapes (Tripods, ProtoMechs, vehicles), but that's
 *   acceptable here — entries with BV=0 are filtered out as ineligible
 *   by `randomForceGenerator`'s budget sanity check, leaving the 4196
 *   "good" units selectable.
 *
 * Caching
 * -------
 * Reading the BV report and stamping every catalog entry is cheap (single
 * disk read of one JSON file plus an O(N) merge), but we still write a
 * derived cache to `.cache/swarm-bv-cache.json` keyed on catalog version
 * + total units so that subsequent CLI runs skip the merge entirely.
 *
 * The cache file is intentionally outside `public/` so that:
 *   - It does not ship with the Next.js app bundle
 *   - It does not pollute the catalog source-of-truth
 *   - It is safe to gitignore (covered by `.cache/` in .gitignore)
 *
 * @see openspec/changes/archive/2026-05-06-add-encounter-swarm-harness/design.md D2
 * @see scripts/validate-bv.ts (Tier 1 source generator)
 * @see src/services/encounter/randomForceGenerator.ts (consumer)
 */

import * as fs from 'fs';
import * as path from 'path';

import type { IUnitIndexEntry } from '../../types/unit/UnitIndex';
import type { ICanonicalUnitService } from '../units/CanonicalUnitService';

import { calculateUnitBV, UnitData } from '../../utils/construction/bvAdapter';

// =============================================================================
// Disk cache shape
// =============================================================================

interface BVCacheFile {
  /** Version stamp from the catalog index (so we invalidate on regen). */
  readonly catalogVersion: string;
  /** Unit count from the catalog index (additional invalidation guard). */
  readonly catalogTotalUnits: number;
  /** Map of unit id → computed BV. */
  readonly bvByUnitId: Record<string, number>;
  /** ISO timestamp of when this cache was written, for debugging. */
  readonly generatedAt: string;
}

// =============================================================================
// BV report shape (Tier 1 source)
// =============================================================================

/**
 * Subset of `validation-output/bv-validation-report.json` we depend on.
 * The full file has many more fields but we only need unitId + calculatedBV.
 */
interface BVReportEntry {
  readonly unitId: string;
  readonly calculatedBV: number | null;
}

interface BVReportFile {
  readonly allResults: readonly BVReportEntry[];
}

// =============================================================================
// Public API
// =============================================================================

export interface PrewarmOptions {
  /** Override the cache file path (mainly for testing). */
  readonly cacheFilePath?: string;
  /** Override the BV report path (mainly for testing). */
  readonly bvReportPath?: string;
  /** Disable disk caching entirely. Useful for tests or stale-cache debugging. */
  readonly skipCache?: boolean;
  /** Progress callback fired every `progressEveryN` units processed. */
  readonly onProgress?: (processed: number, total: number) => void;
  /** Progress reporting cadence. Default 500. */
  readonly progressEveryN?: number;
}

export interface PrewarmResult {
  /** The original catalog enriched with `bv` populated where computable. */
  readonly catalog: IUnitIndexEntry[];
  /** Number of entries that received a positive BV. */
  readonly populated: number;
  /** Number of entries whose BV calc returned 0 (skipped or failed). */
  readonly skipped: number;
  /** True when the result came from the on-disk cache. */
  readonly fromCache: boolean;
  /** Source attribution for telemetry: 'cache' | 'report' | 'fallback' | 'mixed'. */
  readonly source: 'cache' | 'report' | 'fallback' | 'mixed';
}

interface PrewarmPaths {
  readonly cacheFilePath: string;
  readonly bvReportPath: string;
}

interface BVReportLookup {
  readonly bvByUnitId: Record<string, number>;
  readonly reportHits: number;
}

/**
 * Enrich the catalog index with computed BV values.
 *
 * Resolution order:
 *   1. Disk cache hit (matches catalog version + total units) → return as-is.
 *   2. Read `validation-output/bv-validation-report.json` and stamp BV
 *      from `calculatedBV` per `unitId`.
 *   3. For any catalog entries the report did not cover, fall back to
 *      `calculateUnitBV` via the catalog service. This branch is best-effort
 *      and entries that still resolve to 0 are returned with bv: 0
 *      (they will be filtered out by `randomForceGenerator`).
 *
 * The result is persisted to the disk cache for the next run.
 *
 * @param catalog - The raw index entries from `ICanonicalUnitService.getIndex()`.
 *                  Mutated copies are returned, never the input array.
 * @param catalogService - Service used to load each unit's full JSON for the
 *                         fallback path. Not called when the report covers
 *                         every entry.
 * @param catalogVersion - Version stamp from the index file (for cache key).
 * @param options - Optional cache + progress overrides.
 */
export async function prewarmCatalogBV(
  catalog: readonly IUnitIndexEntry[],
  catalogService: ICanonicalUnitService,
  catalogVersion: string,
  options: PrewarmOptions = {},
): Promise<PrewarmResult> {
  const { cacheFilePath, bvReportPath } = resolvePrewarmPaths(options);

  // -- Try disk cache first --------------------------------------------------
  if (!options.skipCache) {
    const cached = buildCachedPrewarmResult(
      catalog,
      catalogVersion,
      cacheFilePath,
    );
    if (cached !== null) return cached;
  }

  // -- Tier 1: read the BV validation report --------------------------------
  const { bvByUnitId, reportHits } = buildBVReportLookup(bvReportPath);

  // -- Tier 2: fallback for catalog entries the report missed ---------------
  const progressEveryN = options.progressEveryN ?? 500;
  const enriched: IUnitIndexEntry[] = [];
  let populated = 0;
  let skipped = 0;
  let fallbackHits = 0;

  for (let i = 0; i < catalog.length; i++) {
    const entry = catalog[i];
    let bv = bvByUnitId[entry.id] ?? 0;

    if (bv === 0) {
      // Tier 2 fallback — only invoked for entries the report did not cover.
      const fallbackBV = await computeBVForEntry(entry.id, catalogService);
      if (fallbackBV > 0) {
        bv = fallbackBV;
        bvByUnitId[entry.id] = bv;
        fallbackHits++;
      }
    }

    enriched.push({ ...entry, bv });

    if (bv > 0) {
      populated++;
    } else {
      skipped++;
    }

    if (
      options.onProgress &&
      ((i + 1) % progressEveryN === 0 || i === catalog.length - 1)
    ) {
      options.onProgress(i + 1, catalog.length);
    }
  }

  // -- Persist cache --------------------------------------------------------
  if (!options.skipCache) {
    tryWriteCache(cacheFilePath, {
      catalogVersion,
      catalogTotalUnits: catalog.length,
      bvByUnitId,
      generatedAt: new Date().toISOString(),
    });
  }

  return {
    catalog: enriched,
    populated,
    skipped,
    fromCache: false,
    source: getPrewarmSource(reportHits, fallbackHits),
  };
}

// =============================================================================
// Internals
// =============================================================================

function resolvePrewarmPaths(options: PrewarmOptions): PrewarmPaths {
  return {
    cacheFilePath:
      options.cacheFilePath ??
      path.resolve(process.cwd(), '.cache/swarm-bv-cache.json'),
    bvReportPath:
      options.bvReportPath ??
      path.resolve(
        process.cwd(),
        'validation-output/bv-validation-report.json',
      ),
  };
}

function buildCachedPrewarmResult(
  catalog: readonly IUnitIndexEntry[],
  catalogVersion: string,
  cacheFilePath: string,
): PrewarmResult | null {
  const cached = tryReadCache(cacheFilePath, catalogVersion, catalog.length);
  if (cached === null) return null;

  const enriched = catalog.map(
    (entry): IUnitIndexEntry => ({
      ...entry,
      bv: cached.bvByUnitId[entry.id] ?? entry.bv ?? 0,
    }),
  );
  const populated = enriched.filter((e) => (e.bv ?? 0) > 0).length;
  return {
    catalog: enriched,
    populated,
    skipped: enriched.length - populated,
    fromCache: true,
    source: 'cache',
  };
}

function buildBVReportLookup(bvReportPath: string): BVReportLookup {
  const bvByUnitId: Record<string, number> = {};
  const report = tryReadBVReport(bvReportPath);
  if (report === null) {
    return { bvByUnitId, reportHits: 0 };
  }

  let reportHits = 0;
  for (const entry of report.allResults) {
    if (entry.calculatedBV !== null && entry.calculatedBV > 0) {
      bvByUnitId[entry.unitId] = entry.calculatedBV;
      reportHits++;
    }
  }
  return { bvByUnitId, reportHits };
}

function getPrewarmSource(
  reportHits: number,
  fallbackHits: number,
): PrewarmResult['source'] {
  if (reportHits > 0 && fallbackHits > 0) return 'mixed';
  if (reportHits > 0) return 'report';
  return 'fallback';
}

/**
 * Compute BV for a single catalog entry. Returns 0 on any failure path so
 * the caller can keep iterating through the rest of the catalog.
 *
 * Uses the construction-side `calculateUnitBV` which works for many but not
 * all unit shapes — fine here as the Tier 1 report covers the common cases.
 */
async function computeBVForEntry(
  unitId: string,
  catalogService: ICanonicalUnitService,
): Promise<number> {
  try {
    const fullUnit = await catalogService.getById(unitId);
    if (fullUnit === null) {
      return 0;
    }
    // The IFullUnit shape and UnitData shape overlap on every field
    // calculateUnitBV reads; keep this adapter boundary explicit until the
    // construction-side BV input shape is split from raw unit persistence.
    return calculateUnitBV(fullUnit as Partial<UnitData> as UnitData);
  } catch {
    return 0;
  }
}

/**
 * Read the BV validation report. Returns null on any miss (file missing,
 * parse error, schema mismatch) so the caller can fall back to per-entry
 * computation.
 */
function tryReadBVReport(reportPath: string): BVReportFile | null {
  try {
    if (!fs.existsSync(reportPath)) {
      return null;
    }
    const raw = fs.readFileSync(reportPath, 'utf-8');
    const parsed = JSON.parse(raw) as BVReportFile;
    if (!Array.isArray(parsed.allResults)) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Read the cache file if present and matching the requested catalog version.
 * Returns null on any miss (file missing, parse error, version mismatch,
 * unit-count mismatch) so the caller knows to rebuild from scratch.
 */
function tryReadCache(
  cacheFilePath: string,
  expectedVersion: string,
  expectedTotalUnits: number,
): BVCacheFile | null {
  try {
    if (!fs.existsSync(cacheFilePath)) {
      return null;
    }
    const raw = fs.readFileSync(cacheFilePath, 'utf-8');
    const parsed = JSON.parse(raw) as BVCacheFile;
    if (parsed.catalogVersion !== expectedVersion) {
      return null;
    }
    if (parsed.catalogTotalUnits !== expectedTotalUnits) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Write the cache file. Errors are logged but not thrown — a failed write
 * just means the next run will rebuild, which is annoying but not fatal.
 */
function tryWriteCache(cacheFilePath: string, cache: BVCacheFile): void {
  try {
    const dir = path.dirname(cacheFilePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(cacheFilePath, JSON.stringify(cache, null, 2), 'utf-8');
  } catch (err) {
    // Log to stderr so CLI users see the warning but don't break the run.
    // eslint-disable-next-line no-console
    console.warn(
      `[bvCatalogPrewarmer] Failed to write cache to ${cacheFilePath}:`,
      err,
    );
  }
}
