import './tactical-map.combat-scenarios.01-range-and-c3.cases';
import './tactical-map.combat-scenarios.02-indirect-fire.cases';
import './tactical-map.combat-scenarios.03-environment-and-posture.cases';
import './tactical-map.combat-scenarios.04-movement-modifiers.cases';
import './tactical-map.combat-scenarios.05-los-and-cover.cases';
import './tactical-map.combat-scenarios.06-aerospace-and-visibility.cases';
import './tactical-map.combat-scenarios.07-arcs.cases';
import './tactical-map.combat-scenarios.08-turrets-and-same-hex.cases';
import './tactical-map.combat-scenarios.09-range-rejections.cases';
