/**
 * Unit Info Banner Component
 * 
 * At-a-glance unit statistics display with "current / max" format
 * for capacity-based stats like MegaMekLab's status bar.
 * 
 * @spec openspec/specs/unit-info-banner/spec.md
 */

import React from 'react';
import { TechBaseBadge } from './TechBaseBadge';
import { ValidationBadge } from './ValidationBadge';
import { TechBaseMode } from '@/types/construction/TechBaseConfiguration';
import { ValidationStatus } from '@/utils/colors/statusColors';

// =============================================================================
// Types
// =============================================================================

export interface UnitStats {
  /** Unit name/variant */
  name: string;
  /** Tonnage (max weight) */
  tonnage: number;
  /** Tech base mode (IS/Clan/Mixed) */
  techBaseMode: TechBaseMode;
  /** Engine rating */
  engineRating: number;
  /** Walk MP */
  walkMP: number;
  /** Run MP */
  runMP: number;
  /** Jump MP */
  jumpMP: number;
  /** Max Run MP with enhancement active (MASC/TSM/Supercharger) */
  maxRunMP?: number;
  /** Current weight used */
  weightUsed: number;
  /** Remaining weight (calculated: tonnage - weightUsed) */
  weightRemaining: number;
  /** Total armor points allocated */
  armorPoints: number;
  /** Maximum armor points possible */
  maxArmorPoints: number;
  /** Critical slots currently used */
  criticalSlotsUsed: number;
  /** Total critical slots available (78 for standard mech) */
  criticalSlotsTotal: number;
  /** Total heat generated by weapons/equipment */
  heatGenerated: number;
  /** Total heat dissipation from heat sinks */
  heatDissipation: number;
  /** Battle Value (optional) */
  battleValue?: number;
  /** Validation status */
  validationStatus: ValidationStatus;
  /** Number of validation errors */
  errorCount: number;
  /** Number of validation warnings */
  warningCount: number;
}

interface UnitInfoBannerProps {
  /** Unit statistics */
  stats: UnitStats;
  /** On reset button click */
  onReset?: () => void;
  /** On debug button click */
  onDebug?: () => void;
  /** Additional CSS classes */
  className?: string;
}

// =============================================================================
// Styles
// =============================================================================

const styles = {
  label: 'text-[10px] font-medium text-text-theme-secondary uppercase tracking-wider',
  value: {
    normal: 'text-white',
    warning: 'text-amber-400',
    error: 'text-red-400',
    success: 'text-green-400',
    engine: 'text-orange-500', // Matches engine color from slotColors
    bv: 'text-cyan-400', // Battle Value - distinctive cyan
  },
  muted: 'text-slate-500',
} as const;

// =============================================================================
// Helper Components
// =============================================================================

interface CapacityStatProps {
  label: string;
  current: number | string;
  max: number | string;
  unit?: string;
  status?: 'normal' | 'warning' | 'error' | 'success';
}

/**
 * Displays a stat in "current / max" format with color coding
 */
function CapacityStat({ label, current, max, unit = '', status = 'normal' }: CapacityStatProps) {
  const valueColor = styles.value[status];
  
  return (
    <div className="flex flex-col items-center gap-0.5">
      <span className={styles.label}>{label}</span>
      <div className="flex items-baseline gap-0.5 sm:gap-1">
        <span className={`text-sm sm:text-lg font-bold ${valueColor}`}>
          {current}{unit}
        </span>
        <span className={`text-xs sm:text-base ${styles.muted}`}>/</span>
        <span className={`text-xs sm:text-sm ${styles.muted}`}>
          {max}{unit}
        </span>
      </div>
    </div>
  );
}

interface SimpleStatProps {
  label: string;
  value: number | string;
  status?: 'normal' | 'warning' | 'error' | 'success' | 'engine' | 'bv';
}

/**
 * Displays a simple single-value stat
 */
function SimpleStat({ label, value, status = 'normal' }: SimpleStatProps) {
  const valueColor = styles.value[status];
  
  return (
    <div className="flex flex-col items-center gap-0.5">
      <span className={styles.label}>{label}</span>
      <span className={`text-sm sm:text-lg font-bold ${valueColor}`}>{value}</span>
    </div>
  );
}

interface MovementStatProps {
  walkMP: number;
  runMP: number;
  jumpMP: number;
  maxRunMP?: number;
}

/**
 * Displays movement in compact format: 5 / 8 [10] / 5
 * Shows Walk / Run [MaxRun] / Jump
 */
function MovementStat({ walkMP, runMP, jumpMP, maxRunMP }: MovementStatProps) {
  const hasEnhancement = maxRunMP && maxRunMP > runMP;
  
  return (
    <div className="flex flex-col items-center gap-0.5">
      <span className={`${styles.label} hidden sm:block`}>WALK / RUN / JUMP</span>
      <span className={`${styles.label} sm:hidden`}>W/R/J</span>
      <div className="flex items-baseline gap-0.5 sm:gap-1">
        <span className="text-sm sm:text-lg font-bold text-white">{walkMP}</span>
        <span className={`text-xs sm:text-base ${styles.muted}`}>/</span>
        <span className="text-sm sm:text-lg font-bold text-white">{runMP}</span>
        {hasEnhancement && (
          <span className="text-sm sm:text-lg font-bold text-white">[{maxRunMP}]</span>
        )}
        <span className={`text-xs sm:text-base ${styles.muted}`}>/</span>
        <span className="text-sm sm:text-lg font-bold text-white">{jumpMP}</span>
      </div>
    </div>
  );
}

// =============================================================================
// Main Component
// =============================================================================

/**
 * Unit information banner with stats display in "current / max" format
 */
export function UnitInfoBanner({
  stats,
  onReset,
  onDebug,
  className = '',
}: UnitInfoBannerProps): React.ReactElement {
  // Calculate status colors
  const weightStatus: 'normal' | 'warning' | 'error' = 
    stats.weightUsed > stats.tonnage ? 'error' :
    stats.weightRemaining < 0.5 ? 'warning' : 'normal';
  
  const slotsStatus: 'normal' | 'warning' | 'error' = 
    stats.criticalSlotsUsed > stats.criticalSlotsTotal ? 'error' : 'normal';
  
  const heatStatus: 'normal' | 'warning' | 'error' | 'success' = 
    stats.heatGenerated > stats.heatDissipation ? 'error' :
    stats.heatGenerated === stats.heatDissipation ? 'warning' : 'success';
  
  return (
    <div className={`bg-surface-base border border-border-theme-subtle rounded-lg ${className}`}>
      {/* Responsive container - stack on mobile, flex row on larger screens */}
      <div className="flex flex-col sm:flex-row sm:flex-wrap items-stretch">
        {/* Section 1: Identity + Validation - full width on mobile */}
        <div className="w-full sm:w-auto px-3 sm:px-4 py-1.5 sm:py-2 border-b sm:border-r border-border-theme-subtle">
          <div className="flex items-center gap-2 sm:gap-3">
            <div className="min-w-0 flex-1">
              <h2 className="text-base sm:text-lg font-bold text-white truncate">{stats.name}</h2>
              <div className="flex flex-wrap items-center gap-1.5 sm:gap-2 mt-0.5">
                <span className="text-xs sm:text-sm text-text-theme-secondary">{stats.tonnage}t</span>
                <TechBaseBadge techBaseMode={stats.techBaseMode} />
                <ValidationBadge 
                  status={stats.validationStatus}
                  label={stats.validationStatus === 'valid' ? 'Valid' : 
                        `${stats.errorCount} errors, ${stats.warningCount} warnings`}
                />
              </div>
            </div>
          </div>
        </div>
        
        {/* Section 2: Movement Stats */}
        <div className="px-3 sm:px-4 py-1.5 sm:py-2 flex items-center justify-center gap-2 sm:gap-4 border-b sm:border-b-0 sm:border-r border-border-theme-subtle">
          <MovementStat 
            walkMP={stats.walkMP} 
            runMP={stats.runMP} 
            jumpMP={stats.jumpMP}
            maxRunMP={stats.maxRunMP}
          />
        </div>
        
        {/* Section 3: Capacity Stats - grows to fill available space, wraps on mobile */}
        <div className="flex-1 px-2 sm:px-4 py-1.5 sm:py-2 flex flex-wrap items-center justify-around gap-1 sm:gap-2 border-b sm:border-b-0 sm:border-r border-border-theme-subtle min-w-0">
          <SimpleStat 
            label="BV"
            value={stats.battleValue?.toLocaleString() ?? '-'}
            status="bv"
          />
          <SimpleStat 
            label="ENGINE"
            value={stats.engineRating}
            status="engine"
          />
          <CapacityStat
            label="WEIGHT"
            current={stats.weightUsed.toFixed(1)}
            max={stats.tonnage.toFixed(1)}
            unit="t"
            status={weightStatus}
          />
          <CapacityStat
            label="ARMOR"
            current={stats.armorPoints}
            max={stats.maxArmorPoints}
            status="normal"
          />
          <CapacityStat
            label="SLOTS"
            current={stats.criticalSlotsUsed}
            max={stats.criticalSlotsTotal}
            status={slotsStatus}
          />
          <CapacityStat
            label="HEAT"
            current={stats.heatGenerated}
            max={stats.heatDissipation}
            status={heatStatus}
          />
        </div>
        
        {/* Section 4: Optional Actions (only render if actions exist) */}
        {(onReset || onDebug) && (
          <div className="px-4 py-2 flex items-center justify-center gap-3 min-w-fit">
            {onReset && (
              <button
                onClick={onReset}
                className="px-3 py-1.5 text-sm bg-surface-raised hover:bg-slate-600 text-slate-300 rounded transition-colors"
              >
                Reset
              </button>
            )}
            {onDebug && (
              <button
                onClick={onDebug}
                className="px-3 py-1.5 text-sm bg-surface-raised hover:bg-slate-600 text-slate-300 rounded transition-colors"
              >
                Debug
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
