import type { ICombatRequirementSupportEntry } from './CombatValidationRequirementSupport.types';

import { TERRAIN_LOS_SIDE_PATH_UNSUPPORTED_IDS } from './CombatRuleSupport';
import {
  integrated,
  outOfScope,
} from './CombatValidationRequirementSupport.builders';
import {
  PHYSICAL_LEGALITY_GATE_SUPPORT_REFS,
  DISPLACEMENT_DOMINO_SECONDARY_FALLOUT_SUPPORT_REFS,
  DISPLACEMENT_DOMINO_SECONDARY_FALLOUT_OUT_OF_SCOPE_REFS,
  MOVEMENT_RULE_SUPPORT_REFS,
  MOVEMENT_ENHANCEMENT_SUPPORT_REFS,
  TERRAIN_ENVIRONMENT_SUPPORT_REFS,
  TERRAIN_TYPE_MOVEMENT_SUPPORT_REFS,
  TERRAIN_TYPE_LOS_SUPPORT_REFS,
  TERRAIN_TYPE_ATTACK_MODIFIER_SUPPORT_REFS,
  TERRAIN_TYPE_HEAT_SUPPORT_REFS,
  TERRAIN_TYPE_PSR_SUPPORT_REFS,
  PILOT_SKILL_SUPPORT_REFS,
  PILOT_ABILITY_SUPPORT_REFS,
  CANONICAL_SPA_SUPPORT_REFS,
  MECH_QUIRK_SUPPORT_REFS,
  PILOT_MODIFIER_RESOLVER_SUPPORT_REFS,
  HEAT_GENERATION_SUPPORT_REFS,
  HEAT_DISSIPATION_SUPPORT_REFS,
  HEAT_LIFECYCLE_SUPPORT_REFS,
  HEAT_DRIVEN_MODIFIER_SUPPORT_REFS,
  RANGE_BRACKET_SUPPORT_REFS,
  ATTACK_INVALIDATION_REASON_SUPPORT_REFS,
  INVALID_TARGET_STATE_SUPPORT_REFS,
  ATTACK_INVALIDATION_SIDE_EFFECT_SUPPORT_REFS,
  TO_HIT_CORE_MODIFIER_SUPPORT_REFS,
  TO_HIT_ADVANCED_MODIFIER_SUPPORT_REFS,
  DAMAGE_RESOLUTION_SUPPORT_REFS,
  DESTRUCTION_CAUSE_SUPPORT_REFS,
  CRITICAL_COMPONENT_SUPPORT_REFS,
  CRITICAL_SLOT_EFFECT_SUPPORT_REFS,
  PILOT_DAMAGE_SUPPORT_REFS,
  PSR_RESOLUTION_SUPPORT_REFS,
  PSR_TRIGGER_SUPPORT_REFS,
  CRITICAL_SLOT_HYDRATION_SUPPORT_REFS,
  RUNNER_INTERACTIVE_PARITY_SUPPORT_REFS,
  BATTLEMECH_EVENT_SUPPORT_REFS,
  NON_BATTLEMECH_EVENT_SCOPE_SUPPORT_REFS,
} from './CombatValidationRequirementSupport.supportRefLists';
import { MEGAMEK_EJECTION_LIFECYCLE_SOURCE_REFS } from './CombatValidationRequirementSupport.types';

export const BATTLEMECH_VALIDATION_REQUIREMENT_HEAT_PHYSICAL_SUPPORT = {
  'heat-generation': integrated(
    'heat-generation',
    'Heat rules cover movement heat, declared TacOps Sprint normal-engine heat, declared TacOps Evade heat, jump-distance heat, weapon heat, engine heat, environmental fire heat, and heat generated event emission',
    HEAT_GENERATION_SUPPORT_REFS,
  ),
  'heat-dissipation': integrated(
    'heat-dissipation',
    'Heat rules cover heat sink count, double sink rating, destroyed heat sink dissipation loss, water cooling, and environmental dissipation modifiers',
    HEAT_DISSIPATION_SUPPORT_REFS,
  ),
  'heat-lifecycle': integrated(
    'heat-lifecycle',
    'Heat rules cover threshold effects, shutdown checks, auto-shutdown, startup, heat pilot damage, optional MaxTech heat critical damage, and runner/event-sourced heat-induced ammo explosion selection plus CASE-aware damage cascade',
    HEAT_LIFECYCLE_SUPPORT_REFS,
  ),
  'heat-driven-modifiers': integrated(
    'heat-driven-modifiers',
    'Heat-driven modifier support covers source-backed Hot Dog heat roll relief, Some Like It Hot heat to-hit relief, and weapon cooling quirk heat changes while keeping local-only Cool Under Fire out-of-scope and unconsumed by BattleMech heat resolution',
    HEAT_DRIVEN_MODIFIER_SUPPORT_REFS,
  ),
  'range-validation': integrated(
    'range-validation',
    'Range support covers short, medium, long, extreme, out-of-range invalidation, and minimum range penalties',
    [...RANGE_BRACKET_SUPPORT_REFS, 'ruleSupport.toHitModifiers.minimum-range'],
  ),
  'attack-invalidation': integrated(
    'attack-invalidation',
    'Invalidation support covers range, LOS, target state, attacker evasion, ammo, same-hex, unknown weapon, destroyed weapon, jammed weapon, and no-side-effect guarantees',
    [
      ...ATTACK_INVALIDATION_REASON_SUPPORT_REFS,
      ...INVALID_TARGET_STATE_SUPPORT_REFS,
      ...ATTACK_INVALIDATION_SIDE_EFFECT_SUPPORT_REFS,
    ],
  ),
  'to-hit-core-modifiers': integrated(
    'to-hit-core-modifiers',
    'Runner to-hit support covers gunnery, range, minimum range, movement including explicit target-sprinted relief, heat, environment, target state, DFA target class, DFA piloting differential, partial cover, terrain features, and indirect fire',
    TO_HIT_CORE_MODIFIER_SUPPORT_REFS,
  ),
  'to-hit-advanced-modifiers': integrated(
    'to-hit-advanced-modifiers',
    'To-hit helpers cover wounds, sensors, actuators, attacker prone, hull-down, secondary targets, called shots, explicit target evasion including 0..3 Skilled Evasion bonus state across ranged and physical to-hit, ECM, C3, terrain features, and source-backed TacOps Sprint/Evade movement creation, with C3 explicit-state consumption, attack-time lifecycle and critical-slot damage refresh, attacker-evading ranged invalidation, conservative runner plus pre-battle/GameCreated equipment seeding, unambiguous single-network formation, independent side-by-side formation/denial evaluation, and fail-closed denial boundaries; residual C3 authoring and same-side partitioning are split out of the BattleMech runtime to-hit validation blocker set',
    [
      ...TO_HIT_ADVANCED_MODIFIER_SUPPORT_REFS,
      'actions.composerMovementModes.movement.sprint',
      'actions.tacticalCommands.movement.evade',
    ],
  ),
  'terrain-movement-los-cover': integrated(
    'terrain-movement-los-cover',
    'Terrain matrices cover movement, MekStation direct and cumulative-density LOS blocking, source-backed land-to-depth-2+ water endpoint blocking, represented single-path pure elevation LOS blocking with direct-fire invalidation, represented divided-path pure elevation LOS blocking, represented underwater clear/non-water depth-0 LOS blocking, represented underwater endpoint-height/minimum-depth LOS metadata, represented same-building building-hex LOS blocking, represented same-building endpoint elevation-difference LOS counting, represented building-height LOS blocking, represented grounded DropShip level-10 entity LOS cover, represented fuel-tank elevation metadata, represented building/fuel-tank/grounded-DropShip damageable cover-provider metadata, represented divided LOS side-path blocking and modifier selection, represented TacOps heavy-industrial and planted-field LOS1 diagram density/elevation, partial-cover derivation for every TerrainType, and no exact terrain LOS leaf blocker remains in the current gap inventory',
    [
      'ruleSupport.terrainEnvironment.terrain-movement-costs',
      'ruleSupport.terrainEnvironment.terrain-los-blocking',
      'ruleSupport.terrainEnvironment.terrain-los-water-endpoint-blocking',
      'ruleSupport.terrainEnvironment.terrain-los-underwater-clear-hex-blocking',
      'ruleSupport.terrainEnvironment.terrain-los-underwater-depth-height-side-paths',
      'ruleSupport.terrainEnvironment.terrain-los-same-building-hex-blocking',
      'ruleSupport.terrainEnvironment.terrain-los-same-building-level-count',
      'ruleSupport.terrainEnvironment.terrain-los-building-height-blocking',
      'ruleSupport.terrainEnvironment.terrain-los-divided-side-path-blocking',
      'ruleSupport.terrainEnvironment.terrain-los-divided-elevation-blocking',
      'ruleSupport.terrainEnvironment.terrain-los-intervening-elevation-blocking',
      'ruleSupport.terrainEnvironment.terrain-los-side-paths',
      ...TERRAIN_LOS_SIDE_PATH_UNSUPPORTED_IDS.map(
        (supportId) => `ruleSupport.terrainEnvironment.${supportId}`,
      ),
      'ruleSupport.terrainEnvironment.terrain-partial-cover',
      ...TERRAIN_TYPE_MOVEMENT_SUPPORT_REFS,
      ...TERRAIN_TYPE_LOS_SUPPORT_REFS,
    ],
  ),
  'terrain-environment-modifiers': integrated(
    'terrain-environment-modifiers',
    'Terrain/environment maps track woods, rubble, rough, water, ice, swamp, buildings, fire, smoke, fog, night, dust, mines, and extreme conditions, including explicit-load building-collapse PSR queueing, represented TerrainType.Mines BattleMech entry damage, represented encoded damage levels, represented entry side paths, represented battle-wide IGameState.minefields coordinate-state entry damage, represented minefield add/set/reset/remove/clear/detect/detonate lifecycle replay, represented explicit GameCreated/prebattle coordinate minefield authoring, represented manual conventional and command-detonated minefield detonation controls, represented clearing/sweeper/reset events, represented movement detonation event emission, represented hidden conventional minefield detection/reveal state, represented density trigger targets, represented conventional/inferno/active/EMP density-decrement behavior, represented EMP no-effect/interference/shutdown outcomes, represented active ground-entry suppression, represented active BattleMech jump-entry triggering, represented typed non-conventional minefield no-fallback guards with resulting damage PSR evidence, and no exact terrain LOS or minefield leaf blocker remains in the current gap inventory',
    [
      ...TERRAIN_ENVIRONMENT_SUPPORT_REFS,
      ...TERRAIN_LOS_SIDE_PATH_UNSUPPORTED_IDS.map(
        (supportId) => `ruleSupport.terrainEnvironment.${supportId}`,
      ),
      ...TERRAIN_TYPE_ATTACK_MODIFIER_SUPPORT_REFS,
      ...TERRAIN_TYPE_HEAT_SUPPORT_REFS,
      ...TERRAIN_TYPE_PSR_SUPPORT_REFS,
    ],
  ),
  'physical-core-actions': integrated(
    'physical-core-actions',
    'Physical action maps, runner behavior tests, event-sourced physical resolution, the MegaMek physical action class scope catalog, and the source-checked legality gate catalog cover punch, kick, push, optional TacOps trip, source-backed thrash, optional TacOps jump-jet attacks, source-backed brush-off, normal TacOps grapple, source-backed normal break-grapple, charge, death from above, active TSM damage, underwater modifiers, source-backed target-evasion physical to-hit, the represented Environmental Specialist Light physical to-hit helper slice, successful push/charge/DFA hit displacement, occupied-hex domino positional displacement cascades with DominoEffect PSRs, represented domino step-out/CFR payload decisions with successful domino_step_out application and failed/declined/no-response forced fallback, represented minefield fallout when physical displacement lands a BattleMech in existing TerrainType.Mines or represented conventional coordinate-state minefields, represented detonated coordinate suppression and typed non-conventional no-fallback guards for domino mine destinations, DFA-miss friendly occupied displacement avoidance, runtime-hydrated grounded DropShip radius-two DFA hit displacement search, source-backed two-level BattleMech displacement elevation caps, source-backed impassable-terrain and overgrown woods/jungle displacement rejection, runner same-phase displacement grid occupancy refresh, blocked successful-charge displacement no-op/no-PSR semantics, charge/DFA miss displacement, runner automatic charge/DFA selection from movement state, shared same-board rejection, shared retreated/ejected targetability removal/rejection, shared evading-attacker rejection, shared cargo-interaction attacker rejection, represented carried-cargo arm-dependent lockout, shared transported-passenger target rejection, shared swarming-target rejection, shared target-making-DFA rejection, shared airborne-target rejection, shared building-occupancy rejection, explicit non-unit invalid hex target rejection, source-backed gun-emplacement automatic success for punch/kick/DFA/melee targets, source-backed selected-arm-missing punch rejection, source-backed missing-leg kick rejection, source-backed prone charge-attacker rejection, source-backed stuck charge/DFA attacker rejection, source-backed BattleMech charge gun-emplacement target-class rejection, push attacker/target Mek unit-type rejection, push quad BattleMech rejection, push airborne-attacker rejection, push rear-flipped-arm rejection, push displacement-state/counter-push rejection, push building/fuel-tank explicit target rejection, charge/DFA building and fuel-tank explicit target rejection, charge standing-Mek target rejection, charge non-Mek-to-infantry/ProtoMech target rejection, charge elevation-overlap rejection, charge/DFA target movement-complete/immobile rejection, charge/DFA displacement-state rejection, DFA mechanical jump booster movement-step rejection, DFA infantry-family attacker rejection, DFA DropShip target rejection, DFA VTOL/WIGE elevation reach with hydrated jump MP/elevation context plus combat motion type in eligibility, event-sourced declaration/resolution, runner resolution, automatic runner selection, DFA target-inside-building rejection, push both-arms-present rejection, push arm-fired helper/session/runner weapon-location rejection, source-backed explicit scope splits for extra MegaMek physical classes, and out-of-scope splits for non-BattleMech or construction-authoring-only physical weapon surfaces',
    [
      'actions.physicalAttackCommands.punch',
      'actions.physicalAttackCommands.kick',
      'actions.physicalAttackCommands.push',
      'actions.physicalAttackCommands.trip',
      'actions.physicalAttackCommands.thrash',
      'actions.physicalAttackCommands.jump-jet-attack',
      'actions.physicalAttackCommands.grapple',
      'actions.physicalAttackCommands.break-grapple',
      'actions.physicalAttackCommands.charge',
      'actions.physicalAttackCommands.dfa',
      'actions.physicalActionClassScope.punch',
      'actions.physicalActionClassScope.kick',
      'actions.physicalActionClassScope.push',
      'actions.physicalActionClassScope.charge',
      'actions.physicalActionClassScope.dfa',
      'actions.physicalActionClassScope.club',
      'actions.physicalActionClassScope.brush-off',
      'actions.physicalActionClassScope.thrash',
      'actions.physicalActionClassScope.trip',
      'actions.physicalActionClassScope.grapple',
      'actions.physicalActionClassScope.break-grapple',
      'actions.physicalActionClassScope.jump-jet-attack',
      'actions.physicalActionClassScope.airmek-ram',
      'actions.physicalActionClassScope.battle-armor-vibro-claw',
      'actions.physicalActionClassScope.lay-explosives',
      'actions.physicalActionClassScope.protomek-physical',
      'actions.physicalActionClassScope.ram',
      'lifecycleAndPsr.actionEligibility.retreated-targetability',
      'lifecycleAndPsr.actionEligibility.ejected-targetability',
      ...PHYSICAL_LEGALITY_GATE_SUPPORT_REFS,
      'ruleSupport.physicalDamageModifiers.tsm',
      'ruleSupport.physicalDamageModifiers.underwater',
    ],
  ),
  'physical-weapon-actions': outOfScope(
    'physical-weapon-actions',
    'Runtime physical weapon actions cover player commands, wire intents, runner resolution, active TSM damage context, source-backed melee damage/to-hit modifiers for hatchet, sword, mace, lance, retractable blade, flail, and wrecking ball, plus source-backed claw punch and talon kick/DFA damage modifiers including destroyed physical-equipment critical production, destroyed/missing/breached represented equipment critical events, and represented destroyed-location replay',
    'The remaining physical-weapon residual is outside this BattleMech runtime validation matrix: source-construction/editor authoring of automatic claw/talon mounted-equipment lifecycle events when no represented CriticalHitResolved payload, physical critical-manifest entry, or destroyed-location event exists; full physical weapon mount authoring/mode state beyond represented attack declarations; and non-BattleMech physical weapon families that require separate validation matrices',
    [
      'actions.physicalAttackCommands.hatchet',
      'actions.physicalAttackCommands.sword',
      'actions.physicalAttackCommands.mace',
      'actions.physicalAttackCommands.lance',
      'actions.physicalAttackCommands.retractable-blade',
      'actions.physicalAttackCommands.flail',
      'actions.physicalAttackCommands.wrecking-ball',
      'featureSupport.physicalWeapons.hatchet',
      'featureSupport.physicalWeapons.sword',
      'featureSupport.physicalWeapons.mace',
      'featureSupport.physicalWeapons.lance',
      'featureSupport.physicalWeapons.retractable-blade',
      'featureSupport.physicalWeapons.claws',
      'featureSupport.physicalWeapons.flail',
      'featureSupport.physicalWeapons.talons',
      'featureSupport.physicalWeapons.wrecking-ball',
      'ruleSupport.physicalDamageModifiers.claw-equipment-lifecycle',
      'ruleSupport.physicalDamageModifiers.claw-physical-critical-production',
      'ruleSupport.physicalDamageModifiers.claw-represented-equipment-cleanup',
      'ruleSupport.physicalDamageModifiers.claws',
      'ruleSupport.physicalDamageModifiers.tsm',
      'ruleSupport.physicalDamageModifiers.talon-equipment-lifecycle',
      'ruleSupport.physicalDamageModifiers.talon-physical-critical-production',
      'ruleSupport.physicalDamageModifiers.talon-represented-equipment-cleanup',
      'ruleSupport.physicalDamageModifiers.talons',
      'ruleSupport.physicalDamageModifiers.underwater',
    ],
  ),
  'physical-self-risk': integrated(
    'physical-self-risk',
    'Runner and event-sourced physical behavior cover charge/DFA target damage, self-damage, represented push/charge/DFA/charge-miss target-displacement legality, occupied-hex domino positional displacement cascades with DominoEffect PSRs, represented domino step-out/CFR decisions that move successful blockers without forced DominoEffect PSRs and fall back to forced domino on invalid/failed/declined/no-response decisions, represented TerrainType.Mines destination fallout during physical displacement with GamePhase.PhysicalAttack mine damage and damage PSR side effects, represented conventional coordinate-state minefield damage plus density reduction/MinefieldChanged fallout, already-detonated coordinate suppression, typed non-conventional no-fallback guards, DFA-miss friendly occupied displacement avoidance, runtime-hydrated grounded DropShip radius-two DFA hit displacement search, same-phase runner occupancy refresh after displacement, blocked successful-charge displacement no-op/no-PSR semantics, source-backed immediate DFA miss fall damage/prone timing and pilot-damage avoidance, DFA impossible-displacement destruction, source-backed successful-DFA attacker PSR +4, miss consequences, PSR queueing, and out-of-scope splits for DropShip footprint/secondary-hex consequences beyond the BattleMech matrix',
    [
      'lifecycleAndPsr.psrTriggers.charged',
      'lifecycleAndPsr.psrTriggers.charge_miss',
      'lifecycleAndPsr.psrTriggers.dfa_target',
      'lifecycleAndPsr.psrTriggers.dfa_miss',
      'lifecycleAndPsr.psrTriggers.domino_effect',
      'ruleSupport.physicalLegalityGates.shared.displacement-domino-positional-chain',
      'ruleSupport.physicalLegalityGates.shared.displacement-domino-minefield-fallout',
      'ruleSupport.physicalLegalityGates.shared.displacement-domino-chain',
      'ruleSupport.physicalLegalityGates.shared.displacement-domino-secondary-fallout',
      ...DISPLACEMENT_DOMINO_SECONDARY_FALLOUT_SUPPORT_REFS,
      ...DISPLACEMENT_DOMINO_SECONDARY_FALLOUT_OUT_OF_SCOPE_REFS,
      'ruleSupport.physicalLegalityGates.shared.displacement-friendly-avoidance',
      'ruleSupport.physicalLegalityGates.shared.displacement-dropship-radius',
    ],
  ),
} satisfies Record<string, ICombatRequirementSupportEntry>;
