import { GameEventType } from '@/types/gameplay';

import type { ICombatFeatureSourceReference } from './CombatFeatureSourceReference';

import {
  BATTLEMECH_CRITICAL_EVENT_SOURCE_REFS,
  BATTLEMECH_DAMAGE_EVENT_SOURCE_REFS,
  BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  BATTLEMECH_INDIRECT_FIRE_EVENT_SOURCE_REFS,
  BATTLEMECH_PHYSICAL_EVENT_SOURCE_REFS,
  BATTLEMECH_PSR_EVENT_SOURCE_REFS,
  BATTLEMECH_RANGED_ATTACK_EVENT_SOURCE_REFS,
  BATTLEMECH_SPECIAL_PROJECTILE_EVENT_SOURCE_REFS,
} from './CombatBattleMechEventSourceRefs.combat';
import {
  BATTLEMECH_ATTACK_REVEAL_EVENT_SOURCE_REFS,
  BATTLEMECH_COMMAND_RESULT_EVENT_SOURCE_REFS,
  BATTLEMECH_GROUND_OBJECT_EVENT_SOURCE_REFS,
  BATTLEMECH_LIFECYCLE_EVENT_SOURCE_REFS,
  BATTLEMECH_MINEFIELD_EVENT_SOURCE_REFS,
  BATTLEMECH_MOVEMENT_EVENT_SOURCE_REFS,
  BATTLEMECH_TURN_PHASE_EVENT_SOURCE_REFS,
} from './CombatBattleMechEventSourceRefs.lifecycle';
import {
  BATTLEMECH_MORALE_WITHDRAWAL_EVENT_SOURCE_REFS,
  BATTLEMECH_NEURAL_INTERFACE_EVENT_SOURCE_REFS,
  BATTLEMECH_OBJECTIVE_EVENT_SOURCE_REFS,
  BATTLEMECH_RETREAT_EJECTION_EVENT_SOURCE_REFS,
} from './CombatBattleMechEventSourceRefs.terminal';
import { BATTLEMECH_SPOTTING_EVENT_SOURCE_REFS } from './CombatSpottingSourceRefs';

export const BATTLEMECH_EVENT_SOURCE_REFS: Readonly<
  Partial<Record<GameEventType, readonly ICombatFeatureSourceReference[]>>
> = {
  [GameEventType.GameCreated]: BATTLEMECH_LIFECYCLE_EVENT_SOURCE_REFS,
  [GameEventType.GameStarted]: BATTLEMECH_LIFECYCLE_EVENT_SOURCE_REFS,
  [GameEventType.GameEnded]: BATTLEMECH_LIFECYCLE_EVENT_SOURCE_REFS,
  [GameEventType.TurnStarted]: BATTLEMECH_TURN_PHASE_EVENT_SOURCE_REFS,
  [GameEventType.TurnEnded]: BATTLEMECH_TURN_PHASE_EVENT_SOURCE_REFS,
  [GameEventType.PhaseChanged]: BATTLEMECH_TURN_PHASE_EVENT_SOURCE_REFS,
  [GameEventType.InitiativeRolled]: BATTLEMECH_TURN_PHASE_EVENT_SOURCE_REFS,
  [GameEventType.InitiativeOrderSet]: BATTLEMECH_TURN_PHASE_EVENT_SOURCE_REFS,
  [GameEventType.MovementDeclared]: BATTLEMECH_MOVEMENT_EVENT_SOURCE_REFS,
  [GameEventType.MovementInvalid]: BATTLEMECH_MOVEMENT_EVENT_SOURCE_REFS,
  [GameEventType.MovementLocked]: BATTLEMECH_MOVEMENT_EVENT_SOURCE_REFS,
  [GameEventType.MovementEnhancementActivated]:
    BATTLEMECH_MOVEMENT_EVENT_SOURCE_REFS,
  [GameEventType.RuntimeMovementStateChanged]:
    BATTLEMECH_MOVEMENT_EVENT_SOURCE_REFS,
  [GameEventType.FacingChanged]: BATTLEMECH_MOVEMENT_EVENT_SOURCE_REFS,
  [GameEventType.MinefieldChanged]: BATTLEMECH_MINEFIELD_EVENT_SOURCE_REFS,
  [GameEventType.EmpMinefieldEffectApplied]:
    BATTLEMECH_MINEFIELD_EVENT_SOURCE_REFS,
  [GameEventType.GroundObjectPickedUp]:
    BATTLEMECH_GROUND_OBJECT_EVENT_SOURCE_REFS,
  [GameEventType.GroundObjectDropped]:
    BATTLEMECH_GROUND_OBJECT_EVENT_SOURCE_REFS,
  [GameEventType.AttackDeclared]: BATTLEMECH_RANGED_ATTACK_EVENT_SOURCE_REFS,
  [GameEventType.AttackLocked]: BATTLEMECH_RANGED_ATTACK_EVENT_SOURCE_REFS,
  [GameEventType.AttacksRevealed]: BATTLEMECH_ATTACK_REVEAL_EVENT_SOURCE_REFS,
  [GameEventType.CommandResultPublished]:
    BATTLEMECH_COMMAND_RESULT_EVENT_SOURCE_REFS,
  [GameEventType.AttackResolved]: BATTLEMECH_RANGED_ATTACK_EVENT_SOURCE_REFS,
  [GameEventType.AttackInvalid]: BATTLEMECH_RANGED_ATTACK_EVENT_SOURCE_REFS,
  [GameEventType.DamageApplied]: BATTLEMECH_DAMAGE_EVENT_SOURCE_REFS,
  [GameEventType.IndirectFireSpotterSelected]:
    BATTLEMECH_INDIRECT_FIRE_EVENT_SOURCE_REFS,
  [GameEventType.IndirectFireSpotterLost]:
    BATTLEMECH_INDIRECT_FIRE_EVENT_SOURCE_REFS,
  [GameEventType.IndirectFireForwardObserver]:
    BATTLEMECH_INDIRECT_FIRE_EVENT_SOURCE_REFS,
  [GameEventType.IndirectFireNarcOverride]:
    BATTLEMECH_INDIRECT_FIRE_EVENT_SOURCE_REFS,
  [GameEventType.SpottingDeclared]: BATTLEMECH_SPOTTING_EVENT_SOURCE_REFS,
  [GameEventType.TerrainChanged]: BATTLEMECH_MOVEMENT_EVENT_SOURCE_REFS,
  [GameEventType.HeatGenerated]: BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  [GameEventType.HeatDissipated]: BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  [GameEventType.HeatEffectApplied]: BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  [GameEventType.PilotHit]: BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  [GameEventType.UnitDestroyed]: BATTLEMECH_DAMAGE_EVENT_SOURCE_REFS,
  [GameEventType.AmmoExplosion]: BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  [GameEventType.CriticalHit]: BATTLEMECH_CRITICAL_EVENT_SOURCE_REFS,
  [GameEventType.CriticalHitResolved]: BATTLEMECH_CRITICAL_EVENT_SOURCE_REFS,
  [GameEventType.PSRTriggered]: BATTLEMECH_PSR_EVENT_SOURCE_REFS,
  [GameEventType.PSRResolved]: BATTLEMECH_PSR_EVENT_SOURCE_REFS,
  [GameEventType.UnitFell]: BATTLEMECH_PSR_EVENT_SOURCE_REFS,
  [GameEventType.UnitStuck]: BATTLEMECH_PSR_EVENT_SOURCE_REFS,
  [GameEventType.UnitStood]: BATTLEMECH_PSR_EVENT_SOURCE_REFS,
  [GameEventType.PhysicalAttackDeclared]: BATTLEMECH_PHYSICAL_EVENT_SOURCE_REFS,
  [GameEventType.PhysicalAttackResolved]: BATTLEMECH_PHYSICAL_EVENT_SOURCE_REFS,
  [GameEventType.ShutdownCheck]: BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  [GameEventType.StartupAttempt]: BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  [GameEventType.AmmoConsumed]: BATTLEMECH_HEAT_EVENT_SOURCE_REFS,
  [GameEventType.AMSInterception]:
    BATTLEMECH_SPECIAL_PROJECTILE_EVENT_SOURCE_REFS,
  [GameEventType.DesignatorMarkerApplied]:
    BATTLEMECH_SPECIAL_PROJECTILE_EVENT_SOURCE_REFS,
  [GameEventType.LocationDestroyed]: BATTLEMECH_DAMAGE_EVENT_SOURCE_REFS,
  [GameEventType.TransferDamage]: BATTLEMECH_DAMAGE_EVENT_SOURCE_REFS,
  [GameEventType.ComponentDestroyed]: BATTLEMECH_CRITICAL_EVENT_SOURCE_REFS,
  [GameEventType.RetreatTriggered]:
    BATTLEMECH_RETREAT_EJECTION_EVENT_SOURCE_REFS,
  [GameEventType.UnitRetreated]: BATTLEMECH_RETREAT_EJECTION_EVENT_SOURCE_REFS,
  [GameEventType.UnitEjected]: BATTLEMECH_RETREAT_EJECTION_EVENT_SOURCE_REFS,
  [GameEventType.NeuralInterfaceStateChanged]:
    BATTLEMECH_NEURAL_INTERFACE_EVENT_SOURCE_REFS,
  [GameEventType.ObjectiveCaptured]: BATTLEMECH_OBJECTIVE_EVENT_SOURCE_REFS,
  [GameEventType.ObjectiveLost]: BATTLEMECH_OBJECTIVE_EVENT_SOURCE_REFS,
  [GameEventType.ObjectiveProgress]: BATTLEMECH_OBJECTIVE_EVENT_SOURCE_REFS,
  [GameEventType.MoraleShifted]: BATTLEMECH_MORALE_WITHDRAWAL_EVENT_SOURCE_REFS,
  [GameEventType.WithdrawalDeclared]:
    BATTLEMECH_MORALE_WITHDRAWAL_EVENT_SOURCE_REFS,
  [GameEventType.ForcedWithdrawalTriggered]:
    BATTLEMECH_MORALE_WITHDRAWAL_EVENT_SOURCE_REFS,
};
