import {
  integrated,
  outOfScope,
  type ICombatFeatureSupportEntry,
} from './CombatFeatureSupport';
import {
  MEGAMEK_ACTIVE_PROBE_SOURCE_REFS,
  MEGAMEK_AMS_AMMO_LIFECYCLE_SOURCE_REFS,
  MEGAMEK_AMS_ASSIGNMENT_SOURCE_REFS,
  MEGAMEK_AMS_CLUSTER_SOURCE_REFS,
  MEGAMEK_AMS_SINGLE_MISSILE_SOURCE_REFS,
  MEGAMEK_ARTEMIS_CLUSTER_SOURCE_REFS,
  MEGAMEK_ARTEMIS_FCS_SOURCE_REFS,
  MEGAMEK_ECM_SUITE_SOURCE_REFS,
  INARC_POD_BRUSH_OFF_REMOVAL_SOURCE_REFS,
  INARC_POD_BRUSH_OFF_TARGET_SELECTION_SOURCE_REFS,
  MEKSTATION_ARTEMIS_STEALTH_LIFECYCLE_SOURCE_REFS,
  MEGAMEK_INARC_ECM_C3_SOURCE_REFS,
  MEGAMEK_INARC_ECM_SENSOR_EFFECT_SOURCE_REFS,
  MEGAMEK_INARC_ECM_SOURCE_REFS,
  MEGAMEK_INARC_EXPLOSIVE_SOURCE_REFS,
  MEGAMEK_INARC_HAYWIRE_SOURCE_REFS,
  MEGAMEK_INARC_HOMING_SOURCE_REFS,
  MEGAMEK_INARC_NEMESIS_SOURCE_REFS,
  MEGAMEK_INARC_POD_OBJECT_SOURCE_REFS,
  MEGAMEK_INARC_POD_TYPE_SOURCE_REFS,
  MEGAMEK_LBX_SOURCE_REFS,
  MEGAMEK_MML_SOURCE_REFS,
  MEGAMEK_NARC_CLUSTER_SOURCE_REFS,
  MEGAMEK_NARC_MARKER_SOURCE_REFS,
  MEGAMEK_NOVA_CEWS_NETWORK_SOURCE_REFS,
  MEGAMEK_PLASMA_CANNON_BATTLEMECH_TARGET_HEAT_SOURCE_REFS,
  MEGAMEK_RAC_SOURCE_REFS,
  MEGAMEK_STEALTH_ACTIVE_SOURCE_REFS,
  MEGAMEK_STREAK_SRM_SOURCE_REFS,
  MEGAMEK_TAG_CLEAR_SOURCE_REFS,
  MEGAMEK_TAG_DESIGNATION_SOURCE_REFS,
  MEGAMEK_TAG_FAMILY_SOURCE_REFS,
  MEGAMEK_TAG_SEMI_GUIDED_SOURCE_REFS,
  MEGAMEK_UAC_SOURCE_REFS,
} from './CombatSpecialWeaponSourceRefs';

export const SPECIAL_WEAPON_PLASMA_COMBAT_SUPPORT = {
  'plasma-cannon-battlemech-target-heat': integrated(
    'plasma-cannon-battlemech-target-heat',
    'Runner plasma-cannon hits against BattleMechs emit zero BattleMech damage, queue source-backed 2d6 external target heat in a Heat Phase pending bucket, adjust heat for reflective or heat-dissipating armor including PLAYTEST_3 behavior, preserve turn-boundary cap reset, and consume source-backed plasma ammo despite MegaMek energy flags',
    MEGAMEK_PLASMA_CANNON_BATTLEMECH_TARGET_HEAT_SOURCE_REFS,
  ),
  'plasma-cannon-battlemech-heat-phase-pending-bucket': integrated(
    'plasma-cannon-battlemech-heat-phase-pending-bucket',
    'Runner plasma-cannon BattleMech target heat is stored on pendingExternalHeat during Weapon Attack, applies as external HeatGenerated in Heat Phase, clears the pending bucket, and enforces the existing 15-point external heat per-turn cap through externalHeatThisTurn',
    MEGAMEK_PLASMA_CANNON_BATTLEMECH_TARGET_HEAT_SOURCE_REFS,
  ),
} satisfies Record<string, ICombatFeatureSupportEntry>;
