import { MEGAMEK_AMMO_EXPLOSION_PILOT_DAMAGE_SOURCE_REFS } from './CombatConsciousnessSourceRefs';
import {
  EQUIPMENT_ARTEMIS_FCS_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_BOMB_BAY_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_BOMB_BAY_CRITICAL_EFFECT_GAP,
  EQUIPMENT_BLUE_SHIELD_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_BLUE_SHIELD_SPECIAL_RULES_EVIDENCE,
  EQUIPMENT_BLUE_SHIELD_SPECIAL_RULES_GAP,
  EQUIPMENT_CHARGED_CAPACITOR_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_EXTENDED_FUEL_TANK_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_FUEL_INCENDIARY_BRANCH_EVIDENCE,
  EQUIPMENT_FUEL_INCENDIARY_BRANCH_GAP,
  EQUIPMENT_HOT_LOAD_LINKED_AMMO_INFERENCE_EVIDENCE,
  EQUIPMENT_HOT_LOAD_MODE_STATE_INFERENCE_EVIDENCE,
  EQUIPMENT_PROTOTYPE_IMPROVED_JUMP_JET_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_EXPLOSIVE_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_HOT_LOADED_WEAPON_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_RISC_LPM_AMBIGUOUS_LINK_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_RISC_LASER_PULSE_MODULE_INOPERABLE_LINKED_CRITICAL_EFFECT_EVIDENCE,
  EQUIPMENT_RISC_LASER_PULSE_MODULE_CRITICAL_EFFECT_EVIDENCE,
  UNRESOLVED_EQUIPMENT_CRITICAL_EFFECT_BRANCHES,
} from './CombatCriticalSlotEffectSupport';
import {
  MEKSTATION_AC_PLAYTEST_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_ACTIVE_PROBE_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_ARTEMIS_FCS_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEGAMEK_AMMO_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_BLUE_SHIELD_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_CHARGED_CAPACITOR_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_EMERGENCY_COOLANT_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEGAMEK_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_HARJEL_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_HOT_LOADED_WEAPON_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_EXTENDED_FUEL_TANK_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_FUEL_INCENDIARY_SCOPE_SPLIT_SOURCE_REFS,
  MEKSTATION_AMMO_EXHAUSTION_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_GENERIC_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEGAMEK_MTF_EQUIPMENT_CRITICAL_SOURCE_REFS,
  MEGAMEK_MTF_SYSTEM_CRITICAL_SOURCE_REFS,
  MEGAMEK_PARTIAL_WING_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEGAMEK_PHYSICAL_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_PROTOTYPE_IMPROVED_JUMP_JET_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_REPRESENTED_EXPLOSIVE_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_RISC_LASER_PULSE_MODULE_INOPERABLE_LINKED_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_RISC_LASER_PULSE_MODULE_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_SCM_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_SHIELD_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEKSTATION_STEALTH_LINKED_ECM_EQUIPMENT_CRITICAL_EFFECT_SOURCE_REFS,
  MEGAMEK_SYSTEM_CRITICAL_EFFECT_SOURCE_REFS,
} from './CombatCriticalSlotSourceRefs';
import {
  BATTLEMECH_MANUAL_DAMAGE_SOURCE_REFS,
  MEGAMEK_BATTLEMECH_DAMAGE_SOURCE_REFS,
  MEKSTATION_COCKPIT_CRIT_PILOT_DEATH_SOURCE_REFS,
  MEKSTATION_DAMAGE_EVENT_SOURCE_REFS,
  MEKSTATION_DAMAGE_RESOLUTION_SOURCE_REFS,
  MEKSTATION_DESTRUCTION_CAUSE_SOURCE_REFS,
  MEKSTATION_HEAT_AMMO_EXPLOSION_DAMAGE_SOURCE_REFS,
  MEKSTATION_HEAT_PILOT_DAMAGE_SOURCE_REFS,
  MEKSTATION_MAXTECH_HEAT_CRITICAL_SOURCE_REFS,
  MEKSTATION_PILOT_DAMAGE_SOURCE_REFS,
} from './CombatDamageSourceRefs';
import { combatFeatureSourceRef } from './CombatFeatureSourceReference';
import {
  integrated,
  outOfScope,
  type ICombatFeatureSourceReference,
  type ICombatFeatureSupportEntry,
} from './CombatFeatureSupport';
import { DAMAGE_THRESHOLD_PSR_SOURCE_REFS } from './CombatPsrTriggerSourceRefs';

const MEGAMEK_DAMAGE_SOURCE_VERSION =
  '325b2504c7b7750ecdcb85468621fb2de2ad8e60';

export const MEGAMEK_DFA_IMPOSSIBLE_DISPLACEMENT_SOURCE_REFS = [
  combatFeatureSourceRef(
    'megamek-source',
    'MegaMek resolveDfaAttack destroys the attacker on a missed DFA when the target cannot be displaced.',
    'https://github.com/MegaMek/megamek/blob/325b2504c7b7750ecdcb85468621fb2de2ad8e60/megamek/src/megamek/server/totalWarfare/TWGameManager.java#L15233-L15265',
    '325b2504c7b7750ecdcb85468621fb2de2ad8e60',
  ),
  combatFeatureSourceRef(
    'megamek-source',
    'MegaMek resolveDfaAttack destroys the target on a successful DFA when the target cannot be displaced.',
    'https://github.com/MegaMek/megamek/blob/325b2504c7b7750ecdcb85468621fb2de2ad8e60/megamek/src/megamek/server/totalWarfare/TWGameManager.java#L15352-L15366',
    '325b2504c7b7750ecdcb85468621fb2de2ad8e60',
  ),
] satisfies readonly ICombatFeatureSourceReference[];

export const MEGAMEK_FALL_PILOT_DAMAGE_SOURCE_REFS = [
  combatFeatureSourceRef(
    'megamek-source',
    'MegaMek doEntityFall rolls checkPilotAvoidFallDamage after fall damage and applies one crew hit when that piloting check fails.',
    'https://github.com/MegaMek/megamek/blob/325b2504c7b7750ecdcb85468621fb2de2ad8e60/megamek/src/megamek/server/totalWarfare/TWGameManager.java#L23233-L23357',
    '325b2504c7b7750ecdcb85468621fb2de2ad8e60',
  ),
] satisfies readonly ICombatFeatureSourceReference[];

export const MEGAMEK_CASE_AMMO_EXPLOSION_SOURCE_REFS = [
  combatFeatureSourceRef(
    'megamek-source',
    'MegaMek applyEntityArmorDamage skips normal armor absorption for ammoExplosion damage, so the cascade starts at internal structure.',
    `https://github.com/MegaMek/megamek/blob/${MEGAMEK_DAMAGE_SOURCE_VERSION}/megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java#L2844-L2865`,
    MEGAMEK_DAMAGE_SOURCE_VERSION,
  ),
  combatFeatureSourceRef(
    'megamek-source',
    'MegaMek prevents remaining ammo-explosion damage from transferring when the hit location has CASE.',
    `https://github.com/MegaMek/megamek/blob/${MEGAMEK_DAMAGE_SOURCE_VERSION}/megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java#L520-L529`,
    MEGAMEK_DAMAGE_SOURCE_VERSION,
  ),
  combatFeatureSourceRef(
    'megamek-source',
    'MegaMek caps ammo-explosion damage at 10 with CASE and 1 with CASE II before local internal damage resolution and blows out rear armor on surviving torso locations.',
    `https://github.com/MegaMek/megamek/blob/${MEGAMEK_DAMAGE_SOURCE_VERSION}/megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java#L2435-L2489`,
    MEGAMEK_DAMAGE_SOURCE_VERSION,
  ),
  combatFeatureSourceRef(
    'megamek-source',
    'MegaMek Entity.locationHasCase detects mounted CASE or CASE-P in the same location.',
    `https://github.com/MegaMek/megamek/blob/${MEGAMEK_DAMAGE_SOURCE_VERSION}/megamek/src/megamek/common/units/Entity.java#L6867-L6874`,
    MEGAMEK_DAMAGE_SOURCE_VERSION,
  ),
] satisfies readonly ICombatFeatureSourceReference[];

export const CORE_DAMAGE_RESOLUTION_SOURCE_REFS = [
  ...BATTLEMECH_MANUAL_DAMAGE_SOURCE_REFS,
  ...MEGAMEK_BATTLEMECH_DAMAGE_SOURCE_REFS,
  ...MEKSTATION_DAMAGE_RESOLUTION_SOURCE_REFS,
] satisfies readonly ICombatFeatureSourceReference[];

export const DAMAGE_EVENT_SOURCE_REFS = [
  ...MEGAMEK_BATTLEMECH_DAMAGE_SOURCE_REFS,
  ...MEKSTATION_DAMAGE_EVENT_SOURCE_REFS,
] satisfies readonly ICombatFeatureSourceReference[];

export const HEAT_AMMO_EXPLOSION_DAMAGE_CASCADE_SOURCE_REFS = [
  ...MEGAMEK_CASE_AMMO_EXPLOSION_SOURCE_REFS,
  ...MEKSTATION_HEAT_AMMO_EXPLOSION_DAMAGE_SOURCE_REFS,
  ...MEKSTATION_DESTRUCTION_CAUSE_SOURCE_REFS,
] satisfies readonly ICombatFeatureSourceReference[];

export const DAMAGE_DESTRUCTION_CAUSE_SOURCE_REFS = [
  ...BATTLEMECH_MANUAL_DAMAGE_SOURCE_REFS,
  ...MEGAMEK_BATTLEMECH_DAMAGE_SOURCE_REFS,
  ...MEKSTATION_DESTRUCTION_CAUSE_SOURCE_REFS,
] satisfies readonly ICombatFeatureSourceReference[];

export const ENGINE_DESTRUCTION_CAUSE_SOURCE_REFS = [
  ...DAMAGE_DESTRUCTION_CAUSE_SOURCE_REFS,
  ...MEGAMEK_SYSTEM_CRITICAL_EFFECT_SOURCE_REFS,
] satisfies readonly ICombatFeatureSourceReference[];

export { UNRESOLVED_EQUIPMENT_CRITICAL_EFFECT_BRANCHES };
