const MEKSTATION_SOURCE_REF_ANCHOR_REMAP: Readonly<Record<string, string>> = {
  'src/engine/__tests__/InteractiveSession.legAttack.scenario.test.ts#L175-L205':
    'src/engine/__tests__/InteractiveSession.legAttack.scenario.test-helpers.ts#L175-L205',
  'src/engine/adapters/CompendiumAdapter.ts#L185-L208':
    'src/engine/adapters/CompendiumAdapter.weapons.ts#L33-L68',
  'src/engine/GameEngine.phases.ts#L388-L479':
    'src/engine/GameEngine.phases.ts#L398-L444',
  'src/engine/InteractiveSession.actions.ts#L1-L1634':
    'src/engine/InteractiveSession.actions.attackProjection.ts#L22-L60',
  'src/engine/InteractiveSession.actions.ts#L192-L235':
    'src/engine/InteractiveSession.actions.attack.ts#L185-L200',
  'src/engine/InteractiveSession.actions.ts#L326-L397':
    'src/engine/InteractiveSession.actions.battleArmor.ts#L119-L145',
  'src/engine/InteractiveSession.actions.ts#L80-L132':
    'src/engine/InteractiveSession.actions.movement.ts#L90-L161',
  'src/lib/p2p/intentTranslation.ts#L187-L444':
    'src/lib/p2p/intentTranslation.ts#L174-L185',
  'src/lib/p2p/intentTranslation.ts#L189-L468':
    'src/lib/p2p/intentTranslation.ts#L176-L187',
  'src/lib/p2p/intentTranslation.ts#L191-L493':
    'src/lib/p2p/intentTranslation.ts#L178-L189',
  'src/lib/p2p/intentTranslation.ts#L193-L525':
    'src/lib/p2p/intentTranslation.ts#L180-L191',
  'src/lib/p2p/intentTranslation.ts#L195-L564':
    'src/lib/p2p/intentTranslation.ts#L182-L193',
  'src/lib/p2p/intentTranslation.ts#L197-L537':
    'src/lib/p2p/intentTranslationCombatTranslators.ts#L189-L200',
  'src/lib/p2p/intentTranslation.ts#L220-L470':
    'src/lib/p2p/intentTranslation.ts#L263-L274',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1027-L1115':
    'src/simulation/runner/__tests__/criticalHitEvents.06.test.ts#L96-L174',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1394-L1457':
    'src/simulation/runner/__tests__/criticalHitEvents.07.test.ts#L98-L184',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1418-L1547':
    'src/simulation/runner/__tests__/criticalHitEvents.06.test.ts#L184-L232',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1459-L1513':
    'src/simulation/runner/__tests__/criticalHitEvents.12.test.ts#L94-L149',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1459-L1518':
    'src/simulation/runner/__tests__/criticalHitEvents.11.test.ts#L247-L307',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1515-L1562':
    'src/simulation/runner/__tests__/criticalHitEvents.12.test.ts#L208-L254',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1564-L1624':
    'src/simulation/runner/__tests__/criticalHitEvents.12.test.ts#L250-L310',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1677-L1770':
    'src/simulation/runner/__tests__/criticalHitEvents.13.test.ts#L147-L240',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L1913-L1952':
    'src/simulation/runner/__tests__/criticalHitEvents.11.test.ts#L159-L199',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L2005-L2065':
    'src/simulation/runner/__tests__/criticalHitEvents.11.test.ts#L201-L250',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L2616-L2694':
    'src/simulation/runner/__tests__/criticalHitEvents.15.test.ts#L94-L160',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L2818-L2907':
    'src/simulation/runner/__tests__/criticalHitEvents.14.test.ts#L94-L160',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L2851-L2934':
    'src/simulation/runner/__tests__/criticalHitEvents.14.test.ts#L177-L227',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L2897-L2948':
    'src/simulation/runner/__tests__/criticalHitEvents.15.test.ts#L174-L224',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L316-L365':
    'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L247-L270',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L354-L372':
    'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L293-L310',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L367-L393':
    'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L273-L300',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L614-L755':
    'src/simulation/runner/__tests__/criticalHitEvents.02.test.ts#L168-L269',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L718-L760':
    'src/simulation/runner/__tests__/criticalHitEvents.07.test.ts#L188-L243',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L723-L797':
    'src/simulation/runner/__tests__/criticalHitEvents.03.test.ts#L208-L273',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L723-L876':
    'src/simulation/runner/__tests__/criticalHitEvents.03.test.ts#L208-L273',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L782-L865':
    'src/simulation/runner/__tests__/criticalHitEvents.05.test.ts#L96-L162',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L797-L875':
    'src/simulation/runner/__tests__/criticalHitEvents.04.test.ts#L178-L244',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L803-L876':
    'src/simulation/runner/__tests__/criticalHitEvents.05.test.ts#L233-L285',
  'src/simulation/runner/__tests__/criticalHitEvents.test.ts#L938-L1023':
    'src/simulation/runner/__tests__/criticalHitEvents.04.test.ts#L96-L158',
  'src/simulation/runner/__tests__/movementPhase.behavior.test.ts#L1855-L1935':
    'src/simulation/runner/__tests__/movementPhase.behavior.07.test.ts#L92-L139',
  'src/simulation/runner/__tests__/movementPhase.behavior.test.ts#L1917-L1965':
    'src/simulation/runner/__tests__/movementPhase.behavior.16.test.ts#L205-L258',
  'src/simulation/runner/__tests__/movementPhase.behavior.test.ts#L375-L436':
    'src/simulation/runner/__tests__/movementPhase.behavior.test.ts#L139-L224',
  'src/simulation/runner/__tests__/movementPhase.behavior.test.ts#L464-L596':
    'src/simulation/runner/__tests__/movementPhase.behavior.test.ts#L219-L289',
  'src/simulation/runner/__tests__/movementPhase.behavior.test.ts#L692-L752':
    'src/simulation/runner/__tests__/movementPhase.behavior.03.test.ts#L172-L234',
  'src/simulation/runner/__tests__/physicalAttackRunner.behavior.test.ts#L1746-L1798':
    'src/simulation/runner/__tests__/physicalAttackRunner.behavior.17.test.ts#L88-L160',
  'src/simulation/runner/__tests__/physicalAttackRunner.behavior.test.ts#L901-L1039':
    'src/simulation/runner/__tests__/physicalAttackRunner.behavior.02.test.ts#L157-L295',
  'src/simulation/runner/__tests__/SimulationRunner.gameCreated.test.ts#L226-L263':
    'src/simulation/runner/__tests__/SimulationRunner.gameCreated.04.test.ts#L17-L68',
  'src/simulation/runner/__tests__/SimulationRunner.gameCreated.test.ts#L283-L321':
    'src/simulation/runner/__tests__/SimulationRunner.gameCreated.04.test.ts#L74-L113',
  'src/simulation/runner/__tests__/SimulationRunner.gameCreated.test.ts#L322-L369':
    'src/simulation/runner/__tests__/SimulationRunner.gameCreated.test.ts#L17-L73',
  'src/simulation/runner/__tests__/SimulationRunner.gameCreated.test.ts#L494-L549':
    'src/simulation/runner/__tests__/SimulationRunner.gameCreated.test.ts#L181-L244',
  'src/simulation/runner/__tests__/weaponAttackToHitModifiers.behavior.test.ts#L1418-L1768':
    'src/simulation/runner/__tests__/weaponAttackToHitModifiers.behavior.05.test.ts#L208-L219',
  'src/simulation/runner/__tests__/weaponAttackToHitModifiers.behavior.test.ts#L2377-L2425':
    'src/simulation/runner/__tests__/weaponAttackToHitModifiers.behavior.10.test.ts#L181-L229',
  'src/simulation/runner/__tests__/weaponAttackToHitModifiers.behavior.test.ts#L2490-L2568':
    'src/simulation/runner/__tests__/weaponAttackToHitModifiers.behavior.11.test.ts#L84-L161',
  'src/simulation/runner/phases/movementMines.ts#L1-L774':
    'src/simulation/runner/phases/movementMines.ts#L38-L199',
  'src/simulation/runner/phases/movementMines.ts#L132-L774':
    'src/simulation/runner/phases/movementMines.ts#L108-L199',
  'src/simulation/runner/phases/movementMines.ts#L189-L314':
    'src/simulation/runner/phases/movementMinefieldState.ts#L60-L128',
  'src/simulation/runner/phases/physicalAttack.ts#L212-L223':
    'src/simulation/runner/phases/physicalAttackSelection.ts#L77-L103',
  'src/simulation/runner/phases/physicalAttack.ts#L216-L240':
    'src/simulation/runner/phases/physicalAttackResolution.ts#L126-L130',
  'src/simulation/runner/phases/physicalAttack.ts#L256-L420':
    'src/simulation/runner/phases/physicalAttackInput.ts#L47-L82',
  'src/simulation/runner/phases/physicalAttack.ts#L421-L545':
    'src/simulation/runner/phases/physicalAttackDisplacement.ts#L54-L90',
  'src/simulation/runner/phases/physicalAttack.ts#L448-L605':
    'src/simulation/runner/phases/physicalAttackResolution.ts#L24-L110',
  'src/simulation/runner/phases/physicalAttack.ts#L507-L531':
    'src/simulation/runner/phases/physicalAttackPsrEffects.ts#L19-L123',
  'src/simulation/runner/phases/physicalAttack.ts#L532-L871':
    'src/simulation/runner/phases/physicalAttackSelection.ts#L207-L320',
  'src/simulation/runner/phases/weaponAttack.ts#L1-L1346':
    'src/simulation/runner/phases/weaponAttackToHit.ts#L69-L103',
  'src/simulation/runner/phases/weaponAttack.ts#L1006-L1208':
    'src/simulation/runner/phases/weaponAttackShotContext.ts#L238-L261',
  'src/simulation/runner/phases/weaponAttack.ts#L1044-L1062':
    'src/simulation/runner/phases/weaponAttackModifierPayload.ts#L97-L118',
  'src/simulation/runner/phases/weaponAttack.ts#L1072-L1081':
    'src/simulation/runner/phases/weaponAttackModifierPayload.ts#L97-L118',
  'src/simulation/runner/phases/weaponAttack.ts#L1072-L1082':
    'src/simulation/runner/phases/weaponAttackModifierPayload.ts#L97-L118',
  'src/simulation/runner/phases/weaponAttack.ts#L1178-L1229':
    'src/simulation/runner/phases/weaponAttackShots.ts#L123-L192',
  'src/simulation/runner/phases/weaponAttack.ts#L1212-L1221':
    'src/simulation/runner/phases/weaponAttackHitResolution.helpers.ts#L101-L157',
  'src/simulation/runner/phases/weaponAttack.ts#L1225-L1317':
    'src/simulation/runner/phases/weaponAttackHitResolution.ts#L145-L356',
  'src/simulation/runner/phases/weaponAttack.ts#L1273-L1302':
    'src/simulation/runner/phases/weaponAttackShots.ts#L209-L249',
  'src/simulation/runner/phases/weaponAttack.ts#L141-L166':
    'src/simulation/runner/phases/weaponAttackC3.ts#L51-L68',
  'src/simulation/runner/phases/weaponAttack.ts#L395-L1320':
    'src/simulation/runner/phases/weaponAttackShots.ts#L123-L285',
  'src/simulation/runner/phases/weaponAttack.ts#L395-L475':
    'src/simulation/runner/phases/weaponAttackAMSResolution.ts#L42-L119',
  'src/simulation/runner/phases/weaponAttack.ts#L581-L590':
    'src/simulation/runner/phases/weaponAttackUnit.ts#L24-L85',
  'src/simulation/runner/phases/weaponAttack.ts#L643-L803':
    'src/simulation/runner/phases/weaponAttackShotContext.ts#L101-L261',
  'src/simulation/runner/phases/weaponAttack.ts#L754-L769':
    'src/simulation/runner/phases/weaponAttackContext.ts#L108-L118',
  'src/simulation/runner/phases/weaponAttack.ts#L818-L939':
    'src/simulation/runner/phases/weaponAttackShotContext.ts#L123-L238',
  'src/simulation/runner/phases/weaponAttack.ts#L880-L940':
    'src/simulation/runner/phases/weaponAttackToHit.ts#L25-L103',
  'src/simulation/runner/phases/weaponAttack.ts#L969-L1004':
    'src/simulation/runner/phases/weaponAttackModifierPayload.ts#L97-L118',
  'src/simulation/runner/UnitHydration.ts#L1136-L1141':
    'src/simulation/runner/UnitHydrationAmmo.ts#L61-L69',
  'src/simulation/runner/UnitHydration.ts#L1160-L1184':
    'src/simulation/runner/UnitHydrationCriticalSlotSupport.ts#L153-L216',
  'src/simulation/runner/UnitHydration.ts#L1461-L1551':
    'src/simulation/runner/UnitHydrationElectronics.ts#L288-L312',
  'src/simulation/runner/UnitHydration.ts#L147-L151':
    'src/simulation/runner/UnitHydrationEquipment.ts#L85-L97',
  'src/simulation/runner/UnitHydration.ts#L1498-L1536':
    'src/simulation/runner/UnitHydrationElectronics.ts#L334-L341',
  'src/simulation/runner/UnitHydration.ts#L1609-L1613':
    'src/simulation/runner/UnitHydrationCriticalSlotClassification.ts#L92-L108',
  'src/simulation/runner/UnitHydration.ts#L1654-L1778':
    'src/simulation/runner/UnitHydrationCriticalSlotSupport.ts#L153-L216',
  'src/simulation/runner/UnitHydration.ts#L1686-L1692':
    'src/simulation/runner/UnitHydrationCriticalSlotClassification.ts#L92-L108',
  'src/simulation/runner/UnitHydration.ts#L1776-L1790':
    'src/simulation/runner/UnitHydrationCriticalSlotClassification.ts#L92-L108',
  'src/simulation/runner/UnitHydration.ts#L1832-L1879':
    'src/simulation/runner/UnitHydrationCriticalSlotClassification.ts#L192-L215',
  'src/simulation/runner/UnitHydration.ts#L1843-L2049':
    'src/simulation/runner/UnitHydrationCriticalSlotSupport.ts#L286-L315',
  'src/simulation/runner/UnitHydration.ts#L1878-L1912':
    'src/simulation/runner/UnitHydrationAmmo.ts#L115-L143',
  'src/simulation/runner/UnitHydration.ts#L209-L238':
    'src/simulation/runner/UnitHydrationState.ts#L54-L72',
  'src/simulation/runner/UnitHydration.ts#L2132-L2148':
    'src/simulation/runner/UnitHydrationState.ts#L54-L72',
  'src/simulation/runner/UnitHydration.ts#L2246-L2302':
    'src/simulation/runner/UnitHydrationCatalogLookup.ts#L214-L236',
  'src/simulation/runner/UnitHydration.ts#L2497-L2498':
    'src/simulation/runner/UnitHydrationAmmo.ts#L61-L69',
  'src/simulation/runner/UnitHydration.ts#L296-L316':
    'src/simulation/runner/UnitHydrationState.ts#L52-L79',
  'src/simulation/runner/UnitHydration.ts#L402-L430':
    'src/simulation/runner/UnitHydrationWeapons.ts#L26-L43',
  'src/simulation/runner/UnitHydration.ts#L458-L480':
    'src/simulation/runner/UnitHydrationElectronics.ts#L253-L312',
  'src/types/gameplay/TerrainTypes.ts#L146-L488':
    'src/types/gameplay/TerrainProperties.ts#L9-L424',
  'src/types/gameplay/TerrainTypes.ts#L15-L35':
    'src/types/gameplay/TerrainTypeDefinitions.ts#L7-L25',
  'src/types/gameplay/TerrainTypes.ts#L409-L428':
    'src/types/gameplay/TerrainProperties.ts#L329-L344',
  'src/utils/gameplay/__tests__/battlemechPhysicalCombat.behavior.test.ts#L5349-L5390':
    'src/utils/gameplay/__tests__/battlemechPhysicalCombat.behavior.18.test.ts#L79-L139',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L1354-L1465':
    'src/utils/gameplay/__tests__/criticalHitResolution.11.test.ts#L4-L134',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L1452-L1611':
    'src/utils/gameplay/__tests__/criticalHitResolution.07.test.ts#L43-L103',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L1476-L1519':
    'src/utils/gameplay/__tests__/criticalHitResolution.07.test.ts#L103-L148',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L1521-L1615':
    'src/utils/gameplay/__tests__/criticalHitResolution.07.test.ts#L245-L286',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L1574-L1627':
    'src/utils/gameplay/__tests__/criticalHitResolution.07.test.ts#L195-L236',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L1756-L1875':
    'src/utils/gameplay/__tests__/criticalHitResolution.08.test.ts#L179-L226',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L1808-L1905':
    'src/utils/gameplay/__tests__/criticalHitResolution.08.test.ts#L51-L142',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L1948-L2050':
    'src/utils/gameplay/__tests__/criticalHitResolution.09.test.ts#L88-L168',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L2033-L2090':
    'src/utils/gameplay/__tests__/criticalHitResolution.10.test.ts#L91-L154',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L2121-L2191':
    'src/utils/gameplay/__tests__/criticalHitResolution.09.test.ts#L174-L258',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L2212-L2260':
    'src/utils/gameplay/__tests__/criticalHitResolution.10.test.ts#L4-L43',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L2225-L2286':
    'src/utils/gameplay/__tests__/criticalHitResolution.10.test.ts#L155-L212',
  'src/utils/gameplay/__tests__/criticalHitResolution.test.ts#L692-L789':
    'src/utils/gameplay/__tests__/criticalHitResolution.03.test.ts#L53-L143',
  'src/utils/gameplay/__tests__/damagePipeline.test.ts#L136-L176':
    'src/utils/gameplay/__tests__/damagePipeline.01.fragment.ts#L136-L176',
  'src/utils/gameplay/__tests__/declareAttack.toHitStateHydration.test.ts#L487-L528':
    'src/utils/gameplay/__tests__/declareAttack.toHitStateHydration.02.fragment.ts#L245-L291',
  'src/utils/gameplay/__tests__/electronicWarfare.test.ts#L493-L547':
    'src/utils/gameplay/__tests__/electronicWarfare.03.fragment.ts#L95-L149',
  'src/utils/gameplay/__tests__/environmentalModifiers.test.ts#L424-L649':
    'src/utils/gameplay/__tests__/environmentalModifiers.02.fragment.ts#L237-L248',
  'src/utils/gameplay/__tests__/gameSession.test.ts#L1300-L1429':
    'src/utils/gameplay/__tests__/gameSession.09.fragment.ts#L170-L337',
  'src/utils/gameplay/__tests__/gameSession.test.ts#L213-L250':
    'src/utils/gameplay/__tests__/gameSession.01.fragment.ts#L213-L249',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L1067-L1080':
    'src/utils/gameplay/__tests__/battlemechPhysicalCombat.behavior.18.test.ts#L79-L139',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L1494-L1585':
    'src/utils/gameplay/__tests__/physicalAttacks.05.test.ts#L85-L169',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L1589-L1710':
    'src/utils/gameplay/__tests__/physicalAttacks.05.test.ts#L173-L263',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L1714-L1864':
    'src/utils/gameplay/__tests__/physicalAttacks.06.test.ts#L18-L111',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L1962-L2269':
    'src/utils/gameplay/__tests__/physicalAttacks.07.test.ts#L62-L180',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L2033-L2262':
    'src/utils/gameplay/__tests__/physicalAttacks.07.test.ts#L99-L180',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L2266-L2481':
    'src/utils/gameplay/__tests__/physicalAttacks.08.test.ts#L142-L250',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L5233-L5303':
    'src/utils/gameplay/__tests__/physicalAttacks.20.test.ts#L207-L252',
  'src/utils/gameplay/__tests__/physicalAttacks.test.ts#L846-L5639':
    'src/utils/gameplay/__tests__/physicalAttacks.03.test.ts#L13-L117',
  'src/utils/gameplay/__tests__/spaModifiers.test.ts#L799-L899':
    'src/utils/gameplay/__tests__/spaModifiers.04.fragment.ts#L61-L169',
  'src/utils/gameplay/__tests__/spaModifiers.test.ts#L852-L899':
    'src/utils/gameplay/__tests__/spaModifiers.04.fragment.ts#L115-L169',
  'src/utils/gameplay/__tests__/specialWeaponMechanics.test.ts#L908-L986':
    'src/utils/gameplay/__tests__/specialWeaponMechanics.04.fragment.ts#L173-L348',
  'src/utils/gameplay/__tests__/unitStateExtension.test.ts#L548-L596':
    'src/utils/gameplay/__tests__/unitStateExtension.04.fragment.ts#L216-L249',
  'src/utils/gameplay/__tests__/unitStateExtension.test.ts#L892-L956':
    'src/utils/gameplay/__tests__/unitStateExtension.04.fragment.ts#L216-L279',
  'src/utils/gameplay/__tests__/unitStateExtension.test.ts#L927-L944':
    'src/utils/gameplay/__tests__/unitStateExtension.04.fragment.ts#L251-L266',
  'src/utils/gameplay/gameSessionAttackResolution.ts#L226-L357':
    'src/utils/gameplay/gameSessionAttackResolution.hit.ts#L48-L216',
  'src/utils/gameplay/gameSessionAttackResolution.ts#L256-L474':
    'src/utils/gameplay/gameSessionAttackResolution.damageEvents.ts#L78-L325',
  'src/utils/gameplay/gameSessionCore.ts#L494-L545':
    'src/utils/gameplay/gameSessionCore.attackToHit.ts#L120-L137',
  'src/utils/gameplay/gameSessionCore.ts#L504-L528':
    'src/utils/gameplay/gameSessionCore.attack.ts#L100-L145',
  'src/utils/gameplay/gameSessionCore.ts#L564-L639':
    'src/utils/gameplay/gameSessionCore.attackEvents.ts#L35-L134',
  'src/utils/gameplay/gameSessionCore.ts#L596-L630':
    'src/utils/gameplay/gameSessionCore.attackEvents.ts#L35-L134',
  'src/utils/gameplay/gameSessionCore.ts#L607-L631':
    'src/utils/gameplay/gameSessionCore.attackEvents.ts#L35-L134',
  'src/utils/gameplay/gameSessionCore.ts#L642-L742':
    'src/utils/gameplay/gameSessionCore.ts#L444-L463',
  'src/utils/gameplay/gameSessionCore.ts#L667-L679':
    'src/utils/gameplay/gameSessionCore.ts#L398-L430',
  'src/utils/gameplay/gameSessionHeat.ts#L1082-L1148':
    'src/utils/gameplay/gameSessionHeat.effects.ts#L246-L359',
  'src/utils/gameplay/gameSessionHeat.ts#L1083-L1135':
    'src/utils/gameplay/gameSessionHeat.effects.ts#L246-L359',
  'src/utils/gameplay/gameSessionHeat.ts#L1146-L1163':
    'src/utils/gameplay/gameSessionHeat.criticalEvents.ts#L69-L168',
  'src/utils/gameplay/gameSessionHeat.ts#L345-L1013':
    'src/utils/gameplay/gameSessionHeat.ts#L23-L70',
  'src/utils/gameplay/gameSessionHeat.ts#L657-L1156':
    'src/utils/gameplay/gameSessionHeat.ammoExplosion.ts#L267-L353',
  'src/utils/gameplay/gameSessionHeat.ts#L657-L940':
    'src/utils/gameplay/gameSessionHeat.sources.ts#L136-L266',
  'src/utils/gameplay/gameSessionHeat.ts#L858-L886':
    'src/utils/gameplay/gameSessionHeat.sources.ts#L136-L266',
  'src/utils/gameplay/gameSessionHeat.ts#L892-L909':
    'src/utils/gameplay/gameSessionHeat.sources.ts#L221-L266',
  'src/utils/gameplay/gameSessionPhysical.ts#L360-L1082':
    'src/utils/gameplay/gameSessionPhysicalResolution.ts#L50-L240',
  'src/utils/gameplay/gameSessionPhysical.ts#L431-L770':
    'src/utils/gameplay/gameSessionPhysicalInput.ts#L47-L82',
  'src/utils/gameplay/gameSessionPhysical.ts#L437-L469':
    'src/utils/gameplay/gameSessionPhysical.ts#L105-L220',
  'src/utils/gameplay/gameSessionPhysical.ts#L543-L549':
    'src/utils/gameplay/gameSessionPhysicalSupport.ts#L153-L160',
  'src/utils/gameplay/gameSessionPhysical.ts#L585-L990':
    'src/utils/gameplay/gameSessionPhysical.ts#L105-L220',
  'src/utils/gameplay/gameSessionPhysical.ts#L607-L825':
    'src/utils/gameplay/gameSessionPhysicalResolution.ts#L50-L186',
  'src/utils/gameplay/gameSessionPhysical.ts#L643-L662':
    'src/utils/gameplay/gameSessionPhysicalResolution.ts#L189-L207',
  'src/utils/gameplay/gameSessionPhysical.ts#L945-L1024':
    'src/utils/gameplay/gameSessionPhysicalPsrEvents.ts#L156-L240',
  'src/utils/gameplay/lineOfSight.ts#L1-L825':
    'src/utils/gameplay/lineOfSight.ts#L57-L125',
  'src/utils/gameplay/lineOfSight.ts#L451-L789':
    'src/utils/gameplay/lineOfSight.traceEvaluation.ts#L123-L287',
  'src/utils/gameplay/movement/calculations.ts#L466-L486':
    'src/utils/gameplay/movement/movementStepCost.ts#L116-L134',
  'src/utils/gameplay/movement/reachable.ts#L447-L472':
    'src/utils/gameplay/movement/reachableDestination.ts#L1-L64',
  'src/utils/gameplay/physicalAttacks/damage.ts#L789-L799':
    'src/utils/gameplay/physicalAttacks/missConsequences.ts#L13-L33',
  'src/utils/gameplay/physicalAttacks/eligibility.ts#L221-L233':
    'src/utils/gameplay/physicalAttacks/eligibilityOptionFactory.ts#L40-L52',
  'src/utils/gameplay/physicalAttacks/restrictions.ts#L1249-L1319':
    'src/utils/gameplay/physicalAttacks/restrictionSpecial.ts#L42-L268',
  'src/utils/gameplay/physicalAttacks/restrictions.ts#L331-L339':
    'src/utils/gameplay/physicalAttacks/restrictionBasic.ts#L26-L40',
  'src/utils/gameplay/physicalAttacks/restrictions.ts#L491-L499':
    'src/utils/gameplay/physicalAttacks/restrictionActionValidationHelpers.ts#L210-L217',
  'src/utils/gameplay/physicalAttacks/restrictions.ts#L666-L751':
    'src/utils/gameplay/physicalAttacks/restrictionActionValidationHelpers.ts#L519-L581',
  'src/utils/gameplay/physicalAttacks/restrictions.ts#L783-L791':
    'src/utils/gameplay/physicalAttacks/restrictionChargePush.ts#L144-L153',
  'src/utils/gameplay/physicalAttacks/toHit.ts#L103-L114':
    'src/utils/gameplay/physicalAttacks/toHitValidationCommon.ts#L84-L114',
  'src/utils/gameplay/physicalAttacks/toHit.ts#L178-L1037':
    'src/utils/gameplay/physicalAttacks/toHitOptional.ts#L50-L102',
  'src/utils/gameplay/physicalAttacks/toHit.ts#L178-L454':
    'src/utils/gameplay/physicalAttacks/toHitValidationCommon.ts#L223-L240',
  'src/utils/gameplay/physicalAttacks/toHit.ts#L194-L218':
    'src/utils/gameplay/physicalAttacks/toHitValidationCommon.ts#L386-L400',
  'src/utils/gameplay/physicalAttacks/toHit.ts#L53-L533':
    'src/utils/gameplay/physicalAttacks/toHitBasic.ts#L53-L120',
};

interface IMekStationRemappableSourceRef {
  readonly kind: string;
  readonly url: string;
  readonly sourceVersion: string;
}

export function remapMekStationSourceRefUrl(url: string): string {
  return MEKSTATION_SOURCE_REF_ANCHOR_REMAP[url] ?? url;
}

export function remapMekStationSourceRef<
  TSourceRef extends IMekStationRemappableSourceRef,
>(sourceRef: TSourceRef): TSourceRef {
  if (
    sourceRef.kind !== 'mekstation-deviation' ||
    sourceRef.sourceVersion !== 'MekStation working-tree'
  ) {
    return sourceRef;
  }

  const remappedUrl = remapMekStationSourceRefUrl(sourceRef.url);
  return remappedUrl === sourceRef.url
    ? sourceRef
    : { ...sourceRef, url: remappedUrl };
}

export function remapMekStationSourceRefs<
  TSourceRef extends IMekStationRemappableSourceRef,
>(sourceRefs: readonly TSourceRef[]): readonly TSourceRef[] {
  return sourceRefs.map(remapMekStationSourceRef);
}
