import type { ICombatRequirementSupportEntry } from './CombatValidationRequirementSupport.types';

import { TERRAIN_LOS_SIDE_PATH_UNSUPPORTED_IDS } from './CombatRuleSupport';
import {
  integrated,
  outOfScope,
} from './CombatValidationRequirementSupport.builders';
import {
  PHYSICAL_LEGALITY_GATE_SUPPORT_REFS,
  DISPLACEMENT_DOMINO_SECONDARY_FALLOUT_SUPPORT_REFS,
  DISPLACEMENT_DOMINO_SECONDARY_FALLOUT_OUT_OF_SCOPE_REFS,
  MOVEMENT_RULE_SUPPORT_REFS,
  MOVEMENT_ENHANCEMENT_SUPPORT_REFS,
  TERRAIN_ENVIRONMENT_SUPPORT_REFS,
  TERRAIN_TYPE_MOVEMENT_SUPPORT_REFS,
  TERRAIN_TYPE_LOS_SUPPORT_REFS,
  TERRAIN_TYPE_ATTACK_MODIFIER_SUPPORT_REFS,
  TERRAIN_TYPE_HEAT_SUPPORT_REFS,
  TERRAIN_TYPE_PSR_SUPPORT_REFS,
  PILOT_SKILL_SUPPORT_REFS,
  PILOT_ABILITY_SUPPORT_REFS,
  CANONICAL_SPA_SUPPORT_REFS,
  MECH_QUIRK_SUPPORT_REFS,
  PILOT_MODIFIER_RESOLVER_SUPPORT_REFS,
  HEAT_GENERATION_SUPPORT_REFS,
  HEAT_DISSIPATION_SUPPORT_REFS,
  HEAT_LIFECYCLE_SUPPORT_REFS,
  HEAT_DRIVEN_MODIFIER_SUPPORT_REFS,
  RANGE_BRACKET_SUPPORT_REFS,
  ATTACK_INVALIDATION_REASON_SUPPORT_REFS,
  INVALID_TARGET_STATE_SUPPORT_REFS,
  ATTACK_INVALIDATION_SIDE_EFFECT_SUPPORT_REFS,
  TO_HIT_CORE_MODIFIER_SUPPORT_REFS,
  TO_HIT_ADVANCED_MODIFIER_SUPPORT_REFS,
  DAMAGE_RESOLUTION_SUPPORT_REFS,
  DESTRUCTION_CAUSE_SUPPORT_REFS,
  CRITICAL_COMPONENT_SUPPORT_REFS,
  CRITICAL_SLOT_EFFECT_SUPPORT_REFS,
  PILOT_DAMAGE_SUPPORT_REFS,
  PSR_RESOLUTION_SUPPORT_REFS,
  PSR_TRIGGER_SUPPORT_REFS,
  CRITICAL_SLOT_HYDRATION_SUPPORT_REFS,
  RUNNER_INTERACTIVE_PARITY_SUPPORT_REFS,
  BATTLEMECH_EVENT_SUPPORT_REFS,
  NON_BATTLEMECH_EVENT_SCOPE_SUPPORT_REFS,
} from './CombatValidationRequirementSupport.supportRefLists';
import { MEGAMEK_EJECTION_LIFECYCLE_SOURCE_REFS } from './CombatValidationRequirementSupport.types';

export const BATTLEMECH_VALIDATION_REQUIREMENT_CATALOG_MOVEMENT_SUPPORT = {
  'official-ranged-weapons': integrated(
    'official-ranged-weapons',
    'Catalog contracts enumerate every official ranged weapon and require non-synthetic AI weapon mapping',
    [
      'validationScope.knownLimitationsAndScope.battlemech-official-catalog-scope',
    ],
  ),
  'official-physical-weapons': integrated(
    'official-physical-weapons',
    'Catalog contracts enumerate official physical weapons, require construction definitions to match the official physical catalog, partition every row into either standalone runtime attacks or modifier-only equipment, and keep claws/talons out of selectable attack types',
    [
      'validationScope.knownLimitationsAndScope.battlemech-official-catalog-scope',
      'featureSupport.physicalWeapons.hatchet',
      'featureSupport.physicalWeapons.sword',
      'featureSupport.physicalWeapons.mace',
      'featureSupport.physicalWeapons.lance',
      'featureSupport.physicalWeapons.retractable-blade',
      'featureSupport.physicalWeapons.claws',
      'featureSupport.physicalWeapons.flail',
      'featureSupport.physicalWeapons.talons',
      'featureSupport.physicalWeapons.wrecking-ball',
    ],
  ),
  'official-ammo': integrated(
    'official-ammo',
    'Catalog contracts enumerate official ammo entries, require compatible rows to become consumable bins, close the generic standard/advanced missing-compatible bucket, split every remaining empty-compatible row through the ammo support map, and prove RAC/10 and RAC/20 ammo rows stay non-consumable without unofficial weapon, alias, ammo-id, or static-BV fallback',
    [
      'featureSupport.ammunitionCompatibility.battlemech-compatible-ammo',
      'featureSupport.ammunitionCompatibility.duplicate-runtime-id',
      'featureSupport.ammunitionCompatibility.battlemech-ammo-missing-compatible-weapon-refs',
      'featureSupport.ammunitionCompatibility.experimental-empty-compatible-row',
      'featureSupport.ammunitionCompatibility.non-battlemech-aerospace-capital-ammo',
      'featureSupport.ammunitionCompatibility.non-battlemech-battle-armor',
      'featureSupport.ammunitionCompatibility.non-battlemech-protomech',
      'featureSupport.ammunitionCompatibility.unsupported-aquatic-torpedo-ammo',
      'featureSupport.ammunitionCompatibility.unsupported-artillery-ammo',
      'featureSupport.ammunitionCompatibility.unsupported-rotary-ac-10-20-ammo',
      'featureSupport.ammunitionCompatibility.unofficial-empty-compatible-row',
      'validationScope.knownLimitationsAndScope.battlemech-official-catalog-scope',
      'validationScope.knownLimitationsAndScope.non-battlemech-ammo-scope',
    ],
  ),
  'weapon-stat-mapping': integrated(
    'weapon-stat-mapping',
    'Weapon catalog contracts and runner rule maps cover damage, heat, range, minimum range, ammo, and hydrated mount conversion',
    [
      'ruleSupport.heatRules.weapon-heat',
      'ruleSupport.rangeBrackets.short',
      'ruleSupport.toHitModifiers.minimum-range',
    ],
  ),
  'special-weapon-families': integrated(
    'special-weapon-families',
    'Special weapon family support catalogs UAC, RAC, LB-X, Streak, MML, NARC, AMS, TAG, Artemis, and plasma-cannon responsibilities, including source-backed compact official IS/Clan launcher id resolution, whole-catalog non-torpedo Artemis FCS allocation audit coverage, active-probe/BAP/CEWS equipment hydration, ECM suite mode import and runner Artemis suppression, BattleMech stealth armor plus ECM critical-damage lifecycle removal of stealth suppression, carrier-attached iNarc pod target identity and selected Brush-Off removal, and explicit out-of-scope accounting for producer-side C3 authoring, AMS bay authoring, optional multi-use AMS authoring, and plasma-cannon non-Mek/terrain/building side paths',
    [
      'featureSupport.specialWeaponFamilies.ultra-ac',
      'featureSupport.specialWeaponFamilies.rotary-ac',
      'featureSupport.specialWeaponFamilies.lb-x-ac',
      'featureSupport.specialWeaponFamilies.streak-srm',
      'featureSupport.specialWeaponFamilies.narc',
      'featureSupport.specialWeaponFamilies.ams',
      'featureSupport.specialWeaponFamilies.tag',
      'featureSupport.specialWeaponFamilies.artemis',
      'featureSupport.specialWeaponFamilies.plasma-cannon',
      'featureSupport.specialWeaponMechanics.mml-variable-damage',
      'featureSupport.specialWeaponMechanics.mml-srm-lrm-ammo-compatibility',
      'featureSupport.specialWeaponMechanics.narc-marker-attachment',
      'featureSupport.specialWeaponMechanics.narc-marker-lifecycle-events',
      'featureSupport.specialWeaponMechanics.inarc-variant-ammo-attachment',
      'featureSupport.specialWeaponMechanics.inarc-ecm-attacker-flight-path-suppression',
      'featureSupport.specialWeaponMechanics.inarc-ecm-c3-disruption',
      'featureSupport.specialWeaponMechanics.inarc-nemesis-redirect',
      'featureSupport.specialWeaponMechanics.inarc-homing-marker-attachment',
      'featureSupport.specialWeaponMechanics.inarc-homing-cluster-modifier',
      'featureSupport.specialWeaponMechanics.inarc-homing-to-hit-modifier',
      'featureSupport.specialWeaponMechanics.inarc-haywire-to-hit-modifier',
      'featureSupport.specialWeaponMechanics.inarc-pod-variants',
      'featureSupport.specialWeaponMechanics.inarc-pod-event-replay-lifecycle',
      'featureSupport.specialWeaponMechanics.inarc-pod-target-identity-lifecycle',
      'featureSupport.specialWeaponMechanics.inarc-pod-target-option-deduplication',
      'featureSupport.specialWeaponMechanics.inarc-pod-brush-off-target-selection',
      'featureSupport.specialWeaponMechanics.inarc-pod-helper-removal-lifecycle',
      'featureSupport.specialWeaponMechanics.inarc-pod-turn-reset-lifecycle',
      'featureSupport.specialWeaponMechanics.inarc-pod-brush-off-removal-lifecycle',
      'featureSupport.specialWeaponMechanics.inarc-pod-object-lifecycle',
      'featureSupport.specialWeaponMechanics.inarc-ecm-sensor-effects',
      'featureSupport.specialWeaponMechanics.inarc-producer-c3-authoring',
      'featureSupport.specialWeaponMechanics.inarc-explosive-ammo-compatibility',
      'featureSupport.specialWeaponMechanics.ams-automatic-interception-assignment',
      'featureSupport.specialWeaponMechanics.ams-projectile-reduction',
      'featureSupport.specialWeaponMechanics.ams-streak-cluster-parity',
      'featureSupport.specialWeaponMechanics.ams-single-missile-parity',
      'featureSupport.specialWeaponMechanics.ams-ammo-consumption',
      'featureSupport.specialWeaponMechanics.ams-interception-events',
      'featureSupport.specialWeaponMechanics.ams-bay-authoring',
      'featureSupport.specialWeaponMechanics.ams-optional-multi-use-authoring',
      'featureSupport.specialWeaponMechanics.tag-designation-hit',
      'featureSupport.specialWeaponMechanics.tag-marker-lifecycle-events',
      'featureSupport.specialWeaponMechanics.tag-semi-guided-to-hit',
      'featureSupport.specialWeaponMechanics.tag-intent-wire-state-replay',
      'featureSupport.specialWeaponMechanics.active-probe-counter-hydration',
      'featureSupport.specialWeaponMechanics.artemis-cluster-modifier',
      'featureSupport.specialWeaponMechanics.artemis-fcs-critical-lifecycle',
      'featureSupport.specialWeaponMechanics.artemis-link-network-lifecycle',
      'featureSupport.specialWeaponMechanics.artemis-ambiguous-fcs-allocation-authoring',
      'featureSupport.specialWeaponMechanics.artemis-active-probe-mode-authoring',
      'featureSupport.specialWeaponMechanics.artemis-ew-mode-authoring',
      'featureSupport.specialWeaponMechanics.artemis-stealth-mode-damage-lifecycle',
      'featureSupport.specialWeaponMechanics.artemis-ecm-suppression',
      'featureSupport.specialWeaponMechanics.artemis-ecm-suite-hydration',
      'featureSupport.specialWeaponMechanics.active-probe-critical-lifecycle',
      'featureSupport.specialWeaponMechanics.artemis-stealth-suppression',
      'featureSupport.specialWeaponMechanics.plasma-cannon-battlemech-target-heat',
      'featureSupport.specialWeaponMechanics.plasma-cannon-battlemech-heat-phase-pending-bucket',
    ],
  ),
  'fallback-prevention': integrated(
    'fallback-prevention',
    'Catalog contracts reject static weapon database drift and synthetic Medium Laser fallback hiding hydration failures',
    [
      'validationScope.knownLimitationsAndScope.static-weapon-database-subset',
      'validationScope.knownLimitationsAndScope.synthetic-medium-laser-fallback-ban',
    ],
  ),
  'damage-string-hazards': integrated(
    'damage-string-hazards',
    'Catalog contracts pin variable damage strings such as MML 1-2/missile so they do not collapse to zero damage; MML firing modes split SRM/LRM damage and consume distinct SRM/LRM ammo-bin families',
    [
      'validationScope.knownLimitationsAndScope.variable-damage-string-guard',
      'featureSupport.specialWeaponFamilies.mml',
      'featureSupport.specialWeaponMechanics.mml-variable-damage',
      'featureSupport.specialWeaponMechanics.mml-srm-lrm-mode-damage',
      'featureSupport.specialWeaponMechanics.mml-srm-lrm-ammo-compatibility',
    ],
  ),
  'movement-actions': integrated(
    'movement-actions',
    'Action and movement rule maps cover walk, run, source-backed TacOps sprint and evade, jump, same-hex facing rotation, stand/careful-stand, hull-down, source-backed voluntary go-prone including non-Mek/already-prone/stuck legality, hull-down zero-MP posture transition, represented BattleMech swarmer dislodgement, enemy-occupied-start follow-up blocking, explicit infernoBurning wash-off, source-backed MASC/Supercharger activation, named MASC/Supercharger failure trigger stamping, prone state, source-backed torso-twist exposure with replayed secondaryFacing consumption, local shell-row exclusions, sprint command/MovementType/wire/P2P/runner movement/normal-engine heat/spotter/ranged-to-hit state, and enemy-occupied-start go-prone follow-up rejection',
    [
      'actions.composerMovementModes.movement.walk',
      'actions.composerMovementModes.movement.run',
      'actions.composerMovementModes.movement.sprint',
      'actions.tacticalCommands.movement.evade',
      'actions.composerMovementModes.movement.jump',
      'actions.tacticalCommands.movement.stand',
      'actions.tacticalCommands.movement.carefulStand',
      'actions.tacticalCommands.movement.hullDown',
      'actions.tacticalCommands.movement.goProne',
      'actions.tacticalCommands.movement.activate-masc',
      'actions.tacticalCommands.movement.activate-supercharger',
      'actions.gameIntents.activateMovementEnhancement',
      'actions.wireIntents.ActivateMovementEnhancement',
      'actions.p2pIntents.activateMovementEnhancement',
      'actions.tacticalCommands.facing.rotate-left',
      'actions.tacticalCommands.facing.rotate-right',
      'actions.tacticalCommands.facing.torso-twist',
      'actions.gameIntents.torsoTwist',
      'actions.wireIntents.TorsoTwist',
      'actions.p2pIntents.torsoTwist',
      'ruleSupport.movementEnhancements.masc-side-paths',
      'ruleSupport.movementEnhancements.supercharger-side-paths',
      ...MOVEMENT_RULE_SUPPORT_REFS,
    ],
  ),
  'movement-validation': integrated(
    'movement-validation',
    'Movement rule and terrain type matrices cover MP cost, heat MP penalties, terrain blocking, elevation, and occupancy',
    [
      'ruleSupport.movementRules.occupancy',
      'ruleSupport.movementRules.elevation',
      'ruleSupport.movementRules.heat-mp-penalty',
      'ruleSupport.terrainEnvironment.terrain-movement-costs',
      'ruleSupport.terrainEnvironment.water-ground-disallow',
    ],
  ),
  'movement-enhancements': integrated(
    'movement-enhancements',
    'Movement enhancement support catalogs integrated core MASC and Supercharger active-run/sprint, activation, named failure trigger stamping, standard plus alternate_masc and alternate_masc_enhanced failure-PSR target tables, Edge-reroll, failure-damage, prior-use lifecycle behavior, represented BattleMech MASC/Supercharger side-path accounting rows, source-backed active TSM movement validation, source-backed Partial Wing jump MP/heat validation, and split non-BattleMech Supercharger support-unit roll adjustment plus vehicle motive-damage branches to an out-of-scope support row',
    MOVEMENT_ENHANCEMENT_SUPPORT_REFS,
  ),
} satisfies Record<string, ICombatRequirementSupportEntry>;
