/**
 * BlkExportServiceCore.writers Tests
 *
 * Tier 1 invariant tests for the BLK section writers. The end-to-end behaviour
 * of these helpers is already exercised through `BlkExportService.test.ts` at
 * the service level, but the writers and the `tag()` helper are also called
 * directly elsewhere in the conversion pipeline. These tests pin down the
 * exact serialisation contract: tag layout, license-header line set, and the
 * location grouping + emission order for each chassis kind.
 */

import type { AerospaceState } from '@/stores/aerospaceState';
import type { BattleArmorState } from '@/stores/battleArmorState';
import type { ProtoMechState } from '@/stores/protoMechState';
import type { VehicleState } from '@/stores/vehicleState';

import { AerospaceLocation } from '@/types/construction/UnitLocation';

import {
  tag,
  writeAerospaceEquipment,
  writeBattleArmorEquipment,
  writeLicenseHeader,
  writeProtoMechEquipment,
  writeVehicleEquipment,
} from '../BlkExportServiceCore.writers';

describe('BlkExportServiceCore.writers', () => {
  // ============================================================================
  // tag() — primitive used everywhere; must produce the exact 3-line shape
  // ============================================================================
  describe('tag()', () => {
    it('wraps the value in <name>...</name> with the value on its own line', () => {
      expect(tag('Tonnage', '40')).toBe('<Tonnage>\n40\n</Tonnage>');
    });

    it('preserves multiline values (e.g. armor blocks) exactly as-is', () => {
      expect(tag('Armor', '10\n10\n10\n10')).toBe(
        '<Armor>\n10\n10\n10\n10\n</Armor>',
      );
    });

    it('preserves spaces in tag names', () => {
      expect(tag('Front Equipment', 'PPC\nMedium Laser')).toBe(
        '<Front Equipment>\nPPC\nMedium Laser\n</Front Equipment>',
      );
    });
  });

  // ============================================================================
  // writeLicenseHeader() — must emit the BLK-style "#"-prefixed preamble
  // ============================================================================
  describe('writeLicenseHeader()', () => {
    it('emits the Creative Commons license preamble', () => {
      const lines: string[] = [];
      writeLicenseHeader(lines);
      const text = lines.join('\n');
      expect(text).toContain('CC BY-NC-SA 4.0');
      expect(text).toContain(
        'https://creativecommons.org/licenses/by-nc-sa/4.0/',
      );
    });

    it('uses BLK-style "#" comment prefix (no trailing space, unlike MTF)', () => {
      const lines: string[] = [];
      writeLicenseHeader(lines);
      // BLK comments have no space after `#` (per BlkExportServiceCore.writers.ts)
      expect(lines[0].startsWith('#MegaMek Data')).toBe(true);
    });

    it('emits the "Generated by MekStation" stamp', () => {
      const lines: string[] = [];
      writeLicenseHeader(lines);
      const text = lines.join('\n');
      expect(text).toContain('Generated by MekStation');
    });

    it('terminates with a blank line so the next field starts cleanly', () => {
      const lines: string[] = [];
      writeLicenseHeader(lines);
      expect(lines[lines.length - 1]).toBe('');
    });
  });

  // ============================================================================
  // writeVehicleEquipment() — groups by location, fixed order, isTurret override
  // ============================================================================
  describe('writeVehicleEquipment()', () => {
    it('emits Front/Left/Right/Rear/Turret/Body sections in canonical order', () => {
      const unit = {
        equipment: [
          { name: 'PPC', location: 'Body', isTurretMounted: false },
          { name: 'AC/5', location: 'Front', isTurretMounted: false },
          { name: 'Medium Laser', location: 'Rear', isTurretMounted: false },
          { name: 'SRM 6', location: 'Right', isTurretMounted: false },
          {
            name: 'Large Laser',
            location: 'Front',
            isTurretMounted: true,
          },
        ],
      } as unknown as VehicleState;

      const lines: string[] = [];
      writeVehicleEquipment(lines, unit);
      const text = lines.join('\n');

      // All five groups present
      expect(text).toContain('<Front Equipment>');
      expect(text).toContain('<Right Equipment>');
      expect(text).toContain('<Rear Equipment>');
      expect(text).toContain('<Turret Equipment>');
      expect(text).toContain('<Body Equipment>');

      // Turret-mounted weapon goes to Turret regardless of stored location
      const frontIdx = text.indexOf('<Front Equipment>');
      const turretIdx = text.indexOf('<Turret Equipment>');
      expect(text.substring(frontIdx, turretIdx)).not.toContain('Large Laser');
      expect(text.substring(turretIdx)).toContain('Large Laser');

      // Front comes before Rear comes before Body
      expect(text.indexOf('<Front Equipment>')).toBeLessThan(
        text.indexOf('<Rear Equipment>'),
      );
      expect(text.indexOf('<Rear Equipment>')).toBeLessThan(
        text.indexOf('<Body Equipment>'),
      );
    });

    it('emits no equipment tags when unit has no equipment', () => {
      const unit = { equipment: [] } as unknown as VehicleState;
      const lines: string[] = [];
      writeVehicleEquipment(lines, unit);
      expect(lines).toHaveLength(0);
    });

    it('groups multiple weapons in the same location into a single tag block', () => {
      const unit = {
        equipment: [
          { name: 'Medium Laser', location: 'Front', isTurretMounted: false },
          { name: 'Small Laser', location: 'Front', isTurretMounted: false },
        ],
      } as unknown as VehicleState;
      const lines: string[] = [];
      writeVehicleEquipment(lines, unit);
      const text = lines.join('\n');
      // Only one Front Equipment tag pair
      expect(text.match(/<Front Equipment>/g) || []).toHaveLength(1);
      expect(text).toContain('Medium Laser\nSmall Laser');
    });
  });

  // ============================================================================
  // writeAerospaceEquipment() — Nose/Left Wing/Right Wing/Aft order
  // ============================================================================
  describe('writeAerospaceEquipment()', () => {
    it('groups equipment into the four aerospace arcs', () => {
      const unit = {
        equipment: [
          { name: 'PPC', location: AerospaceLocation.NOSE },
          { name: 'Medium Laser', location: AerospaceLocation.LEFT_WING },
          { name: 'Medium Laser', location: AerospaceLocation.RIGHT_WING },
          { name: 'Small Laser', location: AerospaceLocation.AFT },
        ],
      } as unknown as AerospaceState;

      const lines: string[] = [];
      writeAerospaceEquipment(lines, unit);
      const text = lines.join('\n');

      expect(text).toContain('<Nose Equipment>');
      expect(text).toContain('<Left Wing Equipment>');
      expect(text).toContain('<Right Wing Equipment>');
      expect(text).toContain('<Aft Equipment>');

      // Order: Nose -> LW -> RW -> Aft
      expect(text.indexOf('<Nose Equipment>')).toBeLessThan(
        text.indexOf('<Left Wing Equipment>'),
      );
      expect(text.indexOf('<Left Wing Equipment>')).toBeLessThan(
        text.indexOf('<Right Wing Equipment>'),
      );
      expect(text.indexOf('<Right Wing Equipment>')).toBeLessThan(
        text.indexOf('<Aft Equipment>'),
      );
    });

    it('emits no tags for an empty equipment list', () => {
      const unit = { equipment: [] } as unknown as AerospaceState;
      const lines: string[] = [];
      writeAerospaceEquipment(lines, unit);
      expect(lines).toHaveLength(0);
    });
  });

  // ============================================================================
  // writeBattleArmorEquipment() — single Squad Equipment tag block
  // ============================================================================
  describe('writeBattleArmorEquipment()', () => {
    it('emits a single Squad Equipment tag containing all weapon names', () => {
      const unit = {
        equipment: [
          { name: 'Small Laser' },
          { name: 'Medium Laser' },
          { name: 'Anti-Personnel Weapon Mount' },
        ],
      } as unknown as BattleArmorState;

      const lines: string[] = [];
      writeBattleArmorEquipment(lines, unit);
      const text = lines.join('\n');

      expect(text).toContain('<Squad Equipment>');
      expect(text).toContain('</Squad Equipment>');
      expect(text).toContain(
        'Small Laser\nMedium Laser\nAnti-Personnel Weapon Mount',
      );
    });

    it('emits no tag when the squad has no equipment', () => {
      const unit = { equipment: [] } as unknown as BattleArmorState;
      const lines: string[] = [];
      writeBattleArmorEquipment(lines, unit);
      expect(lines).toHaveLength(0);
    });

    it('is robust to undefined equipment array', () => {
      const unit = { equipment: undefined } as unknown as BattleArmorState;
      const lines: string[] = [];
      writeBattleArmorEquipment(lines, unit);
      expect(lines).toHaveLength(0);
    });
  });

  // ============================================================================
  // writeProtoMechEquipment() — Head/Torso/Main Gun/LA/RA/Legs order
  // ============================================================================
  describe('writeProtoMechEquipment()', () => {
    it('groups equipment by location and emits in the canonical order', () => {
      const unit = {
        equipment: [
          { name: 'ER Large Laser', location: 'Main Gun' },
          { name: 'Small Laser', location: 'Torso' },
          { name: 'Sensors', location: 'Head' },
        ],
      } as unknown as ProtoMechState;

      const lines: string[] = [];
      writeProtoMechEquipment(lines, unit);
      const text = lines.join('\n');

      // Order: Head < Torso < Main Gun
      expect(text.indexOf('<Head Equipment>')).toBeLessThan(
        text.indexOf('<Torso Equipment>'),
      );
      expect(text.indexOf('<Torso Equipment>')).toBeLessThan(
        text.indexOf('<Main Gun Equipment>'),
      );
    });

    it('falls back to Torso when an equipment entry lacks a location', () => {
      const unit = {
        equipment: [{ name: 'Small Laser' }],
      } as unknown as ProtoMechState;
      const lines: string[] = [];
      writeProtoMechEquipment(lines, unit);
      const text = lines.join('\n');
      expect(text).toContain('<Torso Equipment>');
      expect(text).toContain('Small Laser');
    });

    it('emits no tags for an empty equipment list', () => {
      const unit = { equipment: [] } as unknown as ProtoMechState;
      const lines: string[] = [];
      writeProtoMechEquipment(lines, unit);
      expect(lines).toHaveLength(0);
    });
  });
});
