import type { IBattle } from '@/components/simulation-viewer/pages/EncounterHistory';

export const MOCK_BATTLES: IBattle[] = [
  {
    id: 'battle-1',
    missionId: 'mission-1',
    missionName: 'Operation Bulldog',
    timestamp: '2025-06-15T10:00:00Z',
    duration: 420,
    outcome: 'victory',
    forces: {
      player: {
        units: [
          {
            id: 'u1',
            name: 'Atlas AS7-D',
            pilot: 'Natasha Kerensky',
            status: 'operational',
          },
          {
            id: 'u2',
            name: 'Marauder MAD-3R',
            pilot: 'Kai Allard-Liao',
            status: 'damaged',
          },
        ],
        totalBV: 5200,
      },
      enemy: {
        units: [
          {
            id: 'e1',
            name: 'Timber Wolf Prime',
            pilot: 'Star Captain Vlad',
            status: 'destroyed',
          },
          {
            id: 'e2',
            name: 'Dire Wolf Prime',
            pilot: 'Star Colonel Ward',
            status: 'damaged',
          },
        ],
        totalBV: 6100,
      },
    },
    damageMatrix: {
      attackers: ['u1', 'u2'],
      targets: ['e1', 'e2'],
      cells: [
        { attackerId: 'u1', targetId: 'e1', damage: 85 },
        { attackerId: 'u1', targetId: 'e2', damage: 40 },
        { attackerId: 'u2', targetId: 'e1', damage: 55 },
        { attackerId: 'u2', targetId: 'e2', damage: 20 },
      ],
    },
    keyMoments: [
      {
        id: 'km1',
        turn: 3,
        phase: 'Weapon Attack',
        tier: 'critical',
        type: 'headshot',
        description: 'Atlas headshot on Timber Wolf',
        involvedUnits: ['u1', 'e1'],
      },
      {
        id: 'km2',
        turn: 5,
        phase: 'Physical Attack',
        tier: 'major',
        type: 'fall',
        description: 'Dire Wolf falls after leg damage',
        involvedUnits: ['e2'],
      },
    ],
    events: [
      {
        id: 'ev1',
        turn: 1,
        phase: 'Movement',
        timestamp: 1,
        type: 'movement',
        description: 'Atlas advances to hex 0505',
        involvedUnits: ['u1'],
      },
      {
        id: 'ev2',
        turn: 1,
        phase: 'Weapon Attack',
        timestamp: 2,
        type: 'attack',
        description: 'Atlas fires AC/20 at Timber Wolf',
        involvedUnits: ['u1', 'e1'],
      },
      {
        id: 'ev3',
        turn: 2,
        phase: 'Movement',
        timestamp: 3,
        type: 'movement',
        description: 'Marauder flanks to hex 0607',
        involvedUnits: ['u2'],
      },
      {
        id: 'ev4',
        turn: 2,
        phase: 'Weapon Attack',
        timestamp: 4,
        type: 'attack',
        description: 'Marauder fires PPCs at Dire Wolf',
        involvedUnits: ['u2', 'e2'],
      },
      {
        id: 'ev5',
        turn: 3,
        phase: 'Weapon Attack',
        timestamp: 5,
        type: 'attack',
        description: 'Atlas headshot on Timber Wolf',
        involvedUnits: ['u1', 'e1'],
      },
      {
        id: 'ev6',
        turn: 3,
        phase: 'Damage',
        timestamp: 6,
        type: 'damage',
        description: 'Timber Wolf destroyed — head destroyed',
        involvedUnits: ['e1'],
      },
      {
        id: 'ev7',
        turn: 4,
        phase: 'Movement',
        timestamp: 7,
        type: 'movement',
        description: 'Dire Wolf attempts retreat',
        involvedUnits: ['e2'],
      },
      {
        id: 'ev8',
        turn: 5,
        phase: 'Physical Attack',
        timestamp: 8,
        type: 'damage',
        description: 'Dire Wolf falls after leg damage',
        involvedUnits: ['e2'],
      },
    ],
    stats: { totalKills: 1, totalDamage: 200, unitsLost: 0 },
  },
  {
    id: 'battle-2',
    missionId: 'mission-1',
    missionName: 'Operation Bulldog',
    timestamp: '2025-06-16T14:00:00Z',
    duration: 300,
    outcome: 'victory',
    forces: {
      player: {
        units: [
          {
            id: 'u3',
            name: 'Hunchback HBK-4G',
            pilot: 'Aidan Pryde',
            status: 'operational',
          },
        ],
        totalBV: 2800,
      },
      enemy: {
        units: [
          {
            id: 'e3',
            name: 'Stormcrow Prime',
            pilot: 'Star Commander Trent',
            status: 'destroyed',
          },
        ],
        totalBV: 3100,
      },
    },
    damageMatrix: {
      attackers: ['u3'],
      targets: ['e3'],
      cells: [{ attackerId: 'u3', targetId: 'e3', damage: 120 }],
    },
    keyMoments: [
      {
        id: 'km3',
        turn: 4,
        phase: 'Weapon Attack',
        tier: 'major',
        type: 'kill',
        description: 'Hunchback destroys Stormcrow with AC/20',
        involvedUnits: ['u3', 'e3'],
      },
    ],
    events: [
      {
        id: 'ev9',
        turn: 1,
        phase: 'Movement',
        timestamp: 1,
        type: 'movement',
        description: 'Hunchback takes position',
        involvedUnits: ['u3'],
      },
      {
        id: 'ev10',
        turn: 2,
        phase: 'Weapon Attack',
        timestamp: 2,
        type: 'attack',
        description: 'Hunchback fires AC/20',
        involvedUnits: ['u3', 'e3'],
      },
      {
        id: 'ev11',
        turn: 3,
        phase: 'Movement',
        timestamp: 3,
        type: 'movement',
        description: 'Stormcrow closes range',
        involvedUnits: ['e3'],
      },
      {
        id: 'ev12',
        turn: 4,
        phase: 'Weapon Attack',
        timestamp: 4,
        type: 'attack',
        description: 'Hunchback destroys Stormcrow',
        involvedUnits: ['u3', 'e3'],
      },
    ],
    stats: { totalKills: 1, totalDamage: 120, unitsLost: 0 },
  },
  {
    id: 'battle-3',
    missionId: 'mission-2',
    missionName: 'Garrison Duty',
    timestamp: '2025-06-20T08:00:00Z',
    duration: 600,
    outcome: 'defeat',
    forces: {
      player: {
        units: [
          {
            id: 'u4',
            name: 'Locust LCT-1V',
            pilot: 'MechWarrior Doe',
            status: 'destroyed',
          },
        ],
        totalBV: 800,
      },
      enemy: {
        units: [
          {
            id: 'e4',
            name: 'Mad Cat Mk II',
            pilot: 'Galaxy Commander Pryde',
            status: 'operational',
          },
        ],
        totalBV: 4500,
      },
    },
    damageMatrix: {
      attackers: ['u4', 'e4'],
      targets: ['u4', 'e4'],
      cells: [
        { attackerId: 'u4', targetId: 'e4', damage: 10 },
        { attackerId: 'e4', targetId: 'u4', damage: 150 },
      ],
    },
    keyMoments: [
      {
        id: 'km4',
        turn: 2,
        phase: 'Weapon Attack',
        tier: 'critical',
        type: 'ammo-explosion',
        description: 'Locust ammo explosion',
        involvedUnits: ['u4'],
      },
    ],
    events: [
      {
        id: 'ev13',
        turn: 1,
        phase: 'Movement',
        timestamp: 1,
        type: 'movement',
        description: 'Locust scouts ahead',
        involvedUnits: ['u4'],
      },
      {
        id: 'ev14',
        turn: 2,
        phase: 'Weapon Attack',
        timestamp: 2,
        type: 'attack',
        description: 'Mad Cat fires alpha strike',
        involvedUnits: ['e4', 'u4'],
      },
      {
        id: 'ev15',
        turn: 2,
        phase: 'Damage',
        timestamp: 3,
        type: 'damage',
        description: 'Locust ammo explosion — destroyed',
        involvedUnits: ['u4'],
      },
    ],
    stats: { totalKills: 0, totalDamage: 10, unitsLost: 1 },
  },
];
