/**
 * AI System Type Definitions
 * Interfaces for bot behavior, movement, and weapon handling.
 */

import type {
  VehicleLocation,
  VTOLLocation,
} from '@/types/construction/UnitLocation';

import {
  IHexCoordinate,
  Facing,
  FiringArc,
  MovementType,
} from '@/types/gameplay';

import type { AITierName } from './AITierRegistry';

// =============================================================================
// Bot Behavior
// =============================================================================

/**
 * Retreat edge direction for bot behavior.
 */
export type RetreatEdge =
  | 'nearest'
  | 'north'
  | 'south'
  | 'east'
  | 'west'
  | 'none';

/**
 * Bot behavior settings (adapted from MekHQ's BehaviorSettings).
 * Controls when and how the bot retreats.
 */
export interface IBotBehavior {
  /**
   * Health percentage threshold to trigger retreat (0-1).
   * Default: 0.3 (retreat at 30% health)
   */
  readonly retreatThreshold: number;

  /**
   * Which map edge to retreat toward.
   * Default: 'nearest'
   */
  readonly retreatEdge: RetreatEdge;

  /**
   * Per `improve-bot-basic-combat-competence` task 1.1: heat ceiling
   * the bot tries to stay at or below when picking a fire list.
   * Above this value the bot drops the lowest damage-per-heat weapon
   * from the candidate list until projected heat fits.
   *
   * Default: 13 (corresponds to the +1 to-hit canonical heat threshold;
   * past it the bot starts taking penalties). Tuning per-difficulty
   * profiles can override this without recompiling the AI.
   */
  readonly safeHeatThreshold: number;

  /**
   * Opt-in tactical posture rule for source-backed voluntary go-prone
   * movement. When enabled, `BotPlayer` may choose a same-hex `goProne`
   * movement step instead of returning no movement when a standing unit has
   * no non-stationary legal destinations. Default/variant presets leave this
   * unset so existing AI traces remain unchanged.
   */
  readonly voluntaryGoProneWhenStationary?: boolean;

  /**
   * Per `add-ai-terrain-aware-movement` design D3: the AI difficulty tier
   * this bot plays at. The tier name keys into the AI Difficulty Tier
   * Registry (`AITierRegistry.ts`), which supplies the movement-scoring
   * parameters (pathfinder enable flag + cover / LOS-denial / terrain-cost
   * weights).
   *
   * Optional for backward compatibility: when absent, the bot resolves to
   * the `Regular` tier, which runs the legacy straight-line move scorer
   * byte-for-byte. Every existing bot, test fixture, and the swarm harness
   * keep their pre-change behavior until a caller opts into `Veteran` /
   * `Elite`. The tier is player-selectable per scenario and serializes with
   * the game-session config.
   */
  readonly tier?: AITierName;
}

/**
 * Default bot behavior settings.
 *
 * `tier: 'Regular'` is the legacy-scorer tier — `MoveAI` resolves an absent
 * `tier` to `Regular` anyway, so pinning it explicitly here is purely
 * self-documenting and keeps `DEFAULT_BEHAVIOR` aligned with the `default`
 * preset in `behaviorVariants.ts`. The bot's pre-change move scoring is
 * unchanged.
 */
export const DEFAULT_BEHAVIOR: IBotBehavior = {
  retreatThreshold: 0.3,
  retreatEdge: 'nearest',
  safeHeatThreshold: 13,
  tier: 'Regular',
};

// =============================================================================
// Movement Types
// =============================================================================

/**
 * A potential movement action.
 */
export interface IMove {
  /** Destination hex coordinate */
  readonly destination: IHexCoordinate;

  /** Ending facing direction (0-5) */
  readonly facing: Facing;

  /** Type of movement (walk, run, jump) */
  readonly movementType: MovementType;

  /** MP cost for this move */
  readonly mpCost: number;

  /** Heat generated by this move */
  readonly heatGenerated: number;
}

// =============================================================================
// Weapon Types
// =============================================================================

/**
 * Simplified weapon interface for AI decision-making.
 * Contains only the fields needed to determine if a weapon can fire.
 */
export interface IWeapon {
  /** Unique weapon ID */
  readonly id: string;

  /** Weapon name */
  readonly name: string;

  /** Short range (hexes) */
  readonly shortRange: number;

  /** Medium range (hexes) */
  readonly mediumRange: number;

  /** Long range (hexes) */
  readonly longRange: number;

  /** Extreme range (hexes), when advanced range rules are enabled */
  readonly extremeRange?: number;

  /** Damage dealt on hit */
  readonly damage: number;

  /** Heat generated when fired */
  readonly heat: number;

  /** Minimum range penalty (0 = no minimum) */
  readonly minRange: number;

  /** Ammo per ton (-1 = energy weapon, no ammo needed) */
  readonly ammoPerTon: number;

  /**
   * Mounted unit location, when hydrated from catalog/unit construction data.
   * Values are source labels such as `LEFT_ARM`, `RIGHT_TORSO`, or
   * `Center Torso`; consumers normalize at the rule boundary.
   */
  readonly location?: string;

  /**
   * Optional missile fire-control flags hydrated from canonical unit critical
   * slots. When present, runner missile resolution can apply source-backed
   * Artemis cluster-table bonuses without each test hand-building helper
   * contexts.
   */
  readonly hasArtemisIV?: boolean;
  readonly hasPrototypeArtemisIV?: boolean;
  readonly hasArtemisV?: boolean;

  /** Is this weapon destroyed? */
  readonly destroyed: boolean;

  /**
   * Per `improve-bot-basic-combat-competence` task 3.1: the arc the
   * weapon is mounted in. Front is the default (and matches the
   * pre-change behavior — most 'Mech weapons are front-mounted).
   * When present, `AttackAI.selectWeapons` filters weapons by whether
   * the target hex lies in the weapon's mounted arc given the
   * attacker's facing (and optional torso twist).
   *
   * Optional so existing test fixtures and runtime wiring (which
   * build `IWeapon` without arc data) keep working — missing = Front.
   */
  readonly mountingArc?: FiringArc;

  /**
   * Represented multi-arc mount coverage. Used for vehicle sponsons,
   * unlocked turrets, and other mounts that legitimately cover more than one
   * chassis arc. Missing means legacy omnidirectional/unknown coverage.
   */
  readonly mountingArcs?: readonly FiringArc[];

  /**
   * Explicit AMS lifecycle override for represented multi-use AMS behavior.
   * Standard AMS omits this and stays unavailable after one same-phase use.
   */
  readonly amsMultiUse?: boolean;

  /** Vehicle mount location, when this weapon belongs to a vehicle. */
  readonly vehicleMountLocation?: VehicleLocation | VTOLLocation;

  /** True when the weapon is mounted in the vehicle primary turret. */
  readonly vehicleIsTurretMounted?: boolean;

  /**
   * Per `add-ai-resource-planning` (A2) design D4: optional firing-mode
   * metadata for multi-mode weapons — LB-X autocannons (cluster vs. slug),
   * Ultra / Rotary autocannons (rate of fire). When present,
   * `AIWeaponModeSelector` picks the expected-damage-maximizing mode given
   * range, the target's armor state, and the remaining heat budget.
   *
   * A weapon WITHOUT this field is single-mode — `AIWeaponModeSelector`
   * returns its default mode unchanged, so existing weapon fixtures and
   * runtime wiring need no migration (the selector is byte-identical to
   * "always default mode" for them).
   *
   * Typed as `IWeaponFiringModes` from `AIWeaponModeSelector` — declared
   * here as a structural shape to keep `types.ts` free of an import cycle
   * with the selector module.
   */
  readonly firingModes?: IWeaponFiringModes;

  /** True for represented torpedo weapons that must remain in water. */
  readonly isTorpedo?: boolean;
}

/**
 * The kind of multi-mode weapon, used by `AIWeaponModeSelector` to pick the
 * right mode-selection heuristic.
 *
 *   - `cluster-slug`: LB-X autocannon — cluster (spread / crit-seek) vs.
 *     slug (focused).
 *   - `rate-of-fire`: Ultra / Rotary autocannon — a higher rate of fire
 *     trades heat and ammo for damage.
 */
export type WeaponModeKind = 'ammo-mode' | 'cluster-slug' | 'rate-of-fire';

/**
 * One selectable firing mode of a multi-mode weapon.
 *
 * `damage`, `heat`, and `shotsPerTurn` describe the mode's per-turn cost and
 * output — they OVERRIDE the weapon's base `damage`/`heat` when the mode is
 * selected, so the combat engine resolves the chosen mode's numbers.
 */
export interface IWeaponFiringMode {
  /** Stable mode identifier, e.g. `'cluster'`, `'slug'`, `'single'`. */
  readonly id: string;
  /** Damage this mode deals per turn. */
  readonly damage: number;
  /** Heat this mode generates per turn. */
  readonly heat: number;
  /** Ammo rounds this mode consumes per turn (energy weapons: `0`). */
  readonly shotsPerTurn: number;
  /** Optional ammo-bin weapon family when mode choice changes ammo type. */
  readonly ammoWeaponType?: string;
}

/**
 * Firing-mode metadata for a multi-mode weapon — the optional `firingModes`
 * field on `IWeapon`.
 */
export interface IWeaponFiringModes {
  /** The mode-selection heuristic family this weapon belongs to. */
  readonly kind: WeaponModeKind;
  /** The id of the mode fired when mode selection is disabled. */
  readonly defaultModeId: string;
  /** The selectable modes — at least two for a genuine multi-mode weapon. */
  readonly modes: readonly IWeaponFiringMode[];
}

// =============================================================================
// Unit State for AI
// =============================================================================

/**
 * Extended unit state with weapon information for AI.
 * This is used when the AI needs to evaluate attack options.
 */
export interface IAIUnitState {
  /** Unit ID */
  readonly unitId: string;

  /** Current position */
  readonly position: IHexCoordinate;

  /** Current facing */
  readonly facing: Facing;

  /** Current heat level */
  readonly heat: number;

  /** Available weapons */
  readonly weapons: readonly IWeapon[];

  /** Ammo counts by weapon ID (-1 = unlimited for energy weapons) */
  readonly ammo: Readonly<Record<string, number>>;

  /** Is unit destroyed? */
  readonly destroyed: boolean;

  /** Gunnery skill (for to-hit calculation reference) */
  readonly gunnery: number;

  /**
   * Pilot piloting skill (for PSR / fall-mechanics reference).
   *
   * Optional for backward compat: legacy callers that do not supply it
   * fall back to `DEFAULT_PILOTING` at the consumer site. Production
   * `toAIUnitState` reads this from `IUnitGameState.piloting` so real
   * pilot skills drive AI decisions.
   */
  readonly piloting?: number;

  /** Movement this turn */
  readonly movementType: MovementType;

  /** Hexes moved this turn */
  readonly hexesMoved: number;

  /** True when the unit is currently prone. */
  readonly prone?: boolean;

  /** Construction-side unit type label, when known. */
  readonly unitType?: string;

  /** Pilot SPA ids available to movement and combat decision helpers. */
  readonly abilities?: readonly string[];

  /**
   * Per `improve-bot-basic-combat-competence` task 2.2: fraction of
   * max armor + structure remaining on this unit. Used in threat
   * scoring — full-health units are bigger threats than crippled
   * ones. Clamped to `[0, 1]`.
   *
   * Optional for backward compat: callers that do not supply it
   * get a default of `1.0` (treat as undamaged), which preserves
   * the pre-change scoring for legacy wiring paths that have not
   * been updated yet.
   */
  readonly remainingHpFraction?: number;

  /**
   * Per `improve-bot-basic-combat-competence` task 3.2: optional
   * pending torso-twist state used when filtering weapons by arc.
   * When present, the twist shifts the forward arc by one hex side.
   * `undefined` = no twist (most common case).
   */
  readonly torsoTwist?: 'left' | 'right';

  /**
   * Per `add-bot-retreat-behavior` task 1.1: `true` once the unit has
   * crossed its retreat threshold or taken a through-armor crit on
   * cockpit/gyro/engine. Once `true`, stays `true` for the rest of
   * the match (no toggling back to combat).
   */
  readonly isRetreating?: boolean;
  /**
   * Per task 1.1: the edge the unit is heading toward once retreating.
   * Set once on trigger and locked. `null` until retreat begins.
   */
  readonly retreatTargetEdge?: 'north' | 'south' | 'east' | 'west' | null;

  /**
   * Per `add-ai-resource-planning` (A2) design D3: the unit's per-location
   * armour and internal-structure state, used by `scoreTarget`'s
   * crit-seeking term to gauge how *exposed* the unit is — a location with
   * stripped armour and prior internal damage is one good roll from a
   * crippling critical.
   *
   * Optional for backward compatibility: a unit without this field
   * contributes a zero crit-seeking bonus (treated as fully armoured), so
   * legacy `IAIUnitState` fixtures and the `Green`/`Regular` tiers — which
   * zero `critSeekingWeight` anyway — keep the pre-change `scoreTarget`
   * output exactly. Production `toAIUnitState` populates it from
   * `IUnitGameState` armour / structure maps.
   */
  readonly structureState?: IAIStructureState;

  /**
   * Per `add-ai-resource-planning` (A2) design D4: `true` when the unit is
   * actively evading (e.g. ran / jumped this turn for a defensive movement
   * modifier). `AIWeaponModeSelector` treats an evading target like an
   * armour-stripped one — cluster fire's spread is more reliable against a
   * hard-to-hit target. Optional; absent = not evading.
   */
  readonly isEvading?: boolean;

  /**
   * Per `add-ai-resource-planning` (A2) design D1: the unit's per-turn heat
   * dissipation capacity (sum of functioning heat sinks' dissipation).
   * `AIHeatPlanner.projectHeat` subtracts this each turn when projecting the
   * heat curve.
   *
   * Optional for backward compatibility: a unit without this field falls
   * back to the canonical 10-sink baseline (`DEFAULT_HEAT_DISSIPATION`) at
   * the consumer site. Production `toAIUnitState` reads it from the unit's
   * heat-sink loadout. The `Green`/`Regular` tiers set `heatLookaheadTurns`
   * to `0`, so the planner never runs for them regardless.
   */
  readonly heatDissipation?: number;
}

/**
 * Per-location armour and internal-structure snapshot for a unit, used by
 * the A2 crit-seeking target weighting.
 *
 * Each map is keyed by location name (`"center_torso"`, `"left_torso"`,
 * `"head"`, …). `armorByLocation` holds remaining armour points;
 * `armorMaxByLocation` holds the location's starting armour;
 * `internalByLocation` holds remaining internal structure;
 * `internalMaxByLocation` holds the location's starting internal structure.
 *
 * A location whose armour is `0` is *stripped* — every hit there rolls on
 * the internal-structure / critical table directly. A location whose
 * internal structure is below its maximum has taken *prior internal
 * damage*. Both raise the crit-seeking score (design D3).
 */
export interface IAIStructureState {
  /** Remaining armour points per location. */
  readonly armorByLocation: Readonly<Record<string, number>>;
  /** Starting (maximum) armour points per location. */
  readonly armorMaxByLocation: Readonly<Record<string, number>>;
  /** Remaining internal structure points per location. */
  readonly internalByLocation: Readonly<Record<string, number>>;
  /** Starting (maximum) internal structure points per location. */
  readonly internalMaxByLocation: Readonly<Record<string, number>>;
}
