/**
 * AI System Type Definitions
 * Interfaces for bot behavior, movement, and weapon handling.
 */

import { IHexCoordinate, Facing, MovementType } from '@/types/gameplay';

// =============================================================================
// Bot Behavior
// =============================================================================

/**
 * Retreat edge direction for bot behavior.
 */
export type RetreatEdge = 'nearest' | 'north' | 'south' | 'east' | 'west' | 'none';

/**
 * Bot behavior settings (adapted from MekHQ's BehaviorSettings).
 * Controls when and how the bot retreats.
 */
export interface IBotBehavior {
  /**
   * Health percentage threshold to trigger retreat (0-1).
   * Default: 0.3 (retreat at 30% health)
   */
  readonly retreatThreshold: number;

  /**
   * Which map edge to retreat toward.
   * Default: 'nearest'
   */
  readonly retreatEdge: RetreatEdge;
}

/**
 * Default bot behavior settings.
 */
export const DEFAULT_BEHAVIOR: IBotBehavior = {
  retreatThreshold: 0.3,
  retreatEdge: 'nearest',
};

// =============================================================================
// Movement Types
// =============================================================================

/**
 * A potential movement action.
 */
export interface IMove {
  /** Destination hex coordinate */
  readonly destination: IHexCoordinate;

  /** Ending facing direction (0-5) */
  readonly facing: Facing;

  /** Type of movement (walk, run, jump) */
  readonly movementType: MovementType;

  /** MP cost for this move */
  readonly mpCost: number;

  /** Heat generated by this move */
  readonly heatGenerated: number;
}

// =============================================================================
// Weapon Types
// =============================================================================

/**
 * Simplified weapon interface for AI decision-making.
 * Contains only the fields needed to determine if a weapon can fire.
 */
export interface IWeapon {
  /** Unique weapon ID */
  readonly id: string;

  /** Weapon name */
  readonly name: string;

  /** Short range (hexes) */
  readonly shortRange: number;

  /** Medium range (hexes) */
  readonly mediumRange: number;

  /** Long range (hexes) */
  readonly longRange: number;

  /** Damage dealt on hit */
  readonly damage: number;

  /** Heat generated when fired */
  readonly heat: number;

  /** Minimum range penalty (0 = no minimum) */
  readonly minRange: number;

  /** Ammo per ton (-1 = energy weapon, no ammo needed) */
  readonly ammoPerTon: number;

  /** Is this weapon destroyed? */
  readonly destroyed: boolean;
}

// =============================================================================
// Unit State for AI
// =============================================================================

/**
 * Extended unit state with weapon information for AI.
 * This is used when the AI needs to evaluate attack options.
 */
export interface IAIUnitState {
  /** Unit ID */
  readonly unitId: string;

  /** Current position */
  readonly position: IHexCoordinate;

  /** Current facing */
  readonly facing: Facing;

  /** Current heat level */
  readonly heat: number;

  /** Available weapons */
  readonly weapons: readonly IWeapon[];

  /** Ammo counts by weapon ID (-1 = unlimited for energy weapons) */
  readonly ammo: Readonly<Record<string, number>>;

  /** Is unit destroyed? */
  readonly destroyed: boolean;

  /** Gunnery skill (for to-hit calculation reference) */
  readonly gunnery: number;

  /** Movement this turn */
  readonly movementType: MovementType;

  /** Hexes moved this turn */
  readonly hexesMoved: number;
}
