import type { ICampaignOptionMeta } from './campaignOptionMeta';

import { defaults, OptionGroupId } from './campaignOptionMeta';

export const COMBAT_FORCE_OPTIONS: Record<string, ICampaignOptionMeta> = {
  useAutoResolve: {
    key: 'useAutoResolve',
    group: OptionGroupId.Combat,
    label: 'Use Auto-Resolve',
    description: 'Whether to use auto-resolve for battles',
    type: 'boolean',
    defaultValue: defaults.useAutoResolve,
  },
  autoResolveCasualtyRate: {
    key: 'autoResolveCasualtyRate',
    group: OptionGroupId.Combat,
    label: 'Auto-Resolve Casualty Rate',
    description: 'Casualty rate multiplier for auto-resolve (1.0 = normal)',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.autoResolveCasualtyRate,
  },
  allowPilotCapture: {
    key: 'allowPilotCapture',
    group: OptionGroupId.Combat,
    label: 'Allow Pilot Capture',
    description: 'Whether pilots can be captured',
    type: 'boolean',
    defaultValue: defaults.allowPilotCapture,
  },
  useRandomInjuries: {
    key: 'useRandomInjuries',
    group: OptionGroupId.Combat,
    label: 'Use Random Injuries',
    description: 'Whether to use random pilot injuries',
    type: 'boolean',
    defaultValue: defaults.useRandomInjuries,
  },
  pilotDeathChance: {
    key: 'pilotDeathChance',
    group: OptionGroupId.Combat,
    label: 'Pilot Death Chance',
    description: 'Chance of pilot death on mech destruction (0.0-1.0)',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: defaults.pilotDeathChance,
  },
  autoEject: {
    key: 'autoEject',
    group: OptionGroupId.Combat,
    label: 'Auto Eject',
    description: 'Whether ejection is automatic on destruction',
    type: 'boolean',
    defaultValue: defaults.autoEject,
  },
  trackAmmunition: {
    key: 'trackAmmunition',
    group: OptionGroupId.Combat,
    label: 'Track Ammunition',
    description: 'Whether to track ammunition usage',
    type: 'boolean',
    defaultValue: defaults.trackAmmunition,
  },
  useQuirks: {
    key: 'useQuirks',
    group: OptionGroupId.Combat,
    label: 'Use Quirks',
    description: 'Whether to use quirks system',
    type: 'boolean',
    defaultValue: defaults.useQuirks,
  },
  useAtBScenarios: {
    key: 'useAtBScenarios',
    group: OptionGroupId.Combat,
    label: 'Use AtB Scenarios',
    description: 'Whether to use AtB dynamic scenario generation',
    type: 'boolean',
    defaultValue: false,
  },
  difficultyMultiplier: {
    key: 'difficultyMultiplier',
    group: OptionGroupId.Combat,
    label: 'Difficulty Multiplier',
    description:
      'Difficulty multiplier for OpFor BV calculation (0.5 easy to 2.0 hard)',
    type: 'number',
    min: 0.5,
    max: 2.0,
    step: 0.1,
    defaultValue: 1.0,
  },
  maxUnitsPerLance: {
    key: 'maxUnitsPerLance',
    group: OptionGroupId.ForceOrganization,
    label: 'Max Units Per Lance',
    description: 'Maximum units per lance',
    type: 'number',
    min: 1,
    max: 12,
    step: 1,
    defaultValue: defaults.maxUnitsPerLance,
  },
  maxLancesPerCompany: {
    key: 'maxLancesPerCompany',
    group: OptionGroupId.ForceOrganization,
    label: 'Max Lances Per Company',
    description: 'Maximum lances per company',
    type: 'number',
    min: 1,
    max: 12,
    step: 1,
    defaultValue: defaults.maxLancesPerCompany,
  },
  enforceFormationRules: {
    key: 'enforceFormationRules',
    group: OptionGroupId.ForceOrganization,
    label: 'Enforce Formation Rules',
    description: 'Whether to enforce formation rules',
    type: 'boolean',
    defaultValue: defaults.enforceFormationRules,
  },
  allowMixedFormations: {
    key: 'allowMixedFormations',
    group: OptionGroupId.ForceOrganization,
    label: 'Allow Mixed Formations',
    description: 'Whether to allow mixed unit types in formations',
    type: 'boolean',
    defaultValue: defaults.allowMixedFormations,
  },
  requireForceCommanders: {
    key: 'requireForceCommanders',
    group: OptionGroupId.ForceOrganization,
    label: 'Require Force Commanders',
    description: 'Whether to require commanders for forces',
    type: 'boolean',
    defaultValue: defaults.requireForceCommanders,
  },
  useCombatTeams: {
    key: 'useCombatTeams',
    group: OptionGroupId.ForceOrganization,
    label: 'Use Combat Teams',
    description: 'Whether to use combat teams (AtB)',
    type: 'boolean',
    defaultValue: defaults.useCombatTeams,
  },
};
