import type { ICampaignOptionMeta } from './campaignOptionMeta';

import { defaults, OptionGroupId } from './campaignOptionMeta';

export const FINANCIAL_OPTIONS: Record<string, ICampaignOptionMeta> = {
  startingFunds: {
    key: 'startingFunds',
    group: OptionGroupId.Financial,
    label: 'Starting Funds',
    description: 'Starting funds in C-bills',
    type: 'number',
    min: 0,
    step: 100000,
    defaultValue: defaults.startingFunds,
  },
  maintenanceCostMultiplier: {
    key: 'maintenanceCostMultiplier',
    group: OptionGroupId.Financial,
    label: 'Maintenance Cost Multiplier',
    description: 'Multiplier for maintenance costs (1.0 = normal)',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.maintenanceCostMultiplier,
  },
  repairCostMultiplier: {
    key: 'repairCostMultiplier',
    group: OptionGroupId.Financial,
    label: 'Repair Cost Multiplier',
    description: 'Multiplier for repair costs (1.0 = normal)',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.repairCostMultiplier,
  },
  acquisitionCostMultiplier: {
    key: 'acquisitionCostMultiplier',
    group: OptionGroupId.Financial,
    label: 'Acquisition Cost Multiplier',
    description: 'Multiplier for part acquisition costs (1.0 = normal)',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.acquisitionCostMultiplier,
  },
  payForMaintenance: {
    key: 'payForMaintenance',
    group: OptionGroupId.Financial,
    label: 'Pay For Maintenance',
    description: 'Whether to pay for unit maintenance',
    type: 'boolean',
    defaultValue: defaults.payForMaintenance,
  },
  payForRepairs: {
    key: 'payForRepairs',
    group: OptionGroupId.Financial,
    label: 'Pay For Repairs',
    description: 'Whether to pay for repairs',
    type: 'boolean',
    defaultValue: defaults.payForRepairs,
  },
  payForSalaries: {
    key: 'payForSalaries',
    group: OptionGroupId.Financial,
    label: 'Pay For Salaries',
    description: 'Whether to pay salaries',
    type: 'boolean',
    defaultValue: defaults.payForSalaries,
  },
  payForAmmunition: {
    key: 'payForAmmunition',
    group: OptionGroupId.Financial,
    label: 'Pay For Ammunition',
    description: 'Whether to pay for ammunition',
    type: 'boolean',
    defaultValue: defaults.payForAmmunition,
  },
  maintenanceCycleDays: {
    key: 'maintenanceCycleDays',
    group: OptionGroupId.Financial,
    label: 'Maintenance Cycle Days',
    description: 'Days between maintenance cycles (0 = disabled)',
    type: 'number',
    min: 0,
    max: 365,
    step: 1,
    defaultValue: defaults.maintenanceCycleDays,
  },
  useLoanSystem: {
    key: 'useLoanSystem',
    group: OptionGroupId.Financial,
    label: 'Use Loan System',
    description: 'Whether to use loan system',
    type: 'boolean',
    defaultValue: defaults.useLoanSystem,
  },
  useTaxes: {
    key: 'useTaxes',
    group: OptionGroupId.Financial,
    label: 'Use Taxes',
    description: 'Whether to use tax system',
    type: 'boolean',
    defaultValue: defaults.useTaxes,
  },
  taxRate: {
    key: 'taxRate',
    group: OptionGroupId.Financial,
    label: 'Tax Rate',
    description: 'Tax rate as percentage (e.g., 10 = 10%)',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.taxRate,
  },
  overheadPercent: {
    key: 'overheadPercent',
    group: OptionGroupId.Financial,
    label: 'Overhead Percent',
    description: 'Overhead percentage of salary',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.overheadPercent,
  },
  useRoleBasedSalaries: {
    key: 'useRoleBasedSalaries',
    group: OptionGroupId.Financial,
    label: 'Use Role-Based Salaries',
    description: 'Whether to use role-based salary system',
    type: 'boolean',
    defaultValue: defaults.useRoleBasedSalaries,
  },
  payForSecondaryRole: {
    key: 'payForSecondaryRole',
    group: OptionGroupId.Financial,
    label: 'Pay For Secondary Role',
    description: 'Whether to pay for secondary role assignments',
    type: 'boolean',
    defaultValue: defaults.payForSecondaryRole,
  },
  maxLoanPercent: {
    key: 'maxLoanPercent',
    group: OptionGroupId.Financial,
    label: 'Max Loan Percent',
    description: 'Maximum loan as percentage of total assets',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.maxLoanPercent,
  },
  defaultLoanRate: {
    key: 'defaultLoanRate',
    group: OptionGroupId.Financial,
    label: 'Default Loan Rate',
    description: 'Default annual loan interest rate',
    type: 'number',
    min: 0,
    max: 100,
    step: 0.5,
    defaultValue: defaults.defaultLoanRate,
  },
  taxFrequency: {
    key: 'taxFrequency',
    group: OptionGroupId.Financial,
    label: 'Tax Frequency',
    description: 'Tax payment frequency',
    type: 'enum',
    enumValues: ['monthly', 'quarterly', 'annually'],
    defaultValue: defaults.taxFrequency,
  },
  useFoodAndHousing: {
    key: 'useFoodAndHousing',
    group: OptionGroupId.Financial,
    label: 'Use Food And Housing',
    description: 'Whether to use food and housing costs',
    type: 'boolean',
    defaultValue: defaults.useFoodAndHousing,
  },
  clanPriceMultiplier: {
    key: 'clanPriceMultiplier',
    group: OptionGroupId.Financial,
    label: 'Clan Price Multiplier',
    description: 'Price multiplier for clan equipment',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.clanPriceMultiplier,
  },
  mixedTechPriceMultiplier: {
    key: 'mixedTechPriceMultiplier',
    group: OptionGroupId.Financial,
    label: 'Mixed Tech Price Multiplier',
    description: 'Price multiplier for mixed tech equipment',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.mixedTechPriceMultiplier,
  },
  usedEquipmentMultiplier: {
    key: 'usedEquipmentMultiplier',
    group: OptionGroupId.Financial,
    label: 'Used Equipment Multiplier',
    description: 'Price multiplier for used equipment',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.01,
    defaultValue: defaults.usedEquipmentMultiplier,
  },
  damagedEquipmentMultiplier: {
    key: 'damagedEquipmentMultiplier',
    group: OptionGroupId.Financial,
    label: 'Damaged Equipment Multiplier',
    description: 'Price multiplier for damaged equipment',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.01,
    defaultValue: defaults.damagedEquipmentMultiplier,
  },
};
