import type { ICampaignOptionMeta } from './campaignOptionMeta';

import { defaults, OptionGroupId } from './campaignOptionMeta';

export const GENERAL_EVENT_OPTIONS: Record<string, ICampaignOptionMeta> = {
  dateFormat: {
    key: 'dateFormat',
    group: OptionGroupId.General,
    label: 'Date Format',
    description: 'Date format for display',
    type: 'string',
    defaultValue: defaults.dateFormat,
  },
  useFactionRules: {
    key: 'useFactionRules',
    group: OptionGroupId.General,
    label: 'Use Faction Rules',
    description: 'Whether to use faction-specific rules',
    type: 'boolean',
    defaultValue: defaults.useFactionRules,
  },
  techLevel: {
    key: 'techLevel',
    group: OptionGroupId.General,
    label: 'Tech Level',
    description:
      'Tech level limit (0=Intro, 1=Standard, 2=Advanced, 3=Experimental)',
    type: 'number',
    min: 0,
    max: 3,
    step: 1,
    defaultValue: defaults.techLevel,
  },
  useAcquisitionSystem: {
    key: 'useAcquisitionSystem',
    group: OptionGroupId.General,
    label: 'Use Acquisition System',
    description: 'Whether to use the acquisition/procurement system',
    type: 'boolean',
    defaultValue: defaults.useAcquisitionSystem,
  },
  usePlanetaryModifiers: {
    key: 'usePlanetaryModifiers',
    group: OptionGroupId.General,
    label: 'Use Planetary Modifiers',
    description: 'Whether to apply planetary availability modifiers',
    type: 'boolean',
    defaultValue: defaults.usePlanetaryModifiers,
  },
  acquisitionTransitUnit: {
    key: 'acquisitionTransitUnit',
    group: OptionGroupId.General,
    label: 'Acquisition Transit Unit',
    description: 'Time unit for acquisition transit',
    type: 'enum',
    enumValues: ['day', 'week', 'month'],
    defaultValue: defaults.acquisitionTransitUnit,
  },
  clanPartsPenalty: {
    key: 'clanPartsPenalty',
    group: OptionGroupId.General,
    label: 'Clan Parts Penalty',
    description: 'Whether to apply penalty for Clan parts in IS factions',
    type: 'boolean',
    defaultValue: defaults.clanPartsPenalty,
  },
  limitByYear: {
    key: 'limitByYear',
    group: OptionGroupId.General,
    label: 'Limit By Year',
    description: 'Whether to limit equipment by year',
    type: 'boolean',
    defaultValue: defaults.limitByYear,
  },
  allowClanEquipment: {
    key: 'allowClanEquipment',
    group: OptionGroupId.General,
    label: 'Allow Clan Equipment',
    description: 'Whether to allow Clan equipment for IS factions',
    type: 'boolean',
    defaultValue: defaults.allowClanEquipment,
  },
  useRandomEvents: {
    key: 'useRandomEvents',
    group: OptionGroupId.Events,
    label: 'Use Random Events',
    description: 'Whether to use random events',
    type: 'boolean',
    defaultValue: defaults.useRandomEvents,
  },
  usePrisonerEvents: {
    key: 'usePrisonerEvents',
    group: OptionGroupId.Events,
    label: 'Use Prisoner Events',
    description: 'Whether to use prisoner random events',
    type: 'boolean',
    defaultValue: defaults.usePrisonerEvents,
  },
  useLifeEvents: {
    key: 'useLifeEvents',
    group: OptionGroupId.Events,
    label: 'Use Life Events',
    description: 'Whether to use life random events',
    type: 'boolean',
    defaultValue: defaults.useLifeEvents,
  },
  useContractEvents: {
    key: 'useContractEvents',
    group: OptionGroupId.Events,
    label: 'Use Contract Events',
    description: 'Whether to use contract random events',
    type: 'boolean',
    defaultValue: defaults.useContractEvents,
  },
  simulateGrayMonday: {
    key: 'simulateGrayMonday',
    group: OptionGroupId.Events,
    label: 'Simulate Gray Monday',
    description: 'Whether to simulate Gray Monday historical event',
    type: 'boolean',
    defaultValue: defaults.simulateGrayMonday,
  },
  enableDayReportNotifications: {
    key: 'enableDayReportNotifications',
    group: OptionGroupId.General,
    label: 'Enable Day Report Notifications',
    description: 'Whether to show day report notifications after advancing',
    type: 'boolean',
    defaultValue: defaults.enableDayReportNotifications,
  },
};
