import { MedicalSystem } from '@/lib/campaign/medical/medicalTypes';

import type { ICampaignOptionMeta } from './campaignOptionMeta';

import { defaults, OptionGroupId } from './campaignOptionMeta';

export const PERSONNEL_OPTIONS: Record<string, ICampaignOptionMeta> = {
  healingRateMultiplier: {
    key: 'healingRateMultiplier',
    group: OptionGroupId.Personnel,
    label: 'Healing Rate Multiplier',
    description: 'Multiplier for natural healing rate (1.0 = normal)',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.healingRateMultiplier,
  },
  salaryMultiplier: {
    key: 'salaryMultiplier',
    group: OptionGroupId.Personnel,
    label: 'Salary Multiplier',
    description: 'Multiplier for all salaries (1.0 = normal)',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.salaryMultiplier,
  },
  retirementAge: {
    key: 'retirementAge',
    group: OptionGroupId.Personnel,
    label: 'Retirement Age',
    description: 'Age at which personnel may retire',
    type: 'number',
    min: 1,
    max: 120,
    step: 1,
    defaultValue: defaults.retirementAge,
  },
  healingWaitingPeriod: {
    key: 'healingWaitingPeriod',
    group: OptionGroupId.Personnel,
    label: 'Healing Waiting Period',
    description: 'Days to wait between healing checks',
    type: 'number',
    min: 0,
    max: 30,
    step: 1,
    defaultValue: defaults.healingWaitingPeriod,
  },
  medicalSystem: {
    key: 'medicalSystem',
    group: OptionGroupId.Medical,
    label: 'Medical System',
    description: 'Medical system to use',
    type: 'enum',
    enumValues: Object.values(MedicalSystem),
    defaultValue: defaults.medicalSystem,
  },
  maxPatientsPerDoctor: {
    key: 'maxPatientsPerDoctor',
    group: OptionGroupId.Medical,
    label: 'Max Patients Per Doctor',
    description: 'Maximum patients per doctor',
    type: 'number',
    min: 1,
    max: 100,
    step: 1,
    defaultValue: defaults.maxPatientsPerDoctor,
  },
  doctorsUseAdministration: {
    key: 'doctorsUseAdministration',
    group: OptionGroupId.Medical,
    label: 'Doctors Use Administration',
    description:
      'Whether doctors use administration skill to increase capacity',
    type: 'boolean',
    defaultValue: defaults.doctorsUseAdministration,
  },
  xpPerMission: {
    key: 'xpPerMission',
    group: OptionGroupId.Personnel,
    label: 'XP Per Mission',
    description: 'XP awarded per mission',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.xpPerMission,
  },
  xpPerKill: {
    key: 'xpPerKill',
    group: OptionGroupId.Personnel,
    label: 'XP Per Kill',
    description: 'XP awarded per kill',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.xpPerKill,
  },
  xpCostMultiplier: {
    key: 'xpCostMultiplier',
    group: OptionGroupId.Personnel,
    label: 'XP Cost Multiplier',
    description: 'Multiplier for skill improvement XP costs (1.0 = normal)',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.xpCostMultiplier,
  },
  trackTimeInService: {
    key: 'trackTimeInService',
    group: OptionGroupId.Personnel,
    label: 'Track Time In Service',
    description: 'Whether to track time in service',
    type: 'boolean',
    defaultValue: defaults.trackTimeInService,
  },
  useEdge: {
    key: 'useEdge',
    group: OptionGroupId.Personnel,
    label: 'Use Edge',
    description: 'Whether to use edge points',
    type: 'boolean',
    defaultValue: defaults.useEdge,
  },
  rankSystemCode: {
    key: 'rankSystemCode',
    group: OptionGroupId.Personnel,
    label: 'Rank System Code',
    description: 'Code of the active rank system',
    type: 'string',
    defaultValue: defaults.rankSystemCode,
  },
};
