import { PersonnelMarketStyle } from '@/types/campaign/markets/marketTypes';

import type { ICampaignOptionMeta } from './campaignOptionMeta';

import { defaults, OptionGroupId } from './campaignOptionMeta';

export const TURNOVER_MARKET_OPTIONS: Record<string, ICampaignOptionMeta> = {
  useTurnover: {
    key: 'useTurnover',
    group: OptionGroupId.Turnover,
    label: 'Use Turnover',
    description: 'Whether to use turnover system',
    type: 'boolean',
    defaultValue: defaults.useTurnover,
  },
  turnoverFixedTargetNumber: {
    key: 'turnoverFixedTargetNumber',
    group: OptionGroupId.Turnover,
    label: 'Turnover Fixed Target Number',
    description: 'Fixed target number for turnover checks',
    type: 'number',
    min: 1,
    max: 12,
    step: 1,
    defaultValue: defaults.turnoverFixedTargetNumber,
  },
  turnoverCheckFrequency: {
    key: 'turnoverCheckFrequency',
    group: OptionGroupId.Turnover,
    label: 'Turnover Check Frequency',
    description: 'How often turnover checks occur',
    type: 'enum',
    enumValues: ['weekly', 'monthly', 'quarterly', 'annually', 'never'],
    defaultValue: defaults.turnoverCheckFrequency,
  },
  turnoverCommanderImmune: {
    key: 'turnoverCommanderImmune',
    group: OptionGroupId.Turnover,
    label: 'Turnover Commander Immune',
    description: 'Whether the commander is immune to turnover',
    type: 'boolean',
    defaultValue: defaults.turnoverCommanderImmune,
  },
  turnoverPayoutMultiplier: {
    key: 'turnoverPayoutMultiplier',
    group: OptionGroupId.Turnover,
    label: 'Turnover Payout Multiplier',
    description: 'Multiplier for turnover payout',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.turnoverPayoutMultiplier,
  },
  turnoverUseSkillModifiers: {
    key: 'turnoverUseSkillModifiers',
    group: OptionGroupId.Turnover,
    label: 'Turnover Use Skill Modifiers',
    description: 'Whether to use skill modifiers for turnover',
    type: 'boolean',
    defaultValue: defaults.turnoverUseSkillModifiers,
  },
  turnoverUseAgeModifiers: {
    key: 'turnoverUseAgeModifiers',
    group: OptionGroupId.Turnover,
    label: 'Turnover Use Age Modifiers',
    description: 'Whether to use age modifiers for turnover',
    type: 'boolean',
    defaultValue: defaults.turnoverUseAgeModifiers,
  },
  turnoverUseMissionStatusModifiers: {
    key: 'turnoverUseMissionStatusModifiers',
    group: OptionGroupId.Turnover,
    label: 'Turnover Use Mission Status Modifiers',
    description: 'Whether to use mission status modifiers for turnover',
    type: 'boolean',
    defaultValue: defaults.turnoverUseMissionStatusModifiers,
  },
  trackFactionStanding: {
    key: 'trackFactionStanding',
    group: OptionGroupId.FactionStanding,
    label: 'Track Faction Standing',
    description: 'Whether to track faction standing',
    type: 'boolean',
    defaultValue: defaults.trackFactionStanding,
  },
  regardChangeMultiplier: {
    key: 'regardChangeMultiplier',
    group: OptionGroupId.FactionStanding,
    label: 'Regard Change Multiplier',
    description: 'Multiplier for regard changes (1.0 = normal)',
    type: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: defaults.regardChangeMultiplier,
  },
  autoAwardConfig: {
    key: 'autoAwardConfig',
    group: OptionGroupId.Advanced,
    label: 'Auto-Award Configuration',
    description: 'Auto-award system configuration (complex object)',
    type: 'string',
    defaultValue: undefined,
  },
  unitMarketMethod: {
    key: 'unitMarketMethod',
    group: OptionGroupId.Markets,
    label: 'Unit Market Method',
    description: 'Unit market generation method',
    type: 'enum',
    enumValues: ['none', 'atb_monthly'],
    defaultValue: defaults.unitMarketMethod,
  },
  personnelMarketStyle: {
    key: 'personnelMarketStyle',
    group: OptionGroupId.Markets,
    label: 'Personnel Market Style',
    description: 'Personnel market generation style',
    type: 'enum',
    enumValues: Object.values(PersonnelMarketStyle),
    defaultValue: defaults.personnelMarketStyle,
  },
  contractMarketMethod: {
    key: 'contractMarketMethod',
    group: OptionGroupId.Markets,
    label: 'Contract Market Method',
    description: 'Contract market generation method',
    type: 'enum',
    enumValues: ['none', 'atb_monthly', 'cam_ops'],
    defaultValue: defaults.contractMarketMethod,
  },
};
