import type { ICampaignOptionMeta } from './campaignOptionMeta';

import { defaults, OptionGroupId } from './campaignOptionMeta';

export const XP_PROGRESSION_OPTIONS: Record<string, ICampaignOptionMeta> = {
  scenarioXP: {
    key: 'scenarioXP',
    group: OptionGroupId.XpProgression,
    label: 'Scenario XP',
    description: 'XP awarded per scenario participation',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.scenarioXP,
  },
  killXPAward: {
    key: 'killXPAward',
    group: OptionGroupId.XpProgression,
    label: 'Kill XP Award',
    description: 'XP awarded per kill',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.killXPAward,
  },
  killsForXP: {
    key: 'killsForXP',
    group: OptionGroupId.XpProgression,
    label: 'Kills For XP',
    description: 'Number of kills required to earn kill XP award',
    type: 'number',
    min: 1,
    max: 100,
    step: 1,
    defaultValue: defaults.killsForXP,
  },
  taskXP: {
    key: 'taskXP',
    group: OptionGroupId.XpProgression,
    label: 'Task XP',
    description: 'XP awarded per task completion',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.taskXP,
  },
  nTasksXP: {
    key: 'nTasksXP',
    group: OptionGroupId.XpProgression,
    label: 'Tasks For XP',
    description: 'Number of tasks required to earn task XP',
    type: 'number',
    min: 1,
    max: 100,
    step: 1,
    defaultValue: defaults.nTasksXP,
  },
  vocationalXP: {
    key: 'vocationalXP',
    group: OptionGroupId.XpProgression,
    label: 'Vocational XP',
    description: 'XP awarded per successful vocational training check',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.vocationalXP,
  },
  vocationalXPTargetNumber: {
    key: 'vocationalXPTargetNumber',
    group: OptionGroupId.XpProgression,
    label: 'Vocational XP Target Number',
    description: 'Target number for vocational training 2d6 roll',
    type: 'number',
    min: 2,
    max: 12,
    step: 1,
    defaultValue: defaults.vocationalXPTargetNumber,
  },
  vocationalXPCheckFrequency: {
    key: 'vocationalXPCheckFrequency',
    group: OptionGroupId.XpProgression,
    label: 'Vocational XP Check Frequency',
    description: 'Days between vocational training checks',
    type: 'number',
    min: 1,
    max: 365,
    step: 1,
    defaultValue: defaults.vocationalXPCheckFrequency,
  },
  adminXP: {
    key: 'adminXP',
    group: OptionGroupId.XpProgression,
    label: 'Admin XP',
    description: 'XP awarded for administrative duties',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.adminXP,
  },
  adminXPPeriod: {
    key: 'adminXPPeriod',
    group: OptionGroupId.XpProgression,
    label: 'Admin XP Period',
    description: 'Days between admin XP awards',
    type: 'number',
    min: 1,
    max: 365,
    step: 1,
    defaultValue: defaults.adminXPPeriod,
  },
  missionFailXP: {
    key: 'missionFailXP',
    group: OptionGroupId.XpProgression,
    label: 'Mission Fail XP',
    description: 'XP awarded for mission failure',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.missionFailXP,
  },
  missionSuccessXP: {
    key: 'missionSuccessXP',
    group: OptionGroupId.XpProgression,
    label: 'Mission Success XP',
    description: 'XP awarded for mission success',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.missionSuccessXP,
  },
  missionOutstandingXP: {
    key: 'missionOutstandingXP',
    group: OptionGroupId.XpProgression,
    label: 'Mission Outstanding XP',
    description: 'XP awarded for outstanding mission success',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: defaults.missionOutstandingXP,
  },
  useAgingEffects: {
    key: 'useAgingEffects',
    group: OptionGroupId.XpProgression,
    label: 'Use Aging Effects',
    description:
      'Whether to apply aging effects (attribute decay, trait application)',
    type: 'boolean',
    defaultValue: defaults.useAgingEffects,
  },
};
