import type { IQuickGameUnitRequest } from '@/types/quickgame';

export const DEMO_UNITS: IQuickGameUnitRequest[] = [
  {
    sourceUnitId: 'atlas-as7-d',
    name: 'Atlas AS7-D',
    chassis: 'Atlas',
    variant: 'AS7-D',
    bv: 1897,
    tonnage: 100,
    gunnery: 4,
    piloting: 5,
    maxArmor: {
      head: 9,
      ct: 47,
      lt: 32,
      rt: 32,
      la: 34,
      ra: 34,
      ll: 41,
      rl: 41,
    },
    maxStructure: {
      head: 3,
      ct: 31,
      lt: 21,
      rt: 21,
      la: 17,
      ra: 17,
      ll: 21,
      rl: 21,
    },
  },
  {
    sourceUnitId: 'marauder-mad-3r',
    name: 'Marauder MAD-3R',
    chassis: 'Marauder',
    variant: 'MAD-3R',
    bv: 1220,
    tonnage: 75,
    gunnery: 4,
    piloting: 5,
    maxArmor: {
      head: 9,
      ct: 30,
      lt: 24,
      rt: 24,
      la: 24,
      ra: 24,
      ll: 25,
      rl: 25,
    },
    maxStructure: {
      head: 3,
      ct: 23,
      lt: 16,
      rt: 16,
      la: 12,
      ra: 12,
      ll: 16,
      rl: 16,
    },
  },
  {
    sourceUnitId: 'wolverine-wvr-6r',
    name: 'Wolverine WVR-6R',
    chassis: 'Wolverine',
    variant: 'WVR-6R',
    bv: 1101,
    tonnage: 55,
    gunnery: 4,
    piloting: 5,
    maxArmor: {
      head: 9,
      ct: 25,
      lt: 18,
      rt: 18,
      la: 16,
      ra: 16,
      ll: 22,
      rl: 22,
    },
    maxStructure: {
      head: 3,
      ct: 18,
      lt: 13,
      rt: 13,
      la: 9,
      ra: 9,
      ll: 13,
      rl: 13,
    },
  },
  {
    sourceUnitId: 'locust-lcn-1v',
    name: 'Locust LCT-1V',
    chassis: 'Locust',
    variant: 'LCT-1V',
    bv: 432,
    tonnage: 20,
    gunnery: 4,
    piloting: 5,
    maxArmor: { head: 4, ct: 8, lt: 6, rt: 6, la: 4, ra: 4, ll: 4, rl: 4 },
    maxStructure: {
      head: 3,
      ct: 6,
      lt: 5,
      rt: 5,
      la: 3,
      ra: 3,
      ll: 4,
      rl: 4,
    },
  },
  {
    sourceUnitId: 'hunchback-hbk-4g',
    name: 'Hunchback HBK-4G',
    chassis: 'Hunchback',
    variant: 'HBK-4G',
    bv: 1067,
    tonnage: 50,
    gunnery: 4,
    piloting: 5,
    maxArmor: {
      head: 9,
      ct: 26,
      lt: 18,
      rt: 18,
      la: 16,
      ra: 16,
      ll: 20,
      rl: 20,
    },
    maxStructure: {
      head: 3,
      ct: 16,
      lt: 12,
      rt: 12,
      la: 8,
      ra: 8,
      ll: 12,
      rl: 12,
    },
  },
  {
    sourceUnitId: 'shadow-hawk-shd-2h',
    name: 'Shadow Hawk SHD-2H',
    chassis: 'Shadow Hawk',
    variant: 'SHD-2H',
    bv: 1064,
    tonnage: 55,
    gunnery: 4,
    piloting: 5,
    maxArmor: {
      head: 9,
      ct: 23,
      lt: 18,
      rt: 18,
      la: 16,
      ra: 16,
      ll: 16,
      rl: 16,
    },
    maxStructure: {
      head: 3,
      ct: 18,
      lt: 13,
      rt: 13,
      la: 9,
      ra: 9,
      ll: 13,
      rl: 13,
    },
  },
];
