import {
  tacticalMapEcmNullifiedTagIndirectFireCombatState,
  tacticalMapEcmNullifiedTagIndirectFireHexTerrain,
  tacticalMapEcmNullifiedTagIndirectFireSelectedWeaponIds,
  tacticalMapEcmNullifiedTagIndirectFireTargetId,
  tacticalMapEcmNullifiedTagIndirectFireTokens,
} from './tactical-map.indirect-fire-ecm-scenario';
import {
  tacticalMapForwardObserverIndirectFireCombatState,
  tacticalMapForwardObserverIndirectFireHexTerrain,
  tacticalMapForwardObserverIndirectFireSelectedWeaponIds,
  tacticalMapForwardObserverIndirectFireTargetId,
  tacticalMapForwardObserverIndirectFireTokens,
  tacticalMapINarcBeaconIndirectFireCombatState,
  tacticalMapINarcBeaconIndirectFireHexTerrain,
  tacticalMapINarcBeaconIndirectFireSelectedWeaponIds,
  tacticalMapINarcBeaconIndirectFireTargetId,
  tacticalMapINarcBeaconIndirectFireTokens,
  tacticalMapIndirectFireCombatState,
  tacticalMapIndirectFireHexTerrain,
  tacticalMapIndirectFireSelectedWeaponIds,
  tacticalMapIndirectFireTargetId,
  tacticalMapIndirectFireTokens,
  tacticalMapNarcBeaconIndirectFireCombatState,
  tacticalMapNarcBeaconIndirectFireHexTerrain,
  tacticalMapNarcBeaconIndirectFireSelectedWeaponIds,
  tacticalMapNarcBeaconIndirectFireTargetId,
  tacticalMapNarcBeaconIndirectFireTokens,
  tacticalMapSemiGuidedTagIndirectFireCombatState,
  tacticalMapSemiGuidedTagIndirectFireHexTerrain,
  tacticalMapSemiGuidedTagIndirectFireSelectedWeaponIds,
  tacticalMapSemiGuidedTagIndirectFireTargetId,
  tacticalMapSemiGuidedTagIndirectFireTokens,
} from './tactical-map.indirect-fire-scenario';
import {
  tacticalMapSpotterSkillIndirectFireCombatState,
  tacticalMapSpotterSkillIndirectFireHexTerrain,
  tacticalMapSpotterSkillIndirectFireSelectedWeaponIds,
  tacticalMapSpotterSkillIndirectFireTargetId,
  tacticalMapSpotterSkillIndirectFireTokens,
} from './tactical-map.indirect-fire-spotter-skill-scenario';

const selectedHex = { q: 0, r: 0 } as const;

export const tacticalMapIndirectFireHarnessScenarios = {
  'forward-observer-indirect-fire': {
    selectedWeaponIds: tacticalMapForwardObserverIndirectFireSelectedWeaponIds,
    targetUnitId: tacticalMapForwardObserverIndirectFireTargetId,
    tokens: tacticalMapForwardObserverIndirectFireTokens,
    combatState: tacticalMapForwardObserverIndirectFireCombatState,
    selectedHex,
    hexTerrain: tacticalMapForwardObserverIndirectFireHexTerrain,
  },
  'ecm-nullified-tag-indirect-fire': {
    selectedWeaponIds: tacticalMapEcmNullifiedTagIndirectFireSelectedWeaponIds,
    targetUnitId: tacticalMapEcmNullifiedTagIndirectFireTargetId,
    tokens: tacticalMapEcmNullifiedTagIndirectFireTokens,
    combatState: tacticalMapEcmNullifiedTagIndirectFireCombatState,
    selectedHex,
    hexTerrain: tacticalMapEcmNullifiedTagIndirectFireHexTerrain,
  },
  'inarc-beacon-indirect-fire': {
    selectedWeaponIds: tacticalMapINarcBeaconIndirectFireSelectedWeaponIds,
    targetUnitId: tacticalMapINarcBeaconIndirectFireTargetId,
    tokens: tacticalMapINarcBeaconIndirectFireTokens,
    combatState: tacticalMapINarcBeaconIndirectFireCombatState,
    selectedHex,
    hexTerrain: tacticalMapINarcBeaconIndirectFireHexTerrain,
  },
  'indirect-fire-spotter': {
    selectedWeaponIds: tacticalMapIndirectFireSelectedWeaponIds,
    targetUnitId: tacticalMapIndirectFireTargetId,
    tokens: tacticalMapIndirectFireTokens,
    combatState: tacticalMapIndirectFireCombatState,
    selectedHex,
    hexTerrain: tacticalMapIndirectFireHexTerrain,
  },
  'indirect-fire-spotter-skill': {
    selectedWeaponIds: tacticalMapSpotterSkillIndirectFireSelectedWeaponIds,
    targetUnitId: tacticalMapSpotterSkillIndirectFireTargetId,
    tokens: tacticalMapSpotterSkillIndirectFireTokens,
    combatState: tacticalMapSpotterSkillIndirectFireCombatState,
    selectedHex,
    hexTerrain: tacticalMapSpotterSkillIndirectFireHexTerrain,
  },
  'narc-beacon-indirect-fire': {
    selectedWeaponIds: tacticalMapNarcBeaconIndirectFireSelectedWeaponIds,
    targetUnitId: tacticalMapNarcBeaconIndirectFireTargetId,
    tokens: tacticalMapNarcBeaconIndirectFireTokens,
    combatState: tacticalMapNarcBeaconIndirectFireCombatState,
    selectedHex,
    hexTerrain: tacticalMapNarcBeaconIndirectFireHexTerrain,
  },
  'semi-guided-tag-indirect-fire': {
    selectedWeaponIds: tacticalMapSemiGuidedTagIndirectFireSelectedWeaponIds,
    targetUnitId: tacticalMapSemiGuidedTagIndirectFireTargetId,
    tokens: tacticalMapSemiGuidedTagIndirectFireTokens,
    combatState: tacticalMapSemiGuidedTagIndirectFireCombatState,
    selectedHex,
    hexTerrain: tacticalMapSemiGuidedTagIndirectFireHexTerrain,
  },
} as const;
