/**
 * Campaign Command Extensions
 *
 * Optional fields the command-tier campaign UI (CP2b —
 * `add-campaign-command-ui`) reads off the live `ICampaign`. Modelled on
 * `IInventoryCampaignExtensions` (CP1) — the extension is additive and
 * absent on existing campaigns, so every command selector degrades
 * gracefully to an empty projection.
 *
 * Three additive fields:
 *  - `loans` — the campaign's loan ledger (design D4). Loan repayment
 *    reuses the existing daily-cost pipeline; this is the only new data.
 *  - `personnelMarket` — the current hiring-pool offers the Personnel &
 *    Hiring page renders (design D2). Generated by `personnelMarketProcessor`
 *    in the day pipeline and surfaced to the UI here.
 *  - `contractMarket` — the current contract-market offers the Contract
 *    Market page renders (design D5), plus the ids of offers the player
 *    has declined this market cycle so the page can hide them.
 *
 * @spec openspec/changes/add-campaign-command-ui/specs/campaign-command-ui/spec.md
 * @module campaign/CampaignCommandExtensions
 */

import type { ICampaign } from './Campaign';
import type { ICampaignLoan } from './CampaignLoan';
import type {
  IPersonnelMarketOffer,
  IUnitMarketOffer,
} from './markets/marketTypes';
import type { IContract } from './Mission';

/**
 * The current contract-market state surfaced to the Contract Market page.
 * `declinedOfferIds` records the offers the player declined this cycle —
 * they stay hidden until the next `contractMarketProcessor` refresh
 * replaces the `offers` list (design D5 / open question).
 */
export interface ICampaignContractMarket {
  /** Current contract offers on the market. */
  readonly offers: readonly IContract[];

  /** Ids of offers the player declined this market cycle. */
  readonly declinedOfferIds: readonly string[];
}

/**
 * Optional command-tier fields attached to the campaign. Every field is
 * optional so a campaign that has never opened a command surface still
 * type-checks; selectors default each to an empty projection.
 */
export interface ICampaignCommandExtensions {
  /** The campaign's loan ledger (design D4). */
  readonly loans?: readonly ICampaignLoan[];

  /** Current personnel-market hiring offers (design D2). */
  readonly personnelMarket?: readonly IPersonnelMarketOffer[];

  /** Current contract-market state (design D5). */
  readonly contractMarket?: ICampaignContractMarket;

  /**
   * Current unit-market offers (audit D-7, 2026-06-09 remediation W3.4).
   *
   * Written by `unitMarketProcessor` on its monthly refresh so the
   * generated offers are no longer discarded. No command-UI page reads
   * this yet — the field exists so the refresh the day report announces
   * is real, persisted state a future Unit Market page can render.
   */
  readonly unitMarket?: readonly IUnitMarketOffer[];
}

/** `ICampaign` widened with the optional command-tier extension fields. */
export type ICampaignWithCommand = ICampaign & ICampaignCommandExtensions;
