/**
 * Unit Combat State — per-unit damage carry-over between battles
 *
 * NOTE: This file is the Wave 2 (post-battle-processor) contract.
 * Sub-Branch 3b (repair queue) declares the minimal shape it needs
 * here so the repair builder is self-contained. When Wave 2 ships a
 * fuller implementation, integration is a matter of unifying the
 * field set — additive only.
 *
 * @module types/campaign/UnitCombatState
 */

/**
 * One destroyed component on a unit (e.g., a weapon, a heat sink, an
 * actuator). Generated by the post-battle processor from
 * `ICombatOutcome.unitDeltas[].destroyedComponents` and persisted on
 * `IUnitCombatState.destroyedComponents`.
 */
export interface IDestroyedComponent {
  /** Mech location (e.g., 'LT', 'CT', 'RA') */
  readonly location: string;
  /** Component name (e.g., 'AC/20', 'Medium Laser', 'Heat Sink') */
  readonly componentName: string;
  /** Optional slot index for crit-by-crit tracking */
  readonly slotIndex?: number;
}

/**
 * Persistent post-battle damage state for a single unit.
 *
 * Wave 2 owns persistence (writes from `ICombatOutcome.unitDeltas[]`).
 * Wave 3b (this branch) reads it to build repair tickets.
 *
 * `combatReady` is `false` while any structural damage or destroyed
 * critical component prevents redeployment.
 */
export interface IUnitCombatState {
  /** Unit being tracked */
  readonly unitId: string;

  /** Armor remaining per location (e.g., { LT: 18, CT: 25, ... }) */
  readonly currentArmorPerLocation: Record<string, number>;

  /** Structure remaining per location */
  readonly currentStructurePerLocation: Record<string, number>;

  /** Locations entirely destroyed (empty if none) */
  readonly destroyedLocations: readonly string[];

  /** Components destroyed by crits (e.g., AC/20 in RT, Engine in CT) */
  readonly destroyedComponents: readonly IDestroyedComponent[];

  /** Heat at the end of the last engagement */
  readonly heatEnd: number;

  /** Ammo remaining per bin (e.g., { 'ac20-rt': 4, 'srm6-lt': 12 }) */
  readonly ammoRemaining: Record<string, number>;

  /** False while damage prevents redeployment */
  readonly combatReady: boolean;

  /** Last combat outcome that updated this state */
  readonly lastCombatOutcomeId: string | null;

  /** ISO 8601 timestamp of the last update */
  readonly lastUpdated: string | null;
}

/**
 * Maximum (full-health) state of a unit, used by the repair builder
 * to compute deltas vs current state.
 */
export interface IUnitMaxState {
  readonly unitId: string;
  readonly maxArmorPerLocation: Record<string, number>;
  readonly maxStructurePerLocation: Record<string, number>;
  readonly maxAmmoPerBin: Record<string, number>;
}
