import Link from 'next/link';

const glossaryTerms = [
  {
    term: 'Battle Value',
    aliases: 'BV',
    definition:
      'A numeric rating for unit combat power, used to compare and balance forces before a battle.',
  },
  {
    term: 'Gunnery',
    definition:
      'The pilot skill used for ranged attacks. Lower values are better and reduce the target number.',
  },
  {
    term: 'Piloting',
    definition:
      'The pilot skill used for control checks, falls, and other handling tests. Lower values are better.',
  },
  {
    term: 'Heat',
    definition:
      'Waste heat generated by movement and weapons. High heat can slow, shut down, or damage a unit.',
  },
  {
    term: 'Piloting-skill-roll',
    aliases: 'PSR',
    definition:
      'A control check rolled against piloting skill when damage, movement, or battlefield events threaten stability.',
  },
];

export default function OnboardingPage(): React.ReactElement {
  return (
    <main className="from-surface-deep via-surface-base to-surface-deep min-h-screen bg-gradient-to-br px-6 py-10">
      <div className="mx-auto max-w-5xl">
        <Link
          href="/"
          className="text-text-theme-secondary hover:text-accent text-sm transition-colors"
        >
          Back to dashboard
        </Link>

        <section className="mt-6">
          <h1 className="text-text-theme-primary text-4xl font-bold">
            Onboarding
          </h1>
          <p className="text-text-theme-secondary mt-3 max-w-3xl leading-relaxed">
            Start with Quick Game to learn combat, use the Compendium and Unit
            Builder to inspect BattleMechs, then move into Campaigns when you
            want persistent pilots, repairs, contracts, and money pressure.
          </p>
        </section>

        <section className="mt-10 grid gap-4 md:grid-cols-3">
          {[
            {
              title: 'Build or Browse',
              text: 'Use the Compendium for canonical units and Unit Builder for custom variants.',
            },
            {
              title: 'Play a Skirmish',
              text: 'Quick Game can auto-resolve or launch a playable hex-board skirmish.',
            },
            {
              title: 'Run a Campaign',
              text: 'Campaigns add roster, repair, finance, contract, and time pressure.',
            },
          ].map((card) => (
            <article
              key={card.title}
              className="border-border-theme-subtle bg-surface-base/50 rounded-lg border p-5"
            >
              <h2 className="text-text-theme-primary text-lg font-semibold">
                {card.title}
              </h2>
              <p className="text-text-theme-secondary mt-2 text-sm leading-relaxed">
                {card.text}
              </p>
            </article>
          ))}
        </section>

        <section className="mt-10">
          <h2 className="text-text-theme-primary text-2xl font-semibold">
            Glossary
          </h2>
          <dl className="mt-4 grid gap-4 md:grid-cols-2">
            {glossaryTerms.map((entry) => (
              <div
                key={entry.term}
                className="border-border-theme-subtle bg-surface-base/50 rounded-lg border p-5"
              >
                <dt className="text-accent text-lg font-semibold">
                  {entry.term}
                  {entry.aliases && (
                    <span className="text-text-theme-secondary ml-2 text-sm">
                      ({entry.aliases})
                    </span>
                  )}
                </dt>
                <dd className="text-text-theme-secondary mt-2 text-sm leading-relaxed">
                  {entry.definition}
                </dd>
              </div>
            ))}
          </dl>
        </section>
      </div>
    </main>
  );
}
