import type { IRandomAssignmentTable } from './ratTypes';

import { Era, Faction, FACTION_NAMES, UnitTypeCategory } from './ratTypes';

export const CW_CLAN_INVASION_RAT: IRandomAssignmentTable = {
  faction: Faction.CLAN_WOLF,
  factionName: FACTION_NAMES[Faction.CLAN_WOLF],
  era: Era.CLAN_INVASION,
  entries: [
    {
      chassis: 'Dire Wolf',
      variant: 'Prime',
      designation: 'Dire Wolf Prime',
      bv: 2871,
      tonnage: 100,
      unitType: UnitTypeCategory.BattleMech,
      weight: 8,
    },
    {
      chassis: 'Gargoyle',
      variant: 'Prime',
      designation: 'Gargoyle Prime',
      bv: 1682,
      tonnage: 80,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
    {
      chassis: 'Timber Wolf',
      variant: 'Prime',
      designation: 'Timber Wolf Prime',
      bv: 2737,
      tonnage: 75,
      unitType: UnitTypeCategory.BattleMech,
      weight: 20,
    },
    {
      chassis: 'Hellbringer',
      variant: 'Prime',
      designation: 'Hellbringer Prime',
      bv: 2414,
      tonnage: 65,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Stormcrow',
      variant: 'Prime',
      designation: 'Stormcrow Prime',
      bv: 2031,
      tonnage: 55,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Nova',
      variant: 'Prime',
      designation: 'Nova Prime',
      bv: 1841,
      tonnage: 50,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Kit Fox',
      variant: 'Prime',
      designation: 'Kit Fox Prime',
      bv: 1085,
      tonnage: 30,
      unitType: UnitTypeCategory.BattleMech,
      weight: 14,
    },
    {
      chassis: 'Mist Lynx',
      variant: 'Prime',
      designation: 'Mist Lynx Prime',
      bv: 888,
      tonnage: 25,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
  ],
  totalWeight: 114,
};

export const FS_CLAN_INVASION_RAT: IRandomAssignmentTable = {
  faction: Faction.FEDERATED_SUNS,
  factionName: FACTION_NAMES[Faction.FEDERATED_SUNS],
  era: Era.CLAN_INVASION,
  entries: [
    {
      chassis: 'Victor',
      variant: 'VTR-9B',
      designation: 'Victor VTR-9B',
      bv: 1296,
      tonnage: 80,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Battlemaster',
      variant: 'BLR-1G',
      designation: 'Battlemaster BLR-1G',
      bv: 1519,
      tonnage: 85,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
    {
      chassis: 'JagerMech',
      variant: 'JM6-S',
      designation: 'JagerMech JM6-S',
      bv: 930,
      tonnage: 65,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Axman',
      variant: 'AXM-1N',
      designation: 'Axman AXM-1N',
      bv: 1075,
      tonnage: 65,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Hatchetman',
      variant: 'HCT-3F',
      designation: 'Hatchetman HCT-3F',
      bv: 851,
      tonnage: 45,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
    {
      chassis: 'Centurion',
      variant: 'CN9-A',
      designation: 'Centurion CN9-A',
      bv: 945,
      tonnage: 50,
      unitType: UnitTypeCategory.BattleMech,
      weight: 20,
    },
    {
      chassis: 'Wolfhound',
      variant: 'WLF-1',
      designation: 'Wolfhound WLF-1',
      bv: 954,
      tonnage: 35,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Valkyrie',
      variant: 'VLK-QA',
      designation: 'Valkyrie VLK-QA',
      bv: 723,
      tonnage: 30,
      unitType: UnitTypeCategory.BattleMech,
      weight: 16,
    },
    {
      chassis: 'Mongoose',
      variant: 'MON-67',
      designation: 'Mongoose MON-67',
      bv: 568,
      tonnage: 25,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
  ],
  totalWeight: 138,
};
