import type { IRandomAssignmentTable } from './ratTypes';

import { Era, Faction, FACTION_NAMES, UnitTypeCategory } from './ratTypes';

export const PIRATES_GENERIC_RAT: IRandomAssignmentTable = {
  faction: Faction.PIRATES,
  factionName: FACTION_NAMES[Faction.PIRATES],
  era: Era.LATE_SUCCESSION_WARS,
  entries: [
    {
      chassis: 'Awesome',
      variant: 'AWS-8Q',
      designation: 'Awesome AWS-8Q',
      bv: 1605,
      tonnage: 80,
      unitType: UnitTypeCategory.BattleMech,
      weight: 8,
    },
    {
      chassis: 'Marauder',
      variant: 'MAD-3R',
      designation: 'Marauder MAD-3R',
      bv: 1220,
      tonnage: 75,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Warhammer',
      variant: 'WHM-6R',
      designation: 'Warhammer WHM-6R',
      bv: 1299,
      tonnage: 70,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Thunderbolt',
      variant: 'TDR-5S',
      designation: 'Thunderbolt TDR-5S',
      bv: 1335,
      tonnage: 65,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
    {
      chassis: 'Wolverine',
      variant: 'WVR-6R',
      designation: 'Wolverine WVR-6R',
      bv: 1101,
      tonnage: 55,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Shadow Hawk',
      variant: 'SHD-2H',
      designation: 'Shadow Hawk SHD-2H',
      bv: 1064,
      tonnage: 55,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Phoenix Hawk',
      variant: 'PXH-1',
      designation: 'Phoenix Hawk PXH-1',
      bv: 1041,
      tonnage: 45,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Stinger',
      variant: 'STG-3R',
      designation: 'Stinger STG-3R',
      bv: 359,
      tonnage: 20,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Wasp',
      variant: 'WSP-1A',
      designation: 'Wasp WSP-1A',
      bv: 384,
      tonnage: 20,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Locust',
      variant: 'LCT-1V',
      designation: 'Locust LCT-1V',
      bv: 432,
      tonnage: 20,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
  ],
  totalWeight: 152,
};
