import type { IRandomAssignmentTable } from './ratTypes';

import { Era, Faction, FACTION_NAMES, UnitTypeCategory } from './ratTypes';

export const LC_SUCCESSION_WARS_RAT: IRandomAssignmentTable = {
  faction: Faction.LYRAN_COMMONWEALTH,
  factionName: FACTION_NAMES[Faction.LYRAN_COMMONWEALTH],
  era: Era.LATE_SUCCESSION_WARS,
  entries: [
    {
      chassis: 'Atlas',
      variant: 'AS7-D',
      designation: 'Atlas AS7-D',
      bv: 1897,
      tonnage: 100,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Banshee',
      variant: 'BNC-3E',
      designation: 'Banshee BNC-3E',
      bv: 1114,
      tonnage: 95,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
    {
      chassis: 'Zeus',
      variant: 'ZEU-6S',
      designation: 'Zeus ZEU-6S',
      bv: 1348,
      tonnage: 80,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Commando',
      variant: 'COM-2D',
      designation: 'Commando COM-2D',
      bv: 558,
      tonnage: 25,
      unitType: UnitTypeCategory.BattleMech,
      weight: 10,
    },
    {
      chassis: 'Griffin',
      variant: 'GRF-1N',
      designation: 'Griffin GRF-1N',
      bv: 1272,
      tonnage: 55,
      unitType: UnitTypeCategory.BattleMech,
      weight: 20,
    },
    {
      chassis: 'Hunchback',
      variant: 'HBK-4G',
      designation: 'Hunchback HBK-4G',
      bv: 1067,
      tonnage: 50,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Orion',
      variant: 'ON1-K',
      designation: 'Orion ON1-K',
      bv: 1429,
      tonnage: 75,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Wolverine',
      variant: 'WVR-6R',
      designation: 'Wolverine WVR-6R',
      bv: 1101,
      tonnage: 55,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Enforcer',
      variant: 'ENF-4R',
      designation: 'Enforcer ENF-4R',
      bv: 1031,
      tonnage: 50,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Commando',
      variant: 'COM-2D',
      designation: 'Commando COM-2D',
      bv: 558,
      tonnage: 25,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
    {
      chassis: 'Jenner',
      variant: 'JR7-D',
      designation: 'Jenner JR7-D',
      bv: 875,
      tonnage: 35,
      unitType: UnitTypeCategory.BattleMech,
      weight: 10,
    },
  ],
  totalWeight: 163,
};

export const DC_SUCCESSION_WARS_RAT: IRandomAssignmentTable = {
  faction: Faction.DRACONIS_COMBINE,
  factionName: FACTION_NAMES[Faction.DRACONIS_COMBINE],
  era: Era.LATE_SUCCESSION_WARS,
  entries: [
    {
      chassis: 'Atlas',
      variant: 'AS7-D',
      designation: 'Atlas AS7-D',
      bv: 1897,
      tonnage: 100,
      unitType: UnitTypeCategory.BattleMech,
      weight: 10,
    },
    {
      chassis: 'Stalker',
      variant: 'STK-3F',
      designation: 'Stalker STK-3F',
      bv: 1559,
      tonnage: 85,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
    {
      chassis: 'Dragon',
      variant: 'DRG-1N',
      designation: 'Dragon DRG-1N',
      bv: 1125,
      tonnage: 60,
      unitType: UnitTypeCategory.BattleMech,
      weight: 25,
    },
    {
      chassis: 'Quickdraw',
      variant: 'QKD-4G',
      designation: 'Quickdraw QKD-4G',
      bv: 1192,
      tonnage: 60,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Grand Dragon',
      variant: 'DRG-1G',
      designation: 'Grand Dragon DRG-1G',
      bv: 1305,
      tonnage: 60,
      unitType: UnitTypeCategory.BattleMech,
      weight: 18,
    },
    {
      chassis: 'Panther',
      variant: 'PNT-9R',
      designation: 'Panther PNT-9R',
      bv: 769,
      tonnage: 35,
      unitType: UnitTypeCategory.BattleMech,
      weight: 20,
    },
    {
      chassis: 'Jenner',
      variant: 'JR7-D',
      designation: 'Jenner JR7-D',
      bv: 875,
      tonnage: 35,
      unitType: UnitTypeCategory.BattleMech,
      weight: 22,
    },
    {
      chassis: 'Locust',
      variant: 'LCT-1V',
      designation: 'Locust LCT-1V',
      bv: 432,
      tonnage: 20,
      unitType: UnitTypeCategory.BattleMech,
      weight: 15,
    },
    {
      chassis: 'Wasp',
      variant: 'WSP-1A',
      designation: 'Wasp WSP-1A',
      bv: 384,
      tonnage: 20,
      unitType: UnitTypeCategory.BattleMech,
      weight: 12,
    },
  ],
  totalWeight: 149,
};
