import type { InteractiveSession } from '@/engine/GameEngine';
import type {
  Facing,
  IAttackIntentState,
  IGameSession,
  IGameplayUIState,
  IHexCoordinate,
  IWeaponStatus,
  MovementType,
  PhysicalAttackINarcPodSelection,
  WeaponFireMode,
} from '@/types/gameplay';
import type {
  PhysicalAttackLimb,
  PhysicalAttackType,
} from '@/utils/gameplay/physicalAttacks/types';

import type { InteractivePhase } from './useGameplayStore.helpers';

/**
 * Per `add-combat-phase-ui-flows`: structured plan the player builds
 * in the Movement-phase action panel before committing.
 */
export interface IPlannedMovement {
  readonly unitId?: string;
  readonly destination: IHexCoordinate;
  readonly facing: Facing;
  readonly movementType: MovementType;
  readonly path: readonly IHexCoordinate[];
  /** Rules-backed MP cost from the movement projection / engine validation. */
  readonly mpCost?: number;
  /** Rules-backed heat generated by this movement preview. */
  readonly heatGenerated?: number;
  /** Represented conversion steps reserved before movement path steps. */
  readonly conversionStepCount?: number;
  /** Represented conversion MP reserved before movement path steps. */
  readonly conversionMpCost?: number;
  /** Represented altitude-control steps reserved before movement path steps. */
  readonly altitudeControlStepCount?: number;
  /** Represented altitude-control MP reserved before movement path steps. */
  readonly altitudeControlMpCost?: number;
  /** Rules-level movement mode used for terrain/elevation pathing. */
  readonly movementMode?: string;
  /** Terrain modifier paid on the final step into the destination hex. */
  readonly terrainCost?: number;
  /** MP charged for facing changes along the projected path. */
  readonly turningCost?: number;
  /** Elevation delta from the previous path hex into the destination hex. */
  readonly elevationDelta?: number;
  /** Elevation MP paid on the final step into the destination hex. */
  readonly elevationCost?: number;
}

/**
 * Per `add-combat-phase-ui-flows`: structured plan the player builds
 * in the Attack-phase action panel before firing.
 */
export interface IAttackPlan {
  readonly targetUnitId: string | null;
  readonly selectedWeapons: readonly string[];
  readonly weaponModeError?: string | null;
}

/**
 * Per `add-physical-attack-phase-ui`: structured plan the player builds
 * in the Physical-Attack-phase action panel before declaring a melee
 * attack. Mirrors `IAttackPlan` shape but holds an attack-type pick
 * instead of a weapon-id queue (physical attacks resolve as a single
 * action, not a multi-weapon volley). `null` when no target / type are
 * set yet; the panel renders an empty state in that case.
 */
export interface IPhysicalAttackPlan {
  readonly targetUnitId: string | null;
  readonly attackType: PhysicalAttackType | null;
  readonly limb: PhysicalAttackLimb | null;
  readonly twoHandedZweihander: boolean;
  readonly forecastRequestId?: number;
  readonly selectedINarcPod?: PhysicalAttackINarcPodSelection;
}

/**
 * Minimal slice of the gameplay store the combat-flow helpers need.
 */
export interface CombatFlowsSlice {
  session: IGameSession | null;
  interactiveSession: InteractiveSession | null;
  ui: IGameplayUIState;
  plannedMovement: IPlannedMovement | null;
  attackPlan: IAttackPlan;
  attackIntent: IAttackIntentState;
  weaponModesByUnitId: Record<string, Readonly<Record<string, WeaponFireMode>>>;
  unitWeapons: Record<string, readonly IWeaponStatus[]>;
  interactivePhase: InteractivePhase;
  validMovementHexes: readonly { q: number; r: number }[];
  validTargetIds: readonly string[];
  hitChance: number | null;
}

export type SetFn = {
  (partial: Partial<CombatFlowsSlice>): void;
  (fn: (state: CombatFlowsSlice) => Partial<CombatFlowsSlice>): void;
};

export type GetFn = () => CombatFlowsSlice;
