/**
 * Movement-phase + Attack-phase planning helpers extracted from
 * `useGameplayStore` per `add-combat-phase-ui-flows`.
 *
 * Lives outside the main store file so the store stays under the
 * project's per-file line budget while keeping the planning state +
 * commit handshakes co-located.
 *
 * The functions take Zustand's `set` / `get` directly (typed with the
 * minimal slices they actually touch) so the store can compose them
 * without boilerplate.
 */

import { create } from 'zustand';

import type { InteractiveSession } from '@/engine/GameEngine';
import type { IRuntimeMovementStateChangedPayload } from '@/types/gameplay/GameSessionMovementEvents';
import type {
  IPhysicalAttackInput,
  PhysicalAttackLimb,
  PhysicalAttackType,
} from '@/utils/gameplay/physicalAttacks/types';

import { getPrefersReducedMotion } from '@/hooks/useReducedMotion';
import {
  Facing,
  GamePhase,
  GameEventType,
  IHexCoordinate,
  IGameSession,
  IGameplayUIState,
  IWeaponStatus,
  IMovementDeclaredPayload,
  MovementAnimationMode,
  MovementType,
  type PhysicalAttackINarcPodSelection,
  WeaponFireMode,
  type StandUpMode,
} from '@/types/gameplay';
import { declarePhysicalAttack } from '@/utils/gameplay/gameSession';
import { isZweihanderPhysicalAttackType } from '@/utils/gameplay/physicalAttacks/types';

import { useAnimationQueue } from './useAnimationQueue';
import { InteractivePhase } from './useGameplayStore.helpers';

export {
  clearAttackPlanLogic,
  commitAttackLogic,
  setAttackTargetLogic,
  setPlannedWeaponModeLogic,
  togglePlannedWeaponLogic,
} from './useGameplayStore.attackPlan';

/**
 * Per `add-combat-phase-ui-flows`: structured plan the player builds
 * in the Movement-phase action panel before committing.
 */
export interface IPlannedMovement {
  readonly unitId?: string;
  readonly destination: IHexCoordinate;
  readonly facing: Facing;
  readonly movementType: MovementType;
  readonly path: readonly IHexCoordinate[];
  /** Rules-backed MP cost from the movement projection / engine validation. */
  readonly mpCost?: number;
  /** Rules-backed heat generated by this movement preview. */
  readonly heatGenerated?: number;
  /** Represented conversion steps reserved before movement path steps. */
  readonly conversionStepCount?: number;
  /** Represented conversion MP reserved before movement path steps. */
  readonly conversionMpCost?: number;
  /** Represented altitude-control steps reserved before movement path steps. */
  readonly altitudeControlStepCount?: number;
  /** Represented altitude-control MP reserved before movement path steps. */
  readonly altitudeControlMpCost?: number;
  /** Rules-level movement mode used for terrain/elevation pathing. */
  readonly movementMode?: string;
  /** Terrain modifier paid on the final step into the destination hex. */
  readonly terrainCost?: number;
  /** Elevation delta from the previous path hex into the destination hex. */
  readonly elevationDelta?: number;
  /** Elevation MP paid on the final step into the destination hex. */
  readonly elevationCost?: number;
}

/**
 * Per `add-combat-phase-ui-flows`: structured plan the player builds
 * in the Attack-phase action panel before firing.
 */
export interface IAttackPlan {
  readonly targetUnitId: string | null;
  readonly selectedWeapons: readonly string[];
  readonly weaponModeError?: string | null;
}

/**
 * Per `add-physical-attack-phase-ui`: structured plan the player builds
 * in the Physical-Attack-phase action panel before declaring a melee
 * attack. Mirrors `IAttackPlan` shape but holds an attack-type pick
 * instead of a weapon-id queue (physical attacks resolve as a single
 * action, not a multi-weapon volley). `null` when no target / type are
 * set yet — the panel renders an empty state in that case.
 */
export interface IPhysicalAttackPlan {
  readonly targetUnitId: string | null;
  readonly attackType: PhysicalAttackType | null;
  readonly limb: PhysicalAttackLimb | null;
  readonly twoHandedZweihander: boolean;
  readonly selectedINarcPod?: PhysicalAttackINarcPodSelection;
}

/**
 * Minimal slice of the gameplay store the combat-flow helpers need.
 */
export interface CombatFlowsSlice {
  session: IGameSession | null;
  interactiveSession: InteractiveSession | null;
  ui: IGameplayUIState;
  plannedMovement: IPlannedMovement | null;
  attackPlan: IAttackPlan;
  weaponModesByUnitId: Record<string, Readonly<Record<string, WeaponFireMode>>>;
  unitWeapons: Record<string, readonly IWeaponStatus[]>;
  interactivePhase: InteractivePhase;
  validMovementHexes: readonly { q: number; r: number }[];
  validTargetIds: readonly string[];
  hitChance: number | null;
}

export type SetFn = {
  (partial: Partial<CombatFlowsSlice>): void;
  (fn: (state: CombatFlowsSlice) => Partial<CombatFlowsSlice>): void;
};
export type GetFn = () => CombatFlowsSlice;

// ---------------------------------------------------------------------------
// Movement-phase planning helpers
// ---------------------------------------------------------------------------

export function setPlannedMovementLogic(
  plan: IPlannedMovement,
  set: SetFn,
): void {
  set({ plannedMovement: plan });
}

export function clearPlannedMovementLogic(set: SetFn): void {
  set({ plannedMovement: null });
}

/**
 * Apply the planned move to the interactive session (emits
 * `MovementDeclared` + `MovementLocked` events) and clear the plan.
 * No-op when session / plan / selected unit are missing.
 */
export function commitPlannedMovementLogic(get: GetFn, set: SetFn): void {
  const { interactiveSession, plannedMovement, ui } = get();
  if (!interactiveSession || !plannedMovement || !ui.selectedUnitId) return;
  if (plannedMovement.unitId && plannedMovement.unitId !== ui.selectedUnitId) {
    set({ plannedMovement: null });
    return;
  }
  const unitId = ui.selectedUnitId;
  const beforeSession = interactiveSession.getSession();
  const beforeEventCount = beforeSession.events.length;
  const initialFacing =
    beforeSession.currentState.units[unitId]?.facing ?? plannedMovement.facing;

  interactiveSession.applyMovement(
    unitId,
    plannedMovement.destination,
    plannedMovement.facing,
    plannedMovement.movementType,
    plannedMovement.path,
  );
  const nextSession = interactiveSession.getSession();
  if (!hasNewMovementDeclaredEvent(nextSession, unitId, beforeEventCount)) {
    set({ session: nextSession });
    return;
  }

  enqueueCommittedMovementAnimation({
    session: nextSession,
    unitId,
    initialFacing,
    fallbackPath: plannedMovement.path,
    fallbackMode: plannedMovement.movementType,
  });

  set({
    session: nextSession,
    interactivePhase: InteractivePhase.SelectUnit,
    plannedMovement: null,
    validMovementHexes: [],
    ui: { ...get().ui, selectedUnitId: null },
  });
}

function hasNewMovementDeclaredEvent(
  session: IGameSession,
  unitId: string,
  startIndex: number,
): boolean {
  return session.events.slice(startIndex).some((event) => {
    if (event.type !== GameEventType.MovementDeclared) return false;
    const payload = event.payload as IMovementDeclaredPayload;
    return payload.unitId === unitId;
  });
}

/**
 * Commit a standalone stand-up/posture-exit action for the selected prone or
 * hull-down unit through the same movement validator used by normal map
 * movement. This declares a zero-hex Walk move at the unit's current position
 * so MP, invalid events, locking, and state replay stay on the movement event
 * path.
 */
export function standActiveUnitLogic(
  get: GetFn,
  set: SetFn,
  standUpMode: StandUpMode = 'normal',
): void {
  const { interactiveSession, ui } = get();
  if (!interactiveSession || !ui.selectedUnitId) return;

  const unitId = ui.selectedUnitId;
  const beforeSession = interactiveSession.getSession();
  const unitState = beforeSession.currentState.units[unitId];
  if (!unitState?.prone && !unitState?.hullDown) return;

  const beforeEventCount = beforeSession.events.length;
  interactiveSession.applyMovement(
    unitId,
    unitState.position,
    unitState.facing,
    MovementType.Walk,
    [unitState.position],
    standUpMode,
  );

  const nextSession = interactiveSession.getSession();
  const declared = nextSession.events
    .slice(beforeEventCount)
    .some((event) => event.type === GameEventType.MovementDeclared);

  if (!declared) {
    set({ session: nextSession, plannedMovement: null });
    return;
  }

  set({
    session: nextSession,
    interactivePhase: InteractivePhase.SelectUnit,
    plannedMovement: null,
    validMovementHexes: [],
    ui: { ...get().ui, selectedUnitId: null },
  });
}

/**
 * Commit MegaMek's standing HULL_DOWN posture transition as a same-hex
 * walking movement declaration. The engine owns MP/heat legality and rejects
 * non-Mek-style or damaged-gyro branches before state changes.
 */
export function enterHullDownActiveUnitLogic(get: GetFn, set: SetFn): void {
  const { interactiveSession, ui } = get();
  if (!interactiveSession || !ui.selectedUnitId) return;

  const unitId = ui.selectedUnitId;
  const beforeSession = interactiveSession.getSession();
  const unitState = beforeSession.currentState.units[unitId];
  if (!unitState || unitState.prone === true || unitState.hullDown === true) {
    return;
  }

  const beforeEventCount = beforeSession.events.length;
  interactiveSession.applyMovement(
    unitId,
    unitState.position,
    unitState.facing,
    MovementType.Walk,
    [unitState.position],
    undefined,
    { hullDownEntryAttempt: true },
  );

  const nextSession = interactiveSession.getSession();
  const declared = nextSession.events
    .slice(beforeEventCount)
    .some((event) => event.type === GameEventType.MovementDeclared);

  if (!declared) {
    set({ session: nextSession, plannedMovement: null });
    return;
  }

  set({
    session: nextSession,
    interactivePhase: InteractivePhase.SelectUnit,
    plannedMovement: null,
    validMovementHexes: [],
    ui: { ...get().ui, selectedUnitId: null },
  });
}

/**
 * Commit MegaMek's 0 MP GO_PRONE posture transition from hull-down to prone.
 * This uses `MovementDeclared` so replay, lock-state, and map state all share
 * the same authoritative path as ordinary movement actions.
 */
export function goProneActiveUnitLogic(get: GetFn, set: SetFn): void {
  const { interactiveSession, ui } = get();
  if (!interactiveSession || !ui.selectedUnitId) return;

  const unitId = ui.selectedUnitId;
  const beforeSession = interactiveSession.getSession();
  const unitState = beforeSession.currentState.units[unitId];
  if (unitState?.hullDown !== true || unitState.prone === true) return;

  const beforeEventCount = beforeSession.events.length;
  interactiveSession.applyMovement(
    unitId,
    unitState.position,
    unitState.facing,
    MovementType.Stationary,
    [unitState.position],
    undefined,
    { goProneAttempt: true },
  );

  const nextSession = interactiveSession.getSession();
  const declared = nextSession.events
    .slice(beforeEventCount)
    .some((event) => event.type === GameEventType.MovementDeclared);

  if (!declared) {
    set({ session: nextSession, plannedMovement: null });
    return;
  }

  set({
    session: nextSession,
    interactivePhase: InteractivePhase.SelectUnit,
    plannedMovement: null,
    validMovementHexes: [],
    ui: { ...get().ui, selectedUnitId: null },
  });
}

/**
 * Commit a runtime movement-state change for the selected unit without
 * locking movement. Conversion and infantry mount/dismount controls use this
 * to force the same replayable state event consumed by movement projection and
 * commit validation, then keep the unit selected so the map immediately
 * recomputes the overlay in the new mode.
 */
export function applyRuntimeMovementStateForSelectedUnitLogic(
  get: GetFn,
  set: SetFn,
  patch: Omit<IRuntimeMovementStateChangedPayload, 'unitId'>,
): void {
  const { interactiveSession, ui } = get();
  if (!interactiveSession || !ui.selectedUnitId) return;

  const unitId = ui.selectedUnitId;
  const beforeSession = interactiveSession.getSession();
  if (!beforeSession.currentState.units[unitId]) return;

  interactiveSession.applyRuntimeMovementState(unitId, patch);
  const nextSession = interactiveSession.getSession();
  const validMoves = interactiveSession.getAvailableActions(unitId).validMoves;

  set({
    session: nextSession,
    interactivePhase: InteractivePhase.SelectMovement,
    plannedMovement: null,
    validMovementHexes: validMoves,
    ui: { ...get().ui, selectedUnitId: unitId },
  });
}

function enqueueCommittedMovementAnimation(args: {
  readonly session: IGameSession;
  readonly unitId: string;
  readonly initialFacing: Facing;
  readonly fallbackPath: readonly IHexCoordinate[];
  readonly fallbackMode: MovementType;
}): void {
  if (getPrefersReducedMotion()) return;

  const movementEvent = findLatestMovementDeclaredEvent(
    args.session,
    args.unitId,
  );
  if (!movementEvent) return;

  const payload = movementEvent.payload as IMovementDeclaredPayload;
  const path = payload.path ?? args.fallbackPath;
  const mode = payload.mode ?? movementAnimationModeForType(args.fallbackMode);
  if (!mode || path.length <= 1) return;

  useAnimationQueue.getState().enqueue({
    id: `movement-${movementEvent.id}`,
    mapId: args.session.id,
    unitId: args.unitId,
    kind: 'movement',
    path,
    occupiedHexes: path,
    mode,
    initialFacing: args.initialFacing,
    finalFacing: payload.facing,
    eventSequence: movementEvent.sequence,
  });
}

function findLatestMovementDeclaredEvent(
  session: IGameSession,
  unitId: string,
) {
  for (let index = session.events.length - 1; index >= 0; index -= 1) {
    const event = session.events[index];
    if (event.type !== GameEventType.MovementDeclared) continue;
    const payload = event.payload as IMovementDeclaredPayload;
    if (payload.unitId === unitId) return event;
  }
  return null;
}

function movementAnimationModeForType(
  movementType: MovementType,
): MovementAnimationMode | null {
  switch (movementType) {
    case MovementType.Walk:
    case MovementType.Run:
    case MovementType.Jump:
      return movementType;
    default:
      return null;
  }
}

// ---------------------------------------------------------------------------
// Physical-Attack-phase planning store (per `add-physical-attack-phase-ui`)
// ---------------------------------------------------------------------------

/**
 * Per `add-physical-attack-phase-ui`: contract the physical-attack
 * panel + forecast modal subscribe to. Lives in its own Zustand store
 * (rather than as a slice on `useGameplayStore`) so the panel can
 * snapshot + clear plans without forcing edits to the main store
 * file. The commit action takes a callback the caller wires to
 * `useGameplayStore.setSession` so the underlying session refresh
 * stays a one-way data-flow.
 */
export interface IPhysicalAttackPlanState {
  /** Current draft plan; empty sentinel `{null,null}` when nothing picked. */
  readonly physicalAttackPlan: IPhysicalAttackPlan;
  /** Target-lock setter — mirrors `setAttackTarget` for the weapon flow. */
  setPhysicalAttackTarget: (unitId: string | null) => void;
  /** Stash the chosen attack type. */
  setPhysicalAttackType: (
    attackType: PhysicalAttackType | null,
    limb?: PhysicalAttackLimb | null,
  ) => void;
  /** Explicit two-handed Zweihander declaration for represented physical attacks. */
  setPhysicalAttackTwoHandedZweihander: (enabled: boolean) => void;
  /** Optional Brush-Off iNARC pod identity selected from the target carrier. */
  setPhysicalAttackINarcPod: (
    pod: PhysicalAttackINarcPodSelection | undefined,
  ) => void;
  /** Reset back to `{targetUnitId: null, attackType: null}`. */
  clearPhysicalAttackPlan: () => void;
  /**
   * Commit the plan via `declarePhysicalAttack`. Returns the updated
   * `IGameSession` (so callers can re-seed `useGameplayStore.session`)
   * or `null` when any required slice is missing.
   */
  commitPhysicalAttack: (
    args: ICommitPhysicalAttackArgs,
  ) => IGameSession | null;
}

/**
 * Per `add-physical-attack-phase-ui`: snapshot the panel passes to
 * `commitPhysicalAttack` so the standalone store doesn't need to read
 * from `useGameplayStore` directly (avoids a circular import). All
 * fields are looked up by the panel from `useGameplayStore` selectors
 * + the unit catalog the `GameplayPage` already loads.
 */
export interface ICommitPhysicalAttackArgs {
  readonly interactiveSession: InteractiveSession;
  readonly attackerId: string;
  readonly attackerPiloting: number;
  readonly attackerTonnage?: number;
  readonly targetTonnage?: number;
  readonly attackerUnitType?: IPhysicalAttackInput['attackerUnitType'];
  readonly attackerMovementMode?: IPhysicalAttackInput['attackerMovementMode'];
  readonly optionalRules?: IPhysicalAttackInput['optionalRules'];
  readonly targetUnitType?: IPhysicalAttackInput['targetUnitType'];
  readonly hexesMoved?: number;
  readonly attackerRanThisTurn?: boolean;
  readonly attackerJumpedThisTurn?: boolean;
  readonly weaponsFiredFromLeftArm?: readonly string[];
  readonly weaponsFiredFromRightArm?: readonly string[];
  readonly elevationContext?: IPhysicalAttackInput['elevationContext'];
  readonly terrainContext?: IPhysicalAttackInput['terrainContext'];
}

const EMPTY_PHYSICAL_PLAN: IPhysicalAttackPlan = {
  targetUnitId: null,
  attackType: null,
  limb: null,
  twoHandedZweihander: false,
};

/**
 * Per `add-physical-attack-phase-ui`: dedicated Zustand hook for the
 * physical-attack draft plan. Kept side-by-side with the weapon-attack
 * helpers so reviewers can diff the two flows in one screen, but
 * implemented as a separate store so we don't need to widen
 * `useGameplayStore`'s typed shape (the orchestrator brief
 * intentionally scopes us out of `useGameplayStore.ts`).
 */
export const usePhysicalAttackPlanStore = create<IPhysicalAttackPlanState>(
  (set) => ({
    physicalAttackPlan: EMPTY_PHYSICAL_PLAN,

    setPhysicalAttackTarget: (unitId) =>
      set((state) => {
        const { selectedINarcPod: _selectedINarcPod, ...basePlan } =
          state.physicalAttackPlan;
        return {
          physicalAttackPlan: {
            ...basePlan,
            targetUnitId: unitId,
          },
        };
      }),

    setPhysicalAttackType: (attackType, limb = null) =>
      set((state) => {
        const { selectedINarcPod, ...basePlan } = state.physicalAttackPlan;
        const nextPlan: IPhysicalAttackPlan = {
          ...basePlan,
          attackType,
          limb,
          twoHandedZweihander: isZweihanderPhysicalAttackType(attackType)
            ? state.physicalAttackPlan.twoHandedZweihander
            : false,
        };
        if (attackType === 'brush-off' && selectedINarcPod !== undefined) {
          return {
            physicalAttackPlan: {
              ...nextPlan,
              selectedINarcPod,
            },
          };
        }
        return { physicalAttackPlan: nextPlan };
      }),

    setPhysicalAttackTwoHandedZweihander: (enabled) =>
      set((state) => ({
        physicalAttackPlan: {
          ...state.physicalAttackPlan,
          twoHandedZweihander: isZweihanderPhysicalAttackType(
            state.physicalAttackPlan.attackType,
          )
            ? enabled
            : false,
        },
      })),

    setPhysicalAttackINarcPod: (pod) =>
      set((state) => {
        const { selectedINarcPod: _selectedINarcPod, ...basePlan } =
          state.physicalAttackPlan;
        return {
          physicalAttackPlan:
            pod === undefined
              ? basePlan
              : { ...basePlan, selectedINarcPod: pod },
        };
      }),

    clearPhysicalAttackPlan: () =>
      set({ physicalAttackPlan: EMPTY_PHYSICAL_PLAN }),

    /**
     * Commit reads the current draft from this store, joins it with
     * the caller-supplied attacker context, and pushes a
     * `PhysicalAttackDeclared` event by calling the engine's
     * `declarePhysicalAttack` helper. Returns the updated session so
     * the caller can re-seed `useGameplayStore.session` via
     * `setSession`. No-op (returns null) when target / type are
     * missing.
     */
    commitPhysicalAttack: (args) => {
      // Read the latest plan via `getState` rather than capturing it
      // in a closure — avoids stale-state bugs when `set` runs
      // between the panel button click and the forecast confirm.
      const plan = usePhysicalAttackPlanStore.getState().physicalAttackPlan;
      if (!plan.targetUnitId || !plan.attackType) {
        return null;
      }

      const baseSession = args.interactiveSession.getSession();
      const attackerState =
        baseSession.currentState.units[args.attackerId] ?? null;

      // Phase-1 stand-in tonnage — matches `InteractiveSession`
      // (catalog tonnage isn't yet plumbed onto `IGameUnit`).
      const attackerTonnage = args.attackerTonnage ?? 65;
      const targetTonnage = args.targetTonnage ?? 65;
      const hexesMoved =
        args.hexesMoved ?? attackerState?.hexesMovedThisTurn ?? 0;

      const nextSession = declarePhysicalAttack(
        baseSession,
        args.attackerId,
        plan.targetUnitId,
        plan.attackType,
        {
          attackerTonnage,
          targetTonnage,
          pilotingSkill: args.attackerPiloting,
          hexesMoved,
          attackerUnitType: args.attackerUnitType,
          attackerMovementMode: args.attackerMovementMode,
          optionalRules: args.optionalRules,
          targetUnitType: args.targetUnitType,
          limb: plan.limb ?? undefined,
          arm: armForPhysicalLimb(plan.limb),
          twoHandedZweihander: plan.twoHandedZweihander,
          selectedINarcPod: plan.selectedINarcPod,
          weaponsFiredFromArm:
            weaponsFiredFromArmForPhysicalLimb(plan.limb, args) ??
            attackerState?.weaponsFiredThisTurn,
          attackerRanThisTurn:
            args.attackerRanThisTurn ??
            attackerState?.movementThisTurn === MovementType.Run,
          attackerJumpedThisTurn:
            args.attackerJumpedThisTurn ??
            attackerState?.movementThisTurn === MovementType.Jump,
          elevationContext: args.elevationContext,
          terrainContext: args.terrainContext,
        },
      );

      set({ physicalAttackPlan: EMPTY_PHYSICAL_PLAN });
      return nextSession;
    },
  }),
);

function armForPhysicalLimb(
  limb: PhysicalAttackLimb | null,
): 'left' | 'right' | undefined {
  if (limb === 'leftArm') return 'left';
  if (limb === 'rightArm') return 'right';
  return undefined;
}

function weaponsFiredFromArmForPhysicalLimb(
  limb: PhysicalAttackLimb | null,
  args: ICommitPhysicalAttackArgs,
): readonly string[] | undefined {
  if (limb === 'leftArm') return args.weaponsFiredFromLeftArm;
  if (limb === 'rightArm') return args.weaponsFiredFromRightArm;
  return undefined;
}

// ---------------------------------------------------------------------------
// Phase selectors (task 1.1)
// ---------------------------------------------------------------------------

/**
 * Per `add-physical-attack-phase-ui` task 1.1: selector-style helper
 * that reads the current `IGameSession.currentState.phase` and returns
 * `true` when the session is in `GamePhase.PhysicalAttack`. Kept as a
 * pure function rather than a hook so it composes into both
 * React-rendered components (via a Zustand selector) and
 * non-component call sites (tests, integration helpers).
 */
export function isPhysicalAttackPhase(session: IGameSession | null): boolean {
  if (!session) return false;
  return session.currentState.phase === GamePhase.PhysicalAttack;
}

// ---------------------------------------------------------------------------
// Attack-plan selectors (tasks 1.2 + 1.3)
// ---------------------------------------------------------------------------

/**
 * Per `add-attack-phase-ui` task 1.3: selector-style helper returning
 * the current attack plan when the supplied `attackerId` matches the
 * currently-selected attacker in the store. Returns `null` when the
 * requested attacker is not the one the plan was built for so callers
 * don't confuse another unit's UI state with their own.
 *
 * Pure function — keeps composability identical to `isPhysicalAttackPhase`
 * (tests + non-component callers can invoke it without a hook).
 */
export function getAttackPlanFor(
  plan: IAttackPlan,
  activeAttackerId: string | null,
  attackerId: string,
): IAttackPlan | null {
  if (activeAttackerId !== attackerId) return null;
  return plan;
}

/**
 * Per `add-attack-phase-ui` task 1.2: derive whether a session's
 * phase-change requires clearing the in-progress attack plan. The plan
 * is scoped to the Weapon Attack phase; any transition away from that
 * phase invalidates the currently queued target + weapons.
 *
 * Returns `true` when both:
 *   - the previous phase was `WeaponAttack`
 *   - the next phase is anything else (including the same phase re-entered)
 */
export function shouldClearAttackPlanOnPhaseChange(
  prevPhase: GamePhase | null,
  nextPhase: GamePhase | null,
): boolean {
  if (
    prevPhase === GamePhase.WeaponAttack &&
    nextPhase !== GamePhase.WeaponAttack
  ) {
    return true;
  }
  return false;
}
