/**
 * Auto-Grant Skill Awards
 *
 * Awards automatically granted when reaching certain skill levels.
 *
 * @spec openspec/changes/add-awards-system/specs/awards/spec.md
 */

import { AutoAwardCategory } from '../../campaign/awards/autoAwardTypes';
import { AwardRarity, AwardCategory, CriteriaType } from '../AwardInterfaces';
import { createAutoAwards } from './AutoAwardBuilders';

export const AUTO_SKILL_AWARDS = createAutoAwards([
  {
    id: 'expert-marksman',
    name: 'Expert Marksman',
    description: 'Achieved expert gunnery skill.',
    category: AwardCategory.Combat,
    rarity: AwardRarity.Uncommon,
    icon: 'award-expert-marksman',
    criteriaType: CriteriaType.SpecificEvent,
    criteriaThreshold: 1,
    criteriaConditions: { eventType: 'skill_level' },
    criteriaDescription: 'Reach gunnery skill 3 or better',
    sortOrder: 250,
    autoCategory: AutoAwardCategory.SKILL,
    autoThreshold: 3,
    autoThresholdType: 'skill_level',
    skillId: 'gunnery',
  },
  {
    id: 'master-marksman',
    name: 'Master Marksman',
    description: 'Achieved master gunnery skill. Your aim is legendary.',
    category: AwardCategory.Combat,
    rarity: AwardRarity.Rare,
    icon: 'award-master-marksman',
    criteriaType: CriteriaType.SpecificEvent,
    criteriaThreshold: 1,
    criteriaConditions: { eventType: 'skill_level' },
    criteriaDescription: 'Reach gunnery skill 2 or better',
    sortOrder: 260,
    autoCategory: AutoAwardCategory.SKILL,
    autoThreshold: 2,
    autoThresholdType: 'skill_level',
    skillId: 'gunnery',
  },
  {
    id: 'elite-marksman',
    name: 'Elite Marksman',
    description: 'Achieved elite gunnery skill. Perfection incarnate.',
    category: AwardCategory.Combat,
    rarity: AwardRarity.Legendary,
    icon: 'award-elite-marksman',
    criteriaType: CriteriaType.SpecificEvent,
    criteriaThreshold: 1,
    criteriaConditions: { eventType: 'skill_level' },
    criteriaDescription: 'Reach gunnery skill 0',
    sortOrder: 270,
    autoCategory: AutoAwardCategory.SKILL,
    autoThreshold: 0,
    autoThresholdType: 'skill_level',
    skillId: 'gunnery',
  },
  {
    id: 'expert-pilot',
    name: 'Expert Pilot',
    description: 'Achieved expert piloting skill.',
    category: AwardCategory.Combat,
    rarity: AwardRarity.Uncommon,
    icon: 'award-expert-pilot',
    criteriaType: CriteriaType.SpecificEvent,
    criteriaThreshold: 1,
    criteriaConditions: { eventType: 'skill_level' },
    criteriaDescription: 'Reach piloting skill 3 or better',
    sortOrder: 280,
    autoCategory: AutoAwardCategory.SKILL,
    autoThreshold: 3,
    autoThresholdType: 'skill_level',
    skillId: 'piloting',
  },
  {
    id: 'master-pilot',
    name: 'Master Pilot',
    description: 'Achieved master piloting skill. Grace under fire.',
    category: AwardCategory.Combat,
    rarity: AwardRarity.Rare,
    icon: 'award-master-pilot',
    criteriaType: CriteriaType.SpecificEvent,
    criteriaThreshold: 1,
    criteriaConditions: { eventType: 'skill_level' },
    criteriaDescription: 'Reach piloting skill 2 or better',
    sortOrder: 290,
    autoCategory: AutoAwardCategory.SKILL,
    autoThreshold: 2,
    autoThresholdType: 'skill_level',
    skillId: 'piloting',
  },
  {
    id: 'elite-pilot',
    name: 'Elite Pilot',
    description: 'Achieved elite piloting skill. One with the machine.',
    category: AwardCategory.Combat,
    rarity: AwardRarity.Legendary,
    icon: 'award-elite-pilot',
    criteriaType: CriteriaType.SpecificEvent,
    criteriaThreshold: 1,
    criteriaConditions: { eventType: 'skill_level' },
    criteriaDescription: 'Reach piloting skill 0',
    sortOrder: 295,
    autoCategory: AutoAwardCategory.SKILL,
    autoThreshold: 0,
    autoThresholdType: 'skill_level',
    skillId: 'piloting',
  },
]);
