export {
  EDGE_TRIGGERS,
  GENERIC_EDGE_POINT_PRODUCER_IDS,
  OUT_OF_SCOPE_AEROSPACE_EDGE_TRIGGERS,
  REPRESENTED_BATTLEMECH_EDGE_TRIGGERS,
  canUseEdge,
  createEdgeState,
  deriveEdgePointCountFromPilotAbilities,
  resolveEdgeBattleMechTrigger,
  useEdge,
} from './edgeTriggers';
export type {
  EdgeBattleMechTriggerResolution,
  EdgeBattleMechTriggerType,
  IResolveEdgeBattleMechTriggerOptions,
  OutOfScopeAerospaceEdgeTriggerType,
  RepresentedBattleMechEdgeTriggerType,
} from './edgeTriggers';
export {
  calculateBloodStalkerModifier,
  calculateDodgeManeuverModifier,
  calculateFrogmanPhysicalToHitModifier,
  calculateGroundObjectLiftCapacity,
  calculateJumpingJackModifier,
  calculateMeleeSpecialistModifier,
  calculateMultiTaskerModifier,
  calculateNeuralInterfacePilotingModifier,
  calculateShakyStickModifier,
  calculateTerrainMasterDefensiveToHitModifier,
  calculateVdniRangedToHitModifier,
  checkGroundObjectLiftCapacity,
  getAnimalMimicryPSRModifier,
  getClusterHitterBonus,
  getCoolUnderFireHeatReduction,
  getEffectiveWounds,
  getFrogmanWaterPSRModifier,
  getHeavyLifterGroundObjectLiftMultiplier,
  getHotDogHeatTargetNumberModifier,
  getIronManModifier,
  getManeuveringAceFlankingTurningModifier,
  getManeuveringAceOutOfControlModifier,
  getManeuveringAceSkidModifier,
  getMeleeMasterDamageBonus,
  getMeleeSpecialistDamageBonus,
  getMountaineerRubblePSRModifier,
  getSomeLikeItHotHeatPenaltyReduction,
  getSwampBeastBogDownPSRModifier,
  getTacticalGeniusBonus,
  getVdniPilotingModifier,
} from './abilityModifiers';
export {
  calculateGunnerySpecialistModifier,
  calculateRangeMasterModifier,
  calculateSniperModifier,
  calculateWeaponSpecialistModifier,
} from './weaponSpecialists';
export {
  SPA_CATALOG,
  getConsciousnessCheckModifier,
  getObliqueAttackerBonus,
  getSharpshooterBonus,
  getSPAsByCategory,
  getSPACatalogSize,
  getSPAsForPipeline,
  hasSPA,
} from './catalog';
export {
  calculateAttackerSPAModifiers,
  populateAttackerDesignations,
} from './integration';
export type {
  EdgeTriggerType,
  IEdgeState,
  IEdgeUsage,
  ISPACatalogEntry,
  ISPAContext,
  SPACategory,
  SPAPipeline,
} from './types';
