/**
 * Valid per-variant payload fixtures for the combat lifecycle baseline
 * schema pack (replay-safety PR 4).
 *
 * The `game_created` fixture deliberately exercises the deep nested
 * surface: a fully-optioned BattleMech seed (initiative equipment, C3
 * mount, ammo construction, critical slots, armor maps), a vehicle with
 * its `vehicleInit` block, an infantry platoon carrying the complete
 * `IInfantry` construction record, terrain, an authored C3 network,
 * encounter meta, objectives, ground objects, and minefields. The
 * initiative fixtures retain the resolved dice audit trail (raw rolls,
 * modifiers, totals, Tactical Genius fields, consumed `rolls` array) —
 * stored data, not something validation recomputes.
 */

export const VALID_COMBAT_LIFECYCLE_EVENT_PAYLOADS: Readonly<
  Record<string, unknown>
> = Object.freeze({
  game_created: {
    config: {
      mapRadius: 8,
      turnLimit: 12,
      victoryConditions: ['destruction'],
      optionalRules: ['forced_withdrawal'],
      fogOfWar: false,
      environmentalConditions: {
        light: 'daylight',
        precipitation: 'none',
        fog: 'none',
        blowingSand: false,
        wind: 'none',
        gravity: 1,
        atmosphere: 'standard',
        temperature: 'normal',
      },
      encounterId: 'encounter-1',
      campaignId: 'campaign-1',
      contractId: 'contract-1',
      scenarioId: 'scenario-1',
      forcedWithdrawal: true,
      seed: 1337,
    },
    units: [
      {
        id: 'player-1-atlas-as7-d',
        name: 'Atlas AS7-D',
        side: 'player',
        unitRef: 'atlas-as7-d',
        pilotRef: 'pilot-1',
        gunnery: 4,
        piloting: 5,
        pilotSpas: ['tactical_genius'],
        movementMode: 'walk',
        gyroType: 'Standard',
        tonnage: 100,
        heatSinks: 20,
        heatSinkType: 'double',
        hasTSM: false,
        abilities: ['tactical_genius'],
        edgePointsRemaining: 1,
        initiativeHQBonus: 1,
        initiativeEquipment: {
          workingCommunicationsTonnage: 7,
          communicationsMode: 'Default',
          cockpitType: 'Command Console',
          commandConsoleCrewActive: true,
          tonnage: 100,
          weightClass: 'Assault',
          unitType: 'BattleMech',
          hasAdvancedFireControl: true,
        },
        c3Equipment: [
          {
            role: 'master',
            sourceEquipmentId: 'ISC3MasterUnit',
            sourceLocation: 'Head',
            boosted: false,
          },
        ],
        weaponLocationById: { 'weapon-ac20-1': 'Right Torso' },
        ammoConstruction: [
          {
            binId: 'bin-ac20-1',
            weaponType: 'AC/20',
            location: 'Right Torso',
            maxRounds: 5,
            damagePerRound: 20,
            isExplosive: true,
          },
        ],
        criticalSlotManifest: {
          Head: [
            {
              slotIndex: 0,
              componentType: 'cockpit',
              componentName: 'Cockpit',
              destroyed: false,
            },
          ],
          'Right Torso': [
            {
              slotIndex: 3,
              componentType: 'ammo',
              componentName: 'AC/20 Ammo',
              destroyed: false,
              ammoBinId: 'bin-ac20-1',
              explosionDamage: 100,
              explosionRequiresSecondaryEffects: false,
            },
          ],
        },
        armorTypeByLocation: { CT: 'standard' },
        armorByLocation: { CT: 47, CT_rear: 14 },
        structureByLocation: { CT: 31 },
        caseProtection: { RT: 'case' },
        unitType: 'BattleMech',
        isQuad: false,
        boardId: 'board-1',
      },
      {
        id: 'opponent-1-vedette',
        name: 'Vedette',
        side: 'opponent',
        unitRef: 'vedette-vdt',
        pilotRef: 'crew-1',
        gunnery: 4,
        piloting: 5,
        movementMode: 'tracked',
        tonnage: 50,
        unitType: 'Vehicle',
        vehicleInit: {
          motionType: 'Tracked',
          turretType: 'Single',
          engineType: 'Internal Combustion',
          originalCruiseMP: 5,
          armor: { Front: 24, Left: 16, Right: 16, Rear: 12, Turret: 18 },
          structure: { Front: 5, Left: 5, Right: 5, Rear: 5, Turret: 5 },
          criticalAvailability: {
            weaponLocations: ['Turret'],
            weaponLocationCounts: { Turret: 1 },
            jammableWeaponLocations: ['Turret'],
            cargoLoaded: false,
          },
        },
      },
      {
        id: 'opponent-3-proto',
        name: 'Centaur',
        side: 'opponent',
        unitRef: 'centaur-2',
        pilotRef: 'proto-pilot-1',
        gunnery: 4,
        piloting: 5,
        unitType: 'ProtoMech',
        protoMechInit: {
          chassisType: 'Biped',
          hasMainGun: true,
          armorByLocation: { Head: 2, Torso: 8, 'Main Gun': 2 },
          structureByLocation: { Head: 1, Torso: 4 },
        },
      },
      {
        id: 'opponent-2-platoon',
        name: 'Foot Rifle Platoon',
        side: 'opponent',
        unitRef: 'foot-rifle-platoon',
        pilotRef: 'platoon-leader-1',
        gunnery: 4,
        piloting: 5,
        unitType: 'Infantry',
        infantryInit: {
          id: 'inf-1',
          name: 'Foot Rifle Platoon',
          techBase: 'Inner Sphere',
          rulesLevel: 'Standard',
          introductionYear: 2300,
          era: 'Age of War',
          cost: 600000,
          battleValue: 84,
          unitType: 'Infantry',
          tonnage: 3,
          weightClass: 'Light',
          metadata: {
            chassis: 'Foot Platoon',
            model: 'Rifle',
            era: 'Age of War',
            year: 2300,
            rulesLevel: 'Standard',
          },
          totalWeight: 3,
          remainingTonnage: 0,
          isValid: true,
          validationErrors: [],
          motionType: 'Foot',
          movement: { groundMP: 1, jumpMP: 0, umuMP: 0 },
          squadSize: 7,
          armorPerTrooper: 0,
          numberOfSquads: 4,
          platoonStrength: 28,
          primaryWeapon: 'Auto-Rifle',
          secondaryWeaponCount: 0,
          armorKit: 'Standard',
          specialization: 'None',
          fieldGuns: [],
          fluff: {
            overview: 'Garrison platoon.',
            systemManufacturer: {
              communications: 'FieldCom 5',
              targetingAndTracking: 'EyeSight-2',
            },
          },
          hasAntiMechTraining: false,
          isAugmented: false,
          canSwarm: false,
          canLegAttack: false,
        },
      },
    ],
    hexTerrain: [
      {
        coordinate: { q: 0, r: 0 },
        elevation: 1,
        features: [
          { type: 'light_woods', level: 1 },
          {
            type: 'building',
            level: 2,
            constructionFactor: 40,
            buildingId: 'bldg-1',
          },
        ],
      },
    ],
    c3Network: {
      networks: [
        {
          networkId: 'c3-net-1',
          type: 'master-slave',
          teamId: 'player',
          members: [
            {
              entityId: 'player-1-atlas-as7-d',
              teamId: 'player',
              role: 'master',
              position: { q: 0, r: 0 },
              operational: true,
              ecmDisrupted: false,
            },
          ],
        },
      ],
    },
    encounterMeta: {
      encounterId: 'encounter-1',
      encounterName: 'Bridgehead at Kearny',
      templateType: null,
      playerForceSummary: 'Lance Alpha (4500 BV, 1 unit)',
      opponentSummary: 'Garrison (2 units)',
    },
    objectives: {
      '2,3': {
        id: 'objective-1',
        hexKey: '2,3',
        objectiveType: 'capture',
        owningSide: 'neutral',
        controlSide: 'neutral',
        controlRule: 'sole-occupancy',
        holdTurnsRequired: 2,
        holdProgress: 0,
      },
    },
    groundObjects: {
      'cargo-1': {
        id: 'cargo-1',
        name: 'Supply Crate',
        tonnage: 2,
        position: { q: 1, r: 1 },
      },
    },
    minefields: {
      '4,4': {
        type: 'conventional',
        damagePerLeg: 6,
        density: 10,
        source: 'scenario',
      },
    },
  },
  game_started: { firstSide: 'player' },
  game_ended: { winner: 'player', reason: 'destruction', turns: 9 },
  turn_started: { _type: 'turn_started' },
  turn_ended: { _type: 'turn_ended' },
  phase_changed: { fromPhase: 'initiative', toPhase: 'movement' },
  initiative_rolled: {
    playerRoll: 9,
    opponentRoll: 6,
    playerModifier: 2,
    opponentModifier: 0,
    playerTotal: 11,
    opponentTotal: 6,
    tacticalGeniusRerollSide: 'player',
    playerOriginalRoll: 4,
    opponentOriginalRoll: 6,
    winner: 'player',
    movesFirst: 'opponent',
    rolls: [2, 2, 4, 2, 5, 4],
  },
  initiative_order_set: {
    winner: 'player',
    firstMover: 'opponent',
    secondMover: 'player',
  },
});
