/**
 * CommitMoveButton
 *
 * Per `add-combat-phase-ui-flows`: primary "lock in your move" button
 * for the Movement-phase action panel. Disabled until the player has
 * picked both a destination AND a facing on `plannedMovement`.
 *
 * Renders a `MovementHeatPreview` chip beside the button so the player
 * can sanity-check the heat impact before committing.
 */

import React from 'react';

import type { MovementHeatProfile } from '@/types/gameplay';

import { MovementType } from '@/types/gameplay';

import { MovementHeatPreview } from './MovementHeatPreview';

export interface CommitMoveButtonProps {
  /** True when destination + facing are both set on the plan */
  ready: boolean;
  /** MP cost shown next to the button label */
  mpCost: number;
  /** Movement type for heat preview */
  movementType: MovementType;
  /** Exact heat generated by the projected movement, when known. */
  heatGenerated?: number;
  /** Rules-level movement heat source for fallback previews. */
  movementHeatProfile?: MovementHeatProfile;
  /** Rules-level movement mode used for terrain/elevation pathing. */
  movementMode?: string;
  /** Terrain modifier paid on the final step into the destination hex. */
  terrainCost?: number;
  /** Elevation delta from the previous path hex into the destination hex. */
  elevationDelta?: number;
  /** Elevation MP paid on the final step into the destination hex. */
  elevationCost?: number;
  /** Hexes the unit will jump (only used when type === Jump) */
  jumpHexes?: number;
  /** Callback to fire when the player commits */
  onCommit: () => void;
  /** Optional className */
  className?: string;
}

export function CommitMoveButton({
  ready,
  mpCost,
  movementType,
  heatGenerated,
  movementHeatProfile,
  movementMode,
  terrainCost,
  elevationDelta,
  elevationCost,
  jumpHexes,
  onCommit,
  className = '',
}: CommitMoveButtonProps): React.ReactElement {
  const buttonClasses = ready
    ? 'cursor-pointer bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500'
    : 'cursor-not-allowed bg-gray-300 text-gray-500';
  const hasRulesSummary =
    movementMode !== undefined ||
    terrainCost !== undefined ||
    elevationDelta !== undefined ||
    elevationCost !== undefined;

  return (
    <div
      className={`flex flex-col gap-2 ${className}`}
      data-testid="commit-move-button-wrapper"
    >
      <MovementHeatPreview
        movementType={movementType}
        heatGenerated={heatGenerated}
        movementHeatProfile={movementHeatProfile}
        jumpHexes={jumpHexes}
      />
      {hasRulesSummary && (
        <MovementCommitSummary
          movementMode={movementMode}
          terrainCost={terrainCost}
          elevationDelta={elevationDelta}
          elevationCost={elevationCost}
        />
      )}
      <button
        type="button"
        onClick={onCommit}
        disabled={!ready}
        className={`min-h-[44px] rounded px-4 py-2 font-medium transition-colors focus:ring-2 focus:ring-offset-2 focus:outline-none ${buttonClasses}`}
        data-testid="commit-move-button"
      >
        Commit Move ({mpCost} MP)
      </button>
    </div>
  );
}

interface MovementCommitSummaryProps {
  readonly movementMode?: string;
  readonly terrainCost?: number;
  readonly elevationDelta?: number;
  readonly elevationCost?: number;
}

function formatModeLabel(mode: string): string {
  switch (mode) {
    case 'vtol':
      return 'VTOL';
    case 'wige':
      return 'WiGE';
    case 'umu':
      return 'UMU';
    case 'biped_swim':
      return 'Biped swim';
    case 'quad_swim':
      return 'Quad swim';
    default:
      return mode.charAt(0).toUpperCase() + mode.slice(1).replace(/_/g, ' ');
  }
}

function formatSigned(value: number): string {
  return value > 0 ? `+${value}` : String(value);
}

function MovementCommitSummary({
  movementMode,
  terrainCost,
  elevationDelta,
  elevationCost,
}: MovementCommitSummaryProps): React.ReactElement {
  const summaryParts = [
    movementMode ? `mode ${movementMode}` : null,
    terrainCost !== undefined ? `terrain cost ${terrainCost}` : null,
    elevationDelta !== undefined
      ? `elevation delta ${formatSigned(elevationDelta)}`
      : null,
    elevationCost !== undefined ? `elevation cost ${elevationCost}` : null,
  ].filter(Boolean);

  return (
    <dl
      className="grid grid-cols-2 gap-x-3 gap-y-1 rounded border border-gray-200 bg-gray-50 px-3 py-2 text-xs text-gray-700"
      aria-label={`Movement rules summary: ${summaryParts.join('; ')}`}
      data-testid="movement-commit-summary"
      data-movement-mode={movementMode}
      data-terrain-cost={terrainCost}
      data-elevation-delta={elevationDelta}
      data-elevation-cost={elevationCost}
    >
      {movementMode && (
        <div>
          <dt className="font-semibold text-gray-500">Mode</dt>
          <dd>{formatModeLabel(movementMode)}</dd>
        </div>
      )}
      {terrainCost !== undefined && (
        <div>
          <dt className="font-semibold text-gray-500">Terrain</dt>
          <dd>{formatSigned(terrainCost)} MP</dd>
        </div>
      )}
      {elevationDelta !== undefined && (
        <div>
          <dt className="font-semibold text-gray-500">Elevation</dt>
          <dd>{formatSigned(elevationDelta)}</dd>
        </div>
      )}
      {elevationCost !== undefined && (
        <div>
          <dt className="font-semibold text-gray-500">Elev. Cost</dt>
          <dd>{formatSigned(elevationCost)} MP</dd>
        </div>
      )}
    </dl>
  );
}

export default CommitMoveButton;
